FlowCrypt/flowcrypt-browser

- src/chrome/settings/modules/keyserver.js
- src/js/common/storage.js
> Adds interface for removing send-from addresses - closes #96

- chrome/chrome/settings/settings.ts
- chrome/css/webmail.css
- chrome/js/content_scripts/factory.ts
- chrome/manifest.json
- package-lock.json
- package.json
Issue #1076
- Updates Secure Compose button for Gmail's Redesign
-alt
> Update Secure Compose button for Gmail's Redesign

- chrome/css/webmail.css
Minor styling update
References #1076
> Styling update for Secure Compose button

- chrome/chrome/settings/index.htm
- chrome/chrome/settings/settings.css
Not quite an active issue for this, but updating logo to svg is a nice small touch.
> Update logo to svg

- chrome/chrome/elements/subscribe.htm
- chrome/chrome/settings/modules/backup.htm
- chrome/css/cryptup.css
- chrome/css/mobile-menu-styling.css
> Fixes mobile table bugs on subscribe and backup pages

- chrome/chrome/settings/modules/backup.htm
- chrome/css/cryptup.css
> Updates backup label styling bug 

- chrome/chrome/popups/select_account.htm
- chrome/chrome/popups/select_account.ts
- chrome/chrome/settings/index.htm
- chrome/chrome/settings/index.ts
- chrome/chrome/settings/settings.css
- chrome/css/cryptup.css
- chrome/css/mobile-menu-styling.css
Improves overall consistency and styling updates for Selecting accounts.
> Styling updates for settings and browser extension 'select accounts' functionality.

- extension/chrome/elements/pgp_block.ts
https://github.com/FlowCrypt/flowcrypt-browser/issues/1444 was already fixed, so I decided to go for the "bonus points" from the comment here: https://github.com/FlowCrypt/flowcrypt-browser/issues/1444#issuecomment-461588172
@tomholub
> Make wrong password warning red

- extension/chrome/settings/modules/compatability.ts
executes all tests in the following cases:
1) either private or public key
2) private key is not decrypted
3) key has no valid encryption packet
4) the actual key is scambled but the integrity check is restored as suggested by the error
instead of using the public key, I used a try/catch in the encrypt-decrypt test. Im still hazy on what information is common to both pub/prv. 
Also, and this I will need you to evaluate, I provided a private key, then I moved a few lines of the key block around, I corrected the integrity check, and provided my password. But the sign/verify test would still complete successfully. I don't know the anatomy of these keys, so I am probably not the best person to come up with test-cases at this time, but I feel like it is something i should mention incase it is …
> fixes #1547 and addresses changes cited in comments on in #1257

- extension/chrome/settings/index.htm
- extension/chrome/settings/index.ts
- extension/js/common/api/api.ts
Let me know if you'd like to see it implemented in some other way.
> list the blog entries returned by /feed endpoint.

- extension/manifest.json
@tomholub for future reference - would you like me to mention you in a comment for new PRs, or is adding you as a reviewer sufficient?
> Add line item to manifest

- extension/chrome/elements/add_pubkey.htm
- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/attachment.ts
- extension/chrome/elements/attest.ts
- extension/chrome/elements/compose.ts
- extension/chrome/elements/passphrase.ts
- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/reply_pubkey_mismatch.ts
- extension/chrome/elements/sending_address.ts
- extension/chrome/elements/shared/footer.ts
- extension/chrome/popups/select_account.ts
> light refactoring andcode style

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
- extension/js/common/composer.ts
fixes #612 
* add new icon to compose.htm
* copy styles of close_new_message for new icon
* media query for hiding other blocks in compose window
* event handler for clicking new icon to minimize/maximize parent window
> issue #612 - minimize secure compose window

- extension/js/common/composer.ts
> issue-1072 Load recipients while draft is loading

- extension/chrome/elements/compose.htm
- extension/chrome/elements/shared/attach.template.htm
- extension/css/cryptup.css
- extension/css/fine-uploader-new.css
- extension/js/common/browser.ts
- extension/js/common/composer.ts
> Issue-535 Fixed owerlap when some files uploaded

- extension/js/common/browser.ts
> issue-1649 Changed download text and made the whole block clickable

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
Here is how it looks like now:
> Issue 1653 composer input now shown

- extension/css/cryptup.css
- extension/lib/featherlight/featherlight.css
- extension/lib/featherlight/featherlight.js
I've checked this method because it uses featherlight:
`Ui.renderOverlayPromptAwaitUserChoice({ finishSetup: {}, later: { color: 'gray' } }, msg);`
Everything looks the same way
#1625
> Issue #1625 Changed version from 1.7.0 to 1.7.13

- extension/js/common/composer.ts
> Issue 1659 recipients dublicate

- extension/chrome/elements/backup.htm
- extension/chrome/elements/backup.ts
- extension/chrome/settings/modules/test_passphrase.ts
- extension/css/cryptup.css
- extension/css/webmail.css
- extension/js/common/browser.ts
- extension/js/common/core/att.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
- extension/manifest.json
> Issue 1648 recognize backup

- extension/chrome/settings/inbox/inbox.ts
- extension/js/common/core/mime.ts
- extension/js/common/xss_safe_factory.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> Issue 1648 corrections recognize backup

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/setup.ts
- extension/js/common/api/google.ts
- extension/js/common/composer.ts
- extension/js/common/core/pgp.ts
- extension/js/common/platform/store.ts
> Issue 1704 update pubkeys

- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue #1703 corrected RegEx for filterAtts

- extension/chrome/settings/modules/backup.ts
#1685 
Perhaps would be better to use `modal.info` function, what do you think?
> issue-1685 added confirmation modal window

- extension/chrome/elements/compose.ts
> Issue 1070 honor reply-to

- extension/js/common/core/mime.ts
- test/source/tests/tests/gmail.ts
#1718 
Approx 2 hours, took a bit longer than expected because the issue turned out to be with one of our dependencies (email.js), somewhat deeper than I thought.
> Issue 1718 pubkey encoding

- extension/chrome/elements/pgp_block.htm
- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_pubkey.htm
- extension/js/common/core/mime.ts
- extension/js/common/core/pgp.ts
- extension/js/common/platform/require.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
- extension/types/emailjs.d.ts
- extension/types/openpgp.d.ts
- test/source/tests/browser_recipe.ts
- test/source/tests/tests/decrypt.ts
- test/source/tests/tests/elements.ts
#1667 
~ 8 hrs
Took about as long as I'd expect, signature verification can be tricky to debug.
> fixed detached signatures

- extension/js/common/composer.ts
- package.json
firefox on windows.
Time Spent: 1h
No issues
> issue #1753 set height to 0 instead of unset, added script to run

- extension/js/common/core/mime.ts
- test/tests.json
> Issue 1760 parse signed

- extension/chrome/settings/setup.ts
> take user straight to gmail from setup

- extension/js/common/composer.ts
Issue #1691 
Time Spent: 1h
Done without any issues
> issue #1691 check if the message is being sent and show confirm modal

- extension/js/common/composer.ts
- extension/js/common/core/common.ts
Issue #1717 
Time Spent: 5h
is it okay if I'm reloading composer this way?:
```javascript
this.app.closeMsg();
BrowserMsg.send.openNewMessage(this.urlParams.parentTabId);
```
Or there is a better way?
> Issue 1717 pull list email aliases

- extension/lib/openpgp.js
- extension/lib/openpgp.worker.js
> update openpgp.js to 4.5.5

- extension/css/cryptup.css
- extension/js/common/core/pgp.ts
- extension/types/openpgp.d.ts
#1772
5 hours. This was likely openpgp.js bug https://github.com/openpgpjs/openpgpjs/issues/916
> verify encrypted signed msgs

- extension/js/common/composer.ts
Issue #1575 
Time Spent: 3h
Done without issues because all your comments in the task helped a lot
> issue #1575 Added ability to paste pub key directly in recipients box

- extension/chrome/elements/shared/footer.htm
- extension/chrome/elements/shared/footer.ts
Issue #1038 
Time Spent: ~10h
Almost all the time (8-9h) I was investigating why it didn't validate the signature.
> Issue 1038 signed message broken footer

- extension/chrome/elements/compose.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.ts
- extension/js/common/api/email_provider_api.ts
- extension/js/common/composer.ts
- extension/js/common/core/common.ts
- extension/js/common/platform/store.ts
- extension/js/common/settings.ts
- test/source/browser/browser_pool.ts
#1779 
2 hrs
Used in more places than I thought
> refactor parseEmail to validate email

- .vscode/tasks.json
- extension/chrome/elements/pgp_block.ts
- extension/js/background_page/background_page.ts
- extension/js/background_page/bg_handlers.ts
- extension/js/common/api/attester.ts
- extension/js/common/extension.ts
- extension/js/common/platform/store.ts
- test/source/test.ts
- test/source/tests/browser_recipe.ts
- test/source/tests/index.ts
- test/source/tests/tests/account.ts
- test/source/tests/tests/compose.ts
- test/source/tests/tests/decrypt.ts
- test/source/tests/tests/elements.ts
- test/source/tests/tests/gmail.ts
- test/source/tests/tests/settings.ts
- test/source/tests/tests/setup.ts
- test/source/tests/tests/unit.ts
total 4 hrs at this point
#811
> issue #811-verify-load-pubkey branch 2

- extension/chrome/elements/compose.htm
- extension/js/common/composer.ts
- test/source/mock/google-api-mock.ts
- test/source/tests/tests/compose.ts
Issue: #1794 
Time Spent: ~5h
I didn't know the tests are running on `test.ci.compose@org.flowcrypt.com ` and then I need mock returned `Not Implemented` Error so I had to fix it and after all of it, I had to use `testWithSemaphoredGlobalBrowser` instead of `testWithNewBrowser` because `testWithNewBrowser` didn't work.
Can you pleaase explain the difference between `testWithSemaphoredGlobalBrowser` & `testWithNewBrowser`?
> Issue #1794 Created test for 873 issue

- extension/chrome/elements/passphrase.htm
- extension/js/common/composer.ts
- test/source/tests/tests/compose.ts
Issue #1797 
Time Spent: 7h
I had some troubles with PassPhrase modal window, It didn't show in the test.
Then I tried to use `inboxPage` and it worked.
> Issue #1797 Created two tests for quoting reply part with passphrase

- extension/chrome/elements/compose.ts
- extension/js/common/composer.ts
Issue #1817 
Time Spent: 40-50min
went smoothly
> issue #1817 Add replying headers before adding three dots

- .semaphore/semaphore.yml
> #1822 use SEMAPHORE_PIPELINE_ID for sharing sources

- extension/chrome/elements/compose.ts
> #1825 enable background worker in compose.ts

- extension/chrome/elements/pgp_block.ts
- extension/js/common/core/pgp.ts
- extension/js/common/platform/store.ts
- test/source/tests/tests/decrypt.ts
#1777 and #1827
about 4 hrs so far - a bunch of things related to local contacts needed fixing first, which I didn't expect
> Issue #1777 verify encrypted msg test

- extension/js/common/core/pgp.ts
#1829
20 minutes
read stream to end before attempting to verify
> #1829 refactor message verify

- extension/js/common/composer.ts
Issue #791 
Time Spent: 1h 40m
Went smoothly
> Issue #791 Added names in email headers

- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/js/common/rules.ts
> issue #1729 ENFORCE_ATTESTER_SUBMIT org rule for setup

- extension/js/common/composer.ts
> Issue 1833 move cleaning thread

- extension/js/common/core/mime.ts
#1843 
40 mins so far, renders, but verification does not match yet
> issue #1843 GPGTools signed compatibility

- extension/chrome/settings/setup.ts
- extension/js/common/api/google.ts
- extension/js/common/core/pgp.ts
- extension/js/common/lang.ts
> issue #1850 refactor recovery, count by longids, support several keys per file

- test/source/mock/google-api-mock.ts
- test/source/tests/tests/compose.ts
> Issue 1856 test aliases

- extension/css/cryptup.css
- extension/css/webmail.css
> Issue #1839 Changed 'absolute' position to 'fixed'

- extension/js/common/composer.ts
- extension/js/common/rules.ts
- test/source/tests/tests/account.ts
Issue #1744 
Time Spent: 1h 30m
Went smoothly
> issue #1744 Added emails whitelist that can send large attachments

- extension/css/cryptup.css
Issue #1865 
Time Spent: 5m for adding background color but I'd spent about 2h before for making it looks like what I described in the comment:
https://github.com/FlowCrypt/flowcrypt-browser/issues/1865#issuecomment-517705260
> Issue 1865 added white background

- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue #1746 Check in local DB first and then lookup on keyserver

- test/source/mock/data.ts
- test/source/mock/google-api-mock.ts
- test/source/mock/strategies/send-message-strategy.ts
- test/source/mock/strategies/strategy-base.ts
- test/source/tests/tests/compose.ts
- test/source/util/index.ts
> issue #1798 Added test for testing if the message contains prev quoute

- extension/chrome/elements/compose.htm
- extension/js/common/composer.ts
- test/source/tests/tests/compose.ts
> Issue #1879 Hid and intro btn and wrote a test for it

- extension/js/common/core/buf.ts
- extension/js/common/core/mime.ts
- extension/js/common/core/pgp.ts
- extension/js/common/core/types/openpgp.d.ts
> #1888 update core from mobile

- extension/js/common/core/att.ts
> #1893 mail.ch compat

- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/modules/compatibility.ts
- extension/js/common/core/pgp.ts
- extension/js/common/core/types/openpgp.d.ts
> Issue #1895 expired key

- extension/chrome/elements/compose.htm
> Add titles for header buttons

- extension/js/common/browser.ts
- extension/js/common/composer.ts
> Close the 'New Secure Message' on Esc keydown

- extension/js/common/core/pgp.ts
> #1930 improve dateBeforeExpiration

- extension/js/common/composer.ts
- extension/js/common/extension.ts
- extension/js/content_scripts/webmail/setup_webmail_content_script.ts
Closes #1910 
Used this SO answer as a hint: https://stackoverflow.com/a/1784925
> Focus iframe before focusing #input_to (Firefox needs that)

- extension/css/cryptup.css
- extension/css/webmail.css
Closes #1937
Also in scope of this PR I added the `.new_message` height animation discussed in https://github.com/FlowCrypt/flowcrypt-browser/pull/1933#issuecomment-521162836
@tomholub let me know if that's okay to submit two different things into one PR in case the second change is tiny, or the practice is to be stricter and create PR for every logical scope including one-liners.
> Add text-overflow: ellipsis to contacts items to prevent wrapping long contacts

- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/change_passphrase.ts
- extension/js/common/core/pgp.ts
- extension/js/common/core/types/openpgp.d.ts
- extension/js/common/settings.ts
> #1942 more defensive key decrypt / encrypt handling

- extension/chrome/elements/backup.ts
- extension/chrome/elements/passphrase.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/change_passphrase.ts
- extension/chrome/settings/modules/compatibility.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/modules/security.ts
- extension/chrome/settings/modules/test_passphrase.ts
- extension/chrome/settings/setup.ts
- extension/js/common/composer.ts
- extension/js/common/core/pgp.ts
- extension/js/common/settings.ts
- extension/js/common/ui/key_import_ui.ts
> refactor Pgp.key.decrypt to accept single pp

- extension/js/common/composer/composer-contacts.ts
> Issue 1941 Limit the number of rendered contacts to 10

- extension/css/cryptup.css
- extension/js/common/composer.ts
> Click on header acts like minimize/maximize button

- extension/css/cryptup.css
- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
Closes #1924 
Closes #1934
Also re-enabled `Esc` for closing the 'New Secure Message' window (rollback of https://github.com/FlowCrypt/flowcrypt-browser/commit/1ba6be58ec109c015daf3e996df91f953381aa8f)
> Issue 1924 contacts keyboard navigation

- extension/js/common/composer.ts
> Close maximized window on body (backdrop) click only

- extension/chrome/elements/compose.htm
- extension/chrome/elements/compose.ts
- extension/css/cryptup.css
Closes #1906
Replaced action `<div>`s with `<button>`s with appropriate `tabindex`es so they are focusable and clickable with keyboard (Enter or Space).
What I wasn't able to achieve is to trigger file upload dialog with the keyboard. By hitting Space or Enter the button is getting clicked, not the `<input>` inside it. @tomholub Do you maybe have any hint which could help here?
> Align focused state of action buttons with their hover state

- extension/css/cryptup.css
- extension/js/common/browser.ts
- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
> Issue 1907 focus trap

- extension/js/common/composer.ts
> Do not activate Tab when composed window is minimized

- extension/js/common/composer.ts
> Remove unnecessary tabindex

- extension/js/common/core/pgp.ts
- extension/js/common/core/types/openpgp.d.ts
- extension/lib/openpgp.js
> Issue 1972 gpg dummy fix and openpgpjs upgrade

- extension/chrome/dev/export.ts
- extension/chrome/elements/compose.ts
- extension/js/common/platform/require.ts
- test/source/mock.ts
> issue 1974 require openpgp from pgp file

- extension/chrome/elements/compose.ts
- extension/chrome/settings/inbox/inbox.htm
- extension/js/common/inject.ts
> Issue #1877 small refactoring

- extension/chrome/settings/setup.ts
> Issue #1885, filtered addresses that we can submit key to

- extension/css/cryptup.css
Issue #1990
Time Spent: 15m
Result with scroll:
Result without scroll:
> Issue #1990, changed top&right position of icon

- extension/chrome/elements/pgp_pubkey.htm
- extension/chrome/elements/pgp_pubkey.ts
Issue #1981 
Time Spent: ~1h 30m
> Issue #1981, Allowed users to see details of not usable pub key

- extension/chrome/settings/modules/contacts.ts
- extension/css/cryptup.css
- extension/js/common/core/pgp.ts
> Issue #1977, Added validation and error messages

- extension/chrome/elements/pgp_block.ts
- extension/js/common/composer/composer-quote.ts
Issue #1741 
Time Spent: 1h 15m
> Issue #1741, Changed text and corrected quoting algorithm

- extension/js/background_page/background_page.ts
- extension/js/background_page/inject.ts
- extension/manifest.json
- tooling/build-manifests.ts
> Issue 1995 firefox content scripts

- extension/js/common/composer/composer-contacts.ts
> Issue #1998, Added Title attribute to the recipients when collapsing

- extension/js/common/api/google.ts
> issue 2004 oauth csrf token

- extension/chrome/elements/shared/footer.ts
- extension/js/common/api/google.ts
- extension/js/common/composer.ts
- extension/js/common/core/mime.ts
- extension/js/common/inject.ts
- extension/js/common/platform/store.ts
- extension/js/content_scripts/webmail/setup_webmail_content_script.ts
- extension/js/content_scripts/webmail/webmail.ts
- extension/types/jquery.d.ts
- package.json
> upgraded ts to 3.6.2 + fixes

- extension/chrome/elements/reply_pubkey_mismatch.htm
- extension/chrome/elements/reply_pubkey_mismatch.ts
- extension/css/cryptup.css
- extension/js/common/api/email_provider_api.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
Issue #2001 and #1999
Time Spent: 1h 30m
> Issue 2001 error when asking sender for key

- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/debug_api.ts
- extension/chrome/settings/modules/experimental.htm
- extension/chrome/settings/modules/experimental.ts
- extension/js/common/api/backend.ts
- extension/js/common/api/google.ts
- test/source/mock/google-api-mock.ts
- test/source/mock/oauth.ts
> issue 2012 openid login prep

- extension/js/common/api/google.ts
> add back profile permission for name in id_token

- extension/css/cryptup.css
Issue #1970,
Time Spent: 15m
Result:
> Issue #1970, corrected margin

- extension/css/cryptup.css
Issue #1845,
Time Spent: 10m
Result:
> [<1h] Issue #1845, Added css style to show whitespace

- extension/chrome/elements/pgp_block.ts
- extension/chrome/settings/index.ts
- extension/js/common/api/backend.ts
- extension/js/common/platform/catch.ts
- lgtm.yml
> Issue #2029 lgtm fixes

- extension/chrome/elements/compose.ts
- extension/js/common/xss_safe_factory.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
> [3h+] issue #1493 - rm reply headers from url

- extension/js/common/composer/composer-contacts.ts
- extension/js/common/inject.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
- test/source/patterns.ts
> expand jquery xss checks

- extension/css/cryptup.css
- extension/js/common/browser.ts
#1957 
I set the toast opacity to `0.8` because `0.7` IMO has low contrast with the message body.
Screenshot:
> Add Ui.toast(msg: string) method

- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/css/cryptup.css
Issue #2060,
Time Spent: 1h (including investigation of the issue)
> Issue #2060, open in new tab

- extension/chrome/elements/compose.htm
- extension/chrome/elements/compose.ts
- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
- test/source/browser/browser_pool.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
> auto-focus recipients or text based on msg type

- extension/chrome/settings/index.htm
- extension/chrome/settings/modules/security.htm
- extension/css/cryptup.css
- extension/css/settings.css
> Issue #1689, Group security Settings into logical groups, remove the security settings block from Additional settings

- test/source/tests/tests/setup.ts
> Issue #1675, changed usedPgp before to true

- test/source/tests/tests/decrypt.ts
> Issue #1789, added a test to check failure

- extension/js/common/composer/composer-contacts.ts
> Issue #1957, Add toasts when clicking PK icon

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
- extension/js/common/composer.ts
- test/source/tests/tests/compose.ts
Closes #2046
Also did some tiny refactorings per prior agrement (classes for CSS, ids for JS)
> Issue #2046, Make Send Options keyboard-friendly

- extension/chrome/elements/compose.htm
- extension/js/common/composer.ts
> Issue #1905, make header title toggle the minimized state

- package.json
> issue #2086 fix tests - package.json web-ext update

- extension/js/common/composer.ts
- extension/js/common/extension.ts
- extension/js/content_scripts/webmail/setup_webmail_content_script.ts
- package.json
@tomholub I accidentally pressed the "Create PR" button instead of creating a draft :man_facepalming: 
I need you help here. This change should fix the issue, but for now it doesn't. It seems that this listener isn't being triggered https://github.com/FlowCrypt/flowcrypt-browser/pull/2084/files#diff-668908dbb47e93967b144b8ef0658932R109 and I can't understand why. Could you give me any hint on this?
> Issue #1517, Focus body after sending message to make Gmail shortcuts work

- extension/js/common/ui/passphrase_ui.ts
> Issue #1586, toggle the visibility of all other visible password fields on the page

- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
- extension/js/common/composer/composer-draft.ts
- test/source/tests/tests/compose.ts
Issue #2076,
Time Spent: 1h 30m (1h for a test, 30m for fixing)
I know this is not the best way of fixing it and I'm going to refactor it in #2031, 
I want to change `  private popoverItems?: ComposerPopoverItem[];` from array to dictionary (it would simplify send btn code) but this thing isn't for this PR so I decided to do it today later in another PR.
> Issue 2076 replying to signed msg

- build.sh
- package.json
> issue #2092 option to only build static assets

- extension/chrome/elements/compose.ts
- extension/js/common/composer.ts
Issue #2101 
Time Spent: 2h 30m (2h investigating, 30m fixing)
> Issue #2101, check if there aliases in 'storage.addresses' property

- extension/chrome/settings/index.htm
- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/css/cryptup.css
- extension/css/settings.css
> Allow account switching during the setup phase

- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/modules/add_key.ts
- extension/chrome/settings/modules/backup.htm
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/change_passphrase.htm
- extension/chrome/settings/modules/change_passphrase.ts
- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/css/cryptup.css
- extension/js/common/settings.ts
- extension/js/common/ui/key_import_ui.ts
- test/source/tests/page_recipe.ts
Issue #1503, 
Time Spent: 7h (4h dev, ~3h CSS corrections, testing and fixing)
I replaced all `Settings.renderPwdStrength` with the new method `keyImportUi.validateInputPP` that generates all necesarry HTMLElements to show to user PP validation.
> Issue 1503 pp strength during import key without pp

- extension/chrome/settings/setup.ts
- extension/css/cryptup.css
- extension/css/sweetalert2.css
- extension/js/common/browser.ts
- extension/js/common/ui/passphrase_ui.ts
- extension/lib/sweetalert2.js
- extension/types/sweetalert2.d.ts
- package.json
- test/source/browser/controllable.ts
- test/source/tests/page_recipe.ts
> Set Up: enforce users to write down their passphrase

- extension/chrome/elements/pgp_block.ts
> Issue #1508, Changed text

- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
Issue #306,
Time Spent: ~2h
Everything went smoothly, also I found and fixed one bug. 
When we called `refreshRecipients` method it replaced the whole element along with its attributes and after this action drag&drop and remove recipient functions stopped working. Now it's fixed
> Issue #306, re-evaluate when changing send_from

- extension/js/common/composer/composer-contacts.ts
> issue #2119 fix null and undefined elements

- extension/chrome/settings/modules/contacts.ts
- extension/js/common/composer/composer-quote.ts
- extension/js/common/composer/interfaces/composer-types.ts
- extension/js/common/ui/att_ui.ts
Issue #984,
Time Spent: 5h
Now when we forward a message the attachments will be added to the forwarded message too,
Originally I was thinking to send encrypted attachments without decryption and encryption again but then I realized that we will have a `key mismatch` issue so I had to decrypt and encrypt them with primary user private key.
> [9h] Issue #984, Decrypt and add attachments from previous message

- extension/chrome/elements/compose.ts
- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/reply_pubkey_mismatch.ts
- extension/chrome/elements/subscribe.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/setup.ts
- extension/js/common/api/google.ts
- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
- extension/js/common/composer/interfaces/composer-app-functions.ts
- extension/js/common/platform/store.ts
- extension/js/content_scripts/webmail/webmail.ts
Issue #2073 
Time Spent: 1h 20m
> [2h] Issue #2073, Created GetScopes Method

- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- extension/css/cryptup.css
- test/source/tests/page_recipe.ts
> [1h] issue #2070 pub and prv on one screen

- extension/js/common/ui/att_ui.ts
Issue #2139,
Time Spent: 1h
According to docs, I changed `onSubmitted` to `onSubmit` and started throwing errors when a user can't upload files anymore
> Issue #2139, changed AttUI to make it working properly

- test/source/tests/tests/compose.ts
> Issue #2145, do not check undefined values

- extension/chrome/elements/compose.htm
> Issue #2143, add title to triple dot

- extension/js/common/api/sks.ts
> issue #2108 choose from sks based on uid as well

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/settings/modules/contacts.ts
- extension/js/common/ui/fetch_key_ui.ts
@tomholub, please check how it works
if everything is okay I will do the same for `Add a pubkey to email address` page
> Issue #1692, download keys when pasting in text area

- extension/chrome/settings/modules/security.htm
- extension/chrome/settings/modules/security.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
- test/source/tests/tests/decrypt.ts
- test/source/tests/tests/settings.ts
> Issue 1806 forget pp

- extension/chrome/elements/compose.ts
- extension/chrome/elements/reply_pubkey_mismatch.ts
- extension/js/common/composer.ts
- extension/js/common/composer/interfaces/composer-app-functions.ts
- extension/js/common/settings.ts
Issue #2164, #2140
Time Spent: 3h
Sorry for the delays, it was done on Thursday but I could make a PR only now due to the internet issues.
> Issue 2164 2140 update sendas rendering

- .semaphore/semaphore.yml
- extension/css/cryptup.css
- extension/css/settings.css
Follow-up for #2173
- fixed all stylelint issues
- added `test_stylelint` task to CI
> Fix stylelint issues, add test_stylelint to CI

- extension/js/common/composer/composer-send-btn.ts
Issue #2166,
Time Spent: 1h 30m. (~1h 25m for investigation)
This also fixes what I described in the comment in the issue.
> [2h] Issue #2166, strip comma from the name when sending email

- extension/js/common/inject.ts
- extension/js/common/xss_safe_factory.ts
Issue #2162,
Please do not close 2162 because I want to make sure it won't happen again.
Thanks
> Issue #2162, added catch report, corrected selector

- test/source/mock/google-api-mock.ts
- test/source/mock/strategies/send-message-strategy.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
> Issue #2136, Created Tests for footer

- extension/js/common/inject.ts
> more general end session btn

- extension/js/common/extension.ts
> use plain div instead of Swal in content script

- extension/chrome/popups/default.ts
- extension/js/common/extension.ts
> render popup errors

- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.ts
- extension/js/common/api/api.ts
- extension/js/common/lang.ts
- extension/js/common/settings.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> notify admin policy err

- extension/js/common/composer/composer-render.ts
- extension/js/common/composer/composer-send-btn.ts
> Issue 2195 hide meta att

- extension/js/common/composer/composer-render.ts
- extension/js/common/composer/composer-send-btn-popover.ts
- extension/js/common/platform/store.ts
> issue 2198 sticky rich text

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/settings/modules/contact_page.ts
- extension/chrome/settings/modules/contacts.ts
- extension/js/common/composer/composer-atts.ts
- extension/js/common/ui/att_ui.ts
- extension/js/common/ui/key_import_ui.ts
> use specialized uiChanged callback for handling attachments

- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue 2201 fix scroll to reply box

- extension/js/common/composer/composer-quote.ts
issue #2196 rich text block quote 30 min
> fixed blockquote with rich text

- .stylelintrc.json
> Issue 2200 do not run stylelint on JS/TS files

- extension/chrome/dev/errors.htm
- extension/chrome/dev/export.htm
- extension/chrome/dev/storage.htm
- extension/chrome/elements/add_pubkey.htm
- extension/chrome/elements/passphrase.htm
- extension/chrome/elements/shared/attach.template.htm
- extension/chrome/emails/email_intro.template.htm
- extension/chrome/popups/default.htm
- extension/chrome/settings/fatal.htm
- extension/chrome/settings/index.htm
- extension/chrome/settings/initial.htm
- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/modules/compatibility.htm
- extension/chrome/settings/modules/contact_page.htm
- extension/chrome/settings/modules/decrypt.htm
- extension/chrome/settings/modules/keyserver.htm
- extension/chrome/settings/modules/security.htm
- extension/chrome/settings/setup.htm
- package.json
With the https://github.com/hex-ci/vscode-stylelint-plus extension and the `"stylelint.autoFixOnSave": true` setting there will never be a single issue again in inline styles.
> Fix stylelint issues in htm files

- extension/chrome/elements/compose.ts
- extension/js/common/composer/formatters/encrypted-mail-msg-formatter.ts
- extension/js/common/composer/interfaces/composer-app-functions.ts
> issue 2218 fixed password encrypted attachments

- extension/js/common/api/google.ts
> issue 2225 fix missing payload

- extension/chrome/settings/modules/account.ts
- extension/chrome/settings/modules/experimental.htm
- extension/chrome/settings/modules/experimental.ts
- extension/chrome/settings/modules/help.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/js/common/browser.ts
- extension/js/common/view.ts
> view framework

- extension/js/common/composer/composer-quote.ts
- extension/js/common/composer/composer-render.ts
- extension/js/common/extension.ts
Issue #2189,
Time Spent: 3h
I also fixed an issue when `TripleDots` button was shown on the reply box with a draft and the button was also rendered (but actually it shouldn't have been rendered), and when you click on it nothing happens.
I haven't found the issue related to this `Tripedots` button bug on Github (it might not be reported).
> [4h] Issue #2189, fixed bug when footer doubled

- extension/js/common/composer/composer-contacts.ts
- test/source/mock/strategies/send-message-strategy.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
> Issue 2235 flakey tests

- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/contacts.ts
> issue 2237 refactor BackupView, ContactsView

- .vscode/launch.json
- extension/chrome/elements/compose.htm
- extension/chrome/settings/inbox/inbox.htm
- test/source/browser/controllable.ts
- test/source/tests/tests/compose.ts
- test/source/tests/tests/gmail.ts
> Test toggle minimized state by clicking header

- extension/chrome/settings/modules/auth_denied.ts
> Issue #2231, refactored auth_denied.ts file

- extension/chrome/settings/modules/add_key.ts
Issue #2231,
Time Spent: 40m
I also found a bug:
When we call `BrowserMsg.send.reload(this.parentTabId, { advanced: true });`
It doesn't refresh a page immediately, it refreshed the page in about 4-5 sec after clicking. I tried to investigate it but the code has been written well. I don't know why it behaves this way yet. Need more investigation.
> Issue #2231, refactored add_key.ts file

- extension/chrome/settings/modules/compatibility.ts
> Issue #2231, refactored compatibility file

- extension/js/common/xss_safe_factory.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
- test/source/tests/tests/gmail.ts
> Fix the secure reply button for encrypted emails

- extension/chrome/settings/modules/contact_page.ts
> Issue #2231, refactored contact_page file

- extension/chrome/elements/pgp_block_modules/pgp_block_render_module.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/experimental.ts
- extension/chrome/settings/modules/help.ts
> issue #2253 use arrow function for handlers

- extension/css/settings.css
- extension/css/webmail.css
- extension/js/common/inject.ts
- extension/js/common/webmail.ts
- extension/js/common/xss_safe_factory.ts
- test/source/tests/page_recipe.ts
> issue #2252 fix encrypted session btn

- extension/chrome/settings/modules/debug_api.ts
> Issue #2231, refactored debug_api.ts file

- extension/chrome/settings/modules/my_key_user_ids.ts
> Issue #2231, refactored key_user_ids.ts file

- extension/chrome/settings/modules/my_key_update.ts
> Issue #2231, Refactored my_key_update file

- extension/chrome/elements/compose.ts
- extension/chrome/elements/reply_pubkey_mismatch.ts
- extension/js/background_page/migrations.ts
- extension/js/common/composer/composer-contacts.ts
- extension/js/common/composer/composer-draft.ts
- extension/js/common/composer/composer-errs.ts
- extension/js/common/composer/composer-input.ts
- extension/js/common/composer/composer-my-pubkey.ts
- extension/js/common/composer/composer-pwd-or-pubkey-container.ts
- extension/js/common/composer/composer-recipients.ts
- extension/js/common/composer/composer-render.ts
- extension/js/common/composer/composer-send-btn.ts
- extension/js/common/composer/composer-sender.ts
- extension/js/common/composer/composer-size.ts
- extension/js/common/composer/composer.ts
- extension/js/common/composer/interfaces/composer-app-functions.ts
- extension/js/common/platform/store.ts
> Issue #2256 auto attach

- extension/chrome/settings/modules/my_key.ts
> Issue #2231, refactored my_key.ts file

- extension/js/common/api/google.ts
- extension/js/common/settings.ts
> issue 2259 clearer attester submit error

- extension/chrome/settings/modules/test_passphrase.ts
> Issue #2231, refactored test_passphrase.ts file

- extension/chrome/elements/add_pubkey.ts
> Issue #2239, refactored add_pubkey file

- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/security.ts
- extension/css/settings.css
> Issue #2231, refactored security file

- extension/chrome/elements/compose.ts
> issue 2269 account disabled by admin policy handle

- extension/chrome/elements/backup.ts
> Issue #2239, Refactored backup file

- extension/js/common/inject.ts
> issue 2275 session button doubled up

- extension/chrome/elements/pgp_block_modules/pgp_block_pwd_encrypted_msg_module.ts
- extension/chrome/settings/inbox/inbox.htm
- extension/chrome/settings/inbox/inbox.ts
- extension/js/common/api/api.ts
- extension/js/common/api/backend.ts
- extension/js/common/api/email_provider_api.ts
- extension/js/common/api/google.ts
- extension/js/common/browser.ts
- extension/js/common/composer/composer-draft.ts
- extension/js/common/composer/composer-recipients.ts
- extension/js/common/extension.ts
- extension/js/common/settings.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
- test/source/tests/api.ts
> debug renew access token errs + surface to user

- extension/chrome/settings/index.ts
> issue 2282 SettingsView

- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue 1870 frames doubled

- extension/chrome/elements/passphrase.ts
- test/source/tests/tests/compose.ts
> issue 2286 fix pass phrase prompt layout

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/composer/composer-errs.ts
- extension/chrome/elements/composer/composer-quote.ts
- extension/chrome/elements/composer/composer-render.ts
- extension/chrome/elements/composer/composer-send-btn.ts
- extension/chrome/elements/composer/composer-sender.ts
- extension/chrome/elements/pgp_block_modules/pgp_block_decrypt_module.ts
- extension/chrome/elements/pgp_block_modules/pgp_block_pwd_encrypted_msg_module.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/popups/default.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/compatibility.ts
- extension/js/background_page/background_page.ts
- extension/js/background_page/bg_handlers.ts
- extension/js/common/api/google-auth.ts
- extension/js/common/api/google.ts
- extension/js/common/browser/env.ts
- extension/js/common/core/mime.ts
- extension/js/common/core/pgp.ts
- extension/js/common/platform/xss.ts
- package.json
> Issue 2294 ts upgrade

- extension/chrome/elements/compose.htm
- extension/chrome/elements/composer/composer-pwd-or-pubkey-container.ts
- extension/chrome/elements/composer/composer-send-btn.ts
- extension/chrome/elements/composer/formatters/composer-mail-formatter.ts
- test/source/browser/controllable.ts
- test/source/tests/tests/compose.ts
> Disable #send_btn when in wip state

- extension/chrome/elements/pgp_block_modules/pgp_block_pwd_encrypted_msg_module.ts
- extension/chrome/elements/pgp_block_modules/pgp_block_render_module.ts
> issue 2307 fix badly bound this

- extension/chrome/elements/composer/composer-my-pubkey.ts
- extension/js/common/platform/store.ts
> issue 2305 fix contact null check

- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue 2309 sometimes doesnt render pubkey

- extension/chrome/elements/composer/composer-send-btn.ts
> issue 2314 fix progress percentage

- extension/css/webmail.css
- extension/js/common/xss_safe_factory.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> Secure reply button taborder

- extension/chrome/dev/export.ts
- test/samples/mock-data.ts
- test/source/mock/data.ts
- test/source/tests/tests/compose.ts
Issue #2292,
Time Spent: 40m
I will make a PR with updated `flowcryptcompatibility` mock data to `flowcrypt-bin` repository. When you merge it please re-run tests.
Thanks!
> Issue #2292, Created a test

- extension/chrome/elements/compose.htm
- extension/chrome/settings/inbox/inbox.htm
- test/source/browser/test_urls.ts
- test/source/tests/page_recipe/compose-page-recipe.ts
- test/source/tests/page_recipe/inbox-page-recipe.ts
- test/source/tests/tests/compose.ts
> issue 2324 remove tests that use new message in settings footer

- extension/chrome/elements/composer/composer-quote.ts
- extension/chrome/elements/composer/composer-sender.ts
- extension/chrome/elements/composer/composer-storage.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/help.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-recover-key.ts
- extension/js/common/api/error/api-error.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue 2331 reportIfSignificant

- extension/chrome/settings/modules/backup.ts
> issue 2115 fixed manual setup ff

- extension/js/common/ui/att_ui.ts
> issue 2335 no over limit att error, only modal

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/compose.ts
- extension/chrome/elements/composer/composer-render.ts
- extension/chrome/elements/subscribe.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.htm
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/security.ts
- extension/js/common/settings.ts
- extension/js/common/xss_safe_factory.ts
- extension/js/content_scripts/webmail/setup_webmail_content_script.ts
- test/source/tests/page_recipe/settings-page-recipe.ts
> issue 2326 rm settings new message + rm deprecated urlparams

- extension/chrome/settings/modules/backup.ts
- extension/js/common/core/att.ts
> issue 2342 accept asc backups

- extension/chrome/settings/index.htm
- extension/chrome/settings/modules/experimental.htm
- extension/js/common/notifications.ts
- test/source/tests/tests/account.ts
- test/source/tests/tests/gmail.ts
- tooling/bundle-content-scripts.ts
> Issue 2344 ajaxerr not defined

- test/source/tests/tests/compose.ts
> issue 2346 manual copied key flaky

- flowcrypt-browser.code-workspace
Fix for https://github.com/FlowCrypt/flowcrypt-browser/pull/2347#issuecomment-564976102
> Add eslint.validate to workspace config

- extension/chrome/elements/subscribe.ts
- extension/chrome/settings/modules/account.ts
- extension/chrome/settings/modules/experimental.htm
- test/source/mock/backend/backend-data.ts
- test/source/mock/backend/backend-endpoints.ts
- test/source/test.ts
- test/source/tests/tests/settings.ts
- tooling/build-types.ts
> Issue 2340 mock test report err

- test/source/tests/tests/gmail.ts
> issue 2353 flaky live test

- extension/js/common/api/backend.ts
- extension/js/common/api/google-auth.ts
- extension/js/common/settings.ts
> issue 2355 stop looking at login subscription

- extension/js/common/platform/catch.ts
> issue 1025 worker stack

- extension/js/common/core/pgp-password.ts
- extension/js/common/core/pgp.ts
- extension/js/common/settings.ts
- extension/js/common/ui/key_import_ui.ts
> Issue #1438, refactored pgp password

- extension/chrome/elements/composer/composer-draft.ts
- extension/chrome/elements/composer/composer-input.ts
- extension/chrome/elements/composer/composer-render.ts
> issue #2370 composer input cleanup

- extension/js/common/core/mime.ts
- extension/js/common/core/pgp-armor.ts
- extension/js/common/core/pgp-key.ts
- extension/js/common/core/pgp-password.ts
- extension/js/common/core/pgp.ts
Issue #1438, refactored a part of `Pgp.internal`.
Another part I will refactor when I move `PgpMsg` class to another file.
> Issue 1438 refactor pgp internal

- flowcrypt-browser.code-workspace
Adresses https://github.com/FlowCrypt/flowcrypt-browser/pull/2366#issuecomment-565431655
> Remove editor.fontFamily

- extension/js/content_scripts/webmail/gmail_element_replacer.ts
> issue #2375 fix reply btn enter handler

- extension/js/common/core/pgp-armor.ts
- test/source/tests/tests/decrypt.ts
Issue #337 
Time Spent: 2h
Please merge new mock data first and the rerun tests.
Thanks
> Issue 337 pgp message contained inside signed

- test/source/browser/controllable.ts
- test/source/tests/tests/compose.ts
Issue #1730 
Time Spent: 1h
I added a new optional property to the `.waitAndClick` a method called `sleepWhenDone`.
It used for adding a delay after a click happened. I have added it because after clicking on maximize/minimize buttons there is an animation that takes some time to resize the compose window.
> Issue #1730, Created a test to max/min compose window

- extension/chrome/elements/composer/composer-recipients.ts
Issue #2048,
Time Spent: 1h 20m (30m dev, ~50 testing)
It was easier than I expected but I had to test it well so I spent almost one hour testing it.
I've tested it pretty well and didn't find any bugs.
> Issue #2048, check using attester and add to DB

- flowcrypt-browser.code-workspace
The HTML-only solution for an issue described in #2388
> disable autoformatting in HTML files

- extension/chrome/elements/composer/composer-input.ts
> Make sure that cursor is visible when typing

- extension/chrome/elements/composer/composer-size.ts
- extension/js/common/browser/browser-msg.ts
> issue 2382 fatal err on chrome.runtime

- extension/chrome/elements/composer/composer-recipients.ts
> issue 2383 invalid recipient

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/composer/composer-size.ts
> issue 2397 att download doubleclick

- extension/chrome/elements/attachment.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/my_key.ts
> issue 2407 ff download streamline

- build.sh
- package.json
> issue 2410 incremental builds

- extension/chrome/elements/composer/composer-send-btn-popover.ts
- extension/js/common/platform/catch.ts
close #2413 
20 min
allow rich text on ff
> issue 2413 allow richText ff

- extension/chrome/elements/attachment.htm
- extension/chrome/elements/attachment.ts
- extension/chrome/settings/inbox/inbox_modules/inbox_thread_module.ts
- extension/css/cryptup.css
- extension/js/common/xss_safe_factory.ts
closes #1964
closes #2415  
Time spent: 1h 30m
> Issue #1964, render plain attachments in encrypted inbox

- extension/chrome/elements/composer/composer-errs.ts
- extension/chrome/elements/composer/composer-quote.ts
- test/source/tests/tests/compose.ts
Issue #2395,
Time Spent: 1h 30m
> Issue 2395 fix issue when sending empty msg

- test/source/tests/page_recipe/compose-page-recipe.ts
- test/source/tests/tests/account.ts
close #2316 
Time Spent: 2h
The only thing that went wrong is I had to test it using Live mock, that's why I spent much more time on it.
> Made a test to check if percents is shown

- extension/css/cryptup.css
> Editor overflow

- test/source/browser/controllable.ts
- test/source/mock/all-apis-mock.ts
- test/source/mock/lib/api.ts
- test/source/test.ts
- test/source/tests/page_recipe/compose-page-recipe.ts
- test/source/tests/tests/account.ts
- test/source/tests/tests/compose.ts
- test/source/tests/tests/settings.ts
> issue 2432 test sending % using mock

- extension/chrome/elements/composer/composer-sender.ts
- test/source/tests/tests/compose.ts
close #2427,
Time Spent: 1h
I couldn't test it because it happens only when you changed your footer in settings and then open a reply box. But I corrected the test so now it will check if there is no footer before you click on `triple dot` button
> Issue 2427 issue when footer doubled

- extension/chrome/elements/composer/composer-draft.ts
- extension/chrome/elements/composer/formatters/encrypted-mail-msg-formatter.ts
- extension/chrome/elements/composer/formatters/signed-msg-mail-formatter.ts
- extension/js/common/api/email_provider/email_provider_api.ts
- extension/js/common/api/email_provider/gmail/gmail.ts
- extension/js/common/core/att.ts
- extension/js/common/core/mime.ts
- package.json
> Issue 2425 fix pgp mime

- extension/chrome/elements/compose.htm
- extension/chrome/elements/compose.ts
- extension/chrome/elements/composer/composer-draft.ts
- extension/chrome/elements/composer/composer-errs.ts
- extension/chrome/elements/composer/composer-footer.ts
- extension/chrome/elements/composer/composer-input.ts
- extension/chrome/elements/composer/composer-quote.ts
- extension/chrome/elements/composer/composer-recipients.ts
- extension/chrome/elements/composer/composer-render.ts
- extension/chrome/elements/composer/composer-send-btn.ts
- extension/chrome/elements/composer/composer-sender.ts
- extension/chrome/elements/composer/composer-size.ts
- extension/chrome/elements/composer/composer-storage.ts
- extension/chrome/elements/composer/composer.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/css/cryptup.css
- extension/js/common/core/common.ts
- extension/js/common/lang.ts
- extension/js/common/platform/store.ts
- extension/js/common/settings.ts
- extension/js/common/ui/att_ui.ts
- test/source/browser/controllable.ts
- test/source/mock.ts
- test/source/tests/tests/compose.ts
> Issue 2443 invalid to hdr + footer refactor + sendAs refactor

- extension/css/cryptup.css
> Issue #2446, Corrected 'triple-dot' button

- conf/tslint.test.yaml
- package.json
- test/source/async-stack.ts
- test/source/browser/browser_handle.ts
- test/source/browser/browser_pool.ts
- test/source/browser/controllable.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/mock/lib/oauth.ts
- test/source/platform/store.ts
- test/source/tests/api.ts
Related to https://github.com/FlowCrypt/flowcrypt-browser/issues/2470#issuecomment-571565618
This PR is the result of 
```sh
tslint --fix --project ./conf/tsconfig.test.json -c ./conf/tslint.yaml
```
> Add tslint config for test folder, fix autofixable tslint issues in test folder

- extension/chrome/settings/setup.ts
- extension/js/common/rules.ts
> issue 2473 remember pp by org rule

- extension/js/common/core/mime.ts
- test/source/tests/tests/account.ts
- test/source/tests/tests/flaky.ts
> renamed Mime.isPlainInlineImg to Mime.isPlainImgAtt

- extension/chrome/elements/composer/formatters/encrypted-mail-msg-formatter.ts
> issue 2484 fix pwd reply subject

- extension/chrome/settings/modules/compatibility.ts
- extension/js/common/core/types/openpgp.d.ts
Closes #2487
`Message.prototype.sign()` is returning a Promise:
> Await the result of Message.prototype.sign()

- extension/chrome/settings/modules/add_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/setup/setup-import-key.ts
- extension/js/common/browser/ui.ts
- extension/js/common/ui/key-import-ui.ts
Closes #1578 
@tomholub two questions
1. From the issue: "should only apply to the types of errors that seem like a compatibility issue". I added a footer to all modals. Please let me know which modals are not for "compatibility issues", I'll remove the footer from them.
2. Could you confirm that an automated test is needed for this functionality and if yes, then which steps would you like to be included in that test? 
Thanks!
> Test your private key compatibility

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
Closes #2041
@tomholub do we need test for this? If so, then it should be live Gmail test, right?
> Close original draft window once "open draft" is clicked

- extension/manifest.json
> lower permission

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
> Ensure msgBody has dummy parent after being replaced

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
> Make .action_show_prev_msg accessible with keyboard

- extension/manifest.json
> Add API domains to permissions list

- extension/js/common/core/att.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
> issue #2513 improved gpg4win compat in gmail

- extension/js/common/platform/store.ts
> issue #2519 naked key check

- extension/chrome/elements/composer/composer-render.ts
- extension/chrome/elements/composer/composer-storage.ts
- extension/js/background_page/bg-handlers.ts
- extension/js/common/core/msg-block-parser.ts
- extension/js/common/core/pgp-key.ts
- extension/js/common/ui/key-import-ui.ts
> Issue 2369 pgpkey

- extension/js/common/api/api.ts
- extension/js/common/api/backend.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- test/source/mock/lib/api.ts
- test/source/tests/browser-recipe.ts
- test/source/tests/tests/compose.ts
- test/source/tests/tests/decrypt.ts
- test/source/tests/tests/gmail.ts
- test/source/util/index.ts
- test/tests.json
> issue 2405 fix download percentage

- test/source/tests/tests/compose.ts
> Add 'Ctrl+Enter sends message' test

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- test/source/mock/backend/backend-endpoints.ts
> issue 861 always include reply token

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose-modules/formatters/base-mail-formatter.ts
- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/chrome/elements/compose-modules/formatters/general-mail-formatter.ts
- extension/chrome/elements/compose-modules/formatters/plain-mail-msg-formatter.ts
- extension/chrome/elements/compose-modules/formatters/signed-msg-mail-formatter.ts
> issue 2534 draft no att

- extension/chrome/elements/compose-modules/compose-atts-module.ts
- extension/js/common/ui/att-ui.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/tests/compose.ts
> Issue 2537 prevent oversize atts

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/platform/store.ts
- test/samples/mock-data.ts
- test/source/tests/tests/compose.ts
> Issue 2234 search by name fix

- extension/js/background_page/migrations.ts
- extension/js/common/platform/store.ts
> issue 2486 rm old global store

- extension/js/common/platform/xss.ts
- extension/js/common/view.ts
> issue 2544 check DOMPurify.isSupported

- extension/chrome/settings/index.htm
- extension/chrome/settings/index.ts
> issue 2548 fix unknown page

- extension/chrome/elements/subscribe.ts
> issue 2550 debug subscribe

- extension/chrome/dev/ci_pgp_host_page.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-pwd-encrypted-msg-module.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/js/background_page/background_page.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/content_scripts/webmail/webmail.ts
> Move pgpHashChallengeAnswer from background script

- extension/js/common/api/error/api-error.ts
> Issue 2555 eli5 storage errs

- test/source/browser/controllable.ts
- test/source/tests/tests/compose.ts
> Add test for opening & changing composer send btn popover using keyboard

- test/source/tests/tests/compose.ts
Part of #2051 
Use `?w=1` for review: https://github.com/FlowCrypt/flowcrypt-browser/pull/2563/files?w=1
> Add test for submitting/canceling the 'enter pass phrase' form with kbd

- extension/js/common/ui/att-ui.ts
- test/source/tests/tests/compose.ts
> Add test for attaching files with kbd

- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose.ts
- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-create-key.ts
- extension/chrome/settings/setup/setup-import-key.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/js/common/api/attester.ts
- extension/js/common/api/keyserver.ts
- extension/js/common/rules.ts
- extension/js/common/settings.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- extension/js/content_scripts/webmail/webmail.ts
- test/source/mock.ts
- test/source/mock/backend/backend-data.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/tests/setup.ts
> Issue 2516 no attester submit

- extension/chrome/settings/index.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
> issue 2565 compare lowercased emails

- extension/js/common/core/mime.ts
> issue 2578 jira compat

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
> issue 2580 better replacing of signed content

- extension/js/common/core/pgp-msg.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
> issue 2587 fix ff blob err

- extension/js/common/browser/ui.ts
> Use scrollbarPadding: false for Swal modals

- test/source/tests/tests/gmail.ts
> issue 2594 flaky gmail test

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-quote-module.ts
- extension/js/common/core/common.ts
- extension/js/common/core/msg-block-parser.ts
- extension/js/common/platform/xss.ts
- test/source/platform/xss.ts
- test/source/tests/tests/compose.ts
> Add RTL support for plain text messages

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- package.json
- test/source/browser/controllable.ts
- test/source/tests/tests/compose.ts
> Add RTL support for subject field

- extension/chrome/elements/compose-modules/compose-render-module.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
- test/source/tests/tests/compose.ts
> Support RTL for the Subject input field of a draft

- extension/chrome/elements/pgp_block.htm
- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/css/cryptup.css
> Make signature floating, add RTL support

- extension/chrome/elements/compose-modules/compose-quote-module.ts
Closes #2600 
@tomholub do we need a test for this change?
> Support RTL in quoted text

- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose.ts
- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/js/common/api/attester.ts
- extension/js/common/api/key-manager.ts
- extension/js/common/api/keyserver.ts
- extension/js/common/api/pub-lookup.ts
- extension/js/common/api/sks.ts
- extension/js/common/platform/store/contact-store.ts
- extension/js/common/rules.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
> issue 2607 key manager pubkeys

- test/source/tests/tests/compose.ts
> issue 2610 key manager pubkey test

- extension/js/common/api/error/api-error-types.ts
- extension/js/common/core/common.ts
> issue 2621 ekm err msg

- extension/css/cryptup.css
> Add max-width: 300px to #pgp_signature

- .semaphore/semaphore.yml
- extension/chrome/elements/backup.htm
- extension/chrome/elements/backup.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose-modules/formatters/signed-msg-mail-formatter.ts
- extension/chrome/elements/passphrase.ts
- extension/chrome/elements/pgp_pubkey.htm
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/compatibility.ts
- extension/chrome/settings/modules/contacts.htm
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.htm
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/modules/my_key_user_ids.htm
- extension/chrome/settings/modules/my_key_user_ids.ts
- extension/css/settings.css
- extension/js/common/core/pgp-key.ts
- test/source/tests/page-recipe/settings-page-recipe.ts
- test/source/tests/tests/gmail.ts
- test/source/tests/tests/setup.ts
> issue 2620 prefer ui fingerprints

- extension/chrome/elements/compose-modules/compose-atts-module.ts
- extension/chrome/elements/compose.ts
- extension/chrome/elements/pgp_block.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/modules/security.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-create-key.ts
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/js/common/api/attester.ts
- extension/js/common/api/backend.ts
- extension/js/common/api/google-auth.ts
- extension/js/common/api/pub-lookup.ts
- extension/js/common/org-rules.ts
- extension/js/common/platform/store/abstract-store.ts
- extension/js/common/platform/store/acct-store.ts
- extension/js/common/settings.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- extension/js/content_scripts/webmail/webmail.ts
> issue 2628 rename Rules to OrgRules

- extension/lib/featherlight/featherlight.js
- extension/lib/fine-uploader.js
> issue 2633 lib unsafe eval

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/js/common/browser/browser.ts
- extension/js/common/platform/xss.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
> issue 2631 refactored html assignments

- extension/chrome/settings/index.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/js/common/api/pub-lookup.ts
- extension/js/common/org-rules.ts
- test/source/mock.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/tests/setup.ts
- test/source/util/index.ts
> issue 2640 skip ekm pub + test

- extension/js/common/platform/xss.ts
> issue 2648 mitigate css url leaks

- extension/manifest.json
> issue 2647 csp frame-ancestors

- extension/chrome/elements/pgp_block.ts
- extension/js/common/api/api.ts
- extension/js/common/view.ts
- test/source/test.ts
- test/source/tests/tests/decrypt.ts
> issue 2646 forbid api path traversal + test

- test/source/tests/page-recipe/setup-page-recipe.ts
> issue 2654 retry test errs

- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-create-key.ts
- extension/js/common/api/attester.ts
- extension/js/common/core/msg-block-parser.ts
- extension/js/common/org-rules.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/lib/api.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/tests/flaky.ts
- test/source/tests/tests/setup.ts
> Issue 2639 attester submit with idtoken

- extension/js/common/platform/xss.ts
> issue 2671 xss comments

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/tests/gmail.ts
Closes #1735 
@tomholub is live Gmail test needed for this PR?
> Plain reply to encrypted message

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/chrome/settings/modules/compatibility.ts
- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/setup/setup-create-key.ts
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/js/common/core/pgp-key.ts
- extension/js/common/org-rules.ts
- extension/js/common/platform/store/contact-store.ts
- test/source/mock.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/tests/setup.ts
- test/source/util/index.ts
> Issue 2675 key expiration org rule

- extension/css/webmail.css
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/tests/gmail.ts
> Show error notification about switching from plain to encrypted

- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-create-key.ts
- extension/chrome/settings/setup/setup-import-key.ts
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/chrome/settings/setup/setup-recover-key.ts
- extension/chrome/settings/setup/setup-render.ts
- test/source/browser/controllable.ts
- test/source/mock.ts
- test/source/mock/backend/backend-data.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/tests/flaky.ts
- test/source/tests/tests/setup.ts
- test/source/util/index.ts
> issue 2679 org rules can create prv but backup forbidden

- extension/js/common/api/api.ts
- extension/js/common/api/error/api-error.ts
- extension/js/common/api/pub-lookup.ts
- extension/js/common/api/wkd.ts
- extension/js/common/core/pgp-key.ts
- extension/js/common/core/types/openpgp.d.ts
- extension/js/common/org-rules.ts
- test/source/tests/tests/compose.ts
> issue 2681 direct wkd lookup

- extension/chrome/settings/index.ts
- extension/chrome/settings/setup.ts
- extension/css/cryptup.css
- extension/css/mobile-menu-styling.css
- extension/css/sweetalert2.css
- extension/js/common/assert.ts
- extension/js/common/browser/ui.ts
- extension/js/common/settings.ts
- extension/lib/sweetalert2.js
- extension/types/sweetalert2.d.ts
- package.json
The first part of #2632
In this PR the most of featherlight usage cases are replaced with SweetAlert2.
Also, bumped SweetAlert2 to latest version.
> Replace featherlight with sweetalert2 in settings

- extension/chrome/elements/backup.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/passphrase.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/add_key.ts
- extension/chrome/settings/modules/backup-manual-module.ts
- extension/chrome/settings/modules/change_passphrase.ts
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/modules/my_key_user_ids.ts
- extension/chrome/settings/modules/security.ts
- extension/chrome/settings/setup.ts
- extension/js/common/core/pgp-key.ts
- extension/js/common/inject.ts
- extension/js/common/platform/store/key-store.ts
- extension/js/common/platform/store/passphrase-store.ts
- extension/js/common/settings.ts
> issue-2627-prefer-fingerprint

- extension/js/common/platform/store/contact-store.ts
> issue 2694 contact validemail refactor

- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/js/common/api/error/api-error-types.ts
> issue 2697 no ajaxerr static props

- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/experimental.htm
- extension/chrome/settings/modules/experimental.ts
- extension/js/common/api/api.ts
- extension/js/common/api/backend.ts
- extension/js/common/api/google-auth.ts
- test/source/mock/backend/backend-endpoints.ts
> issue 2700 deprecate account check

- extension/chrome/settings/index.htm
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/auth_denied.htm
- extension/chrome/settings/modules/change_passphrase.htm
- extension/chrome/settings/setup.htm
- extension/css/cryptup.css
- extension/js/common/browser/ui.ts
- extension/lib/sweetalert2.js
- package.json
Towards #2632 
Also, updated SweetAlert2 to latest version in which we made the security fix to make it a bit more robust in terms of security, see https://github.com/sweetalert2/sweetalert2/pull/1930/files for details.
> Replace data-featherlight with SweetAlert2

- extension/js/common/api/api.ts
- test/source/tests/tests/compose.ts
> issue 2706 wkd timeout

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/tests/gmail.ts
> Fix drafts for plain replies

- test/source/tests/tests/gmail.ts
The master branch is failing now because of my last PR: https://semaphoreci.com/flowcrypt/flowcrypt-browser/branches/master/builds/1633
This should eliminate the flakiness.
> Fix 'plain reply to encrypted message' test

- extension/chrome/elements/attachment.ts
> Fix hovering attachment which is downloading

- extension/js/common/browser/ui.ts
> Make backdrop for Ui.modal.iframe() darker

- extension/manifest.json
Reverts FlowCrypt/flowcrypt-browser#2751
> Revert "added insecure requests upgrade directive to CSP"

- extension/css/sweetalert2.css
- extension/js/common/browser/ui.ts
- extension/lib/sweetalert2.js
- package.json
> Bump sweetalert2 to v9.15.2

- extension/chrome/settings/modules/experimental.ts
> Prevent default action for link in Enperimental features page

- extension/js/common/platform/xss.ts
> issue 2771 fix key rm, keep fingerprint html attr

- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
> Prevent attempts to send already sent messages

- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose.htm
- extension/chrome/elements/compose.ts
- test/source/tests/tests/compose.ts
> Send email by ctrl+enter only when focus is in subject or compose

- extension/chrome/elements/compose-modules/compose-render-module.ts
> Do not show gray border for unencryped unsinged messages

- extension/chrome/elements/attachment.htm
- extension/chrome/elements/attachment.ts
- extension/css/cryptup.css
- extension/js/common/browser/browser.ts
> Add ability to download attachment with keyboard

- extension/js/common/platform/store/contact-store.ts
> issue 2824 better prv update check

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose-modules/compose-size-module.ts
- extension/chrome/elements/compose.ts
- extension/css/cryptup.css
> Render rich-text replies with attachments

- extension/chrome/settings/modules/add_key.ts
- extension/chrome/settings/setup/setup-import-key.ts
- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
> issue 2825 unsupported key type unknown

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose.htm
- extension/js/common/xss-safe-factory.ts
- test/source/tests/tests/compose.ts
> fix attachment preview in rendered replies

- extension/js/common/core/crypto/pgp/openpgpjs-custom.ts
user was concerned that they didn't want their customers to easily see they use Gmail
> remove "Gmail" from version string

- test/source/tests/tests/account.ts
> issue 2835 temporarily disable test

- extension/chrome/settings/modules/contacts.ts
- extension/js/common/platform/store/contact-store.ts
> issue 2811 speed up contacts page loading

- extension/lib/openpgp.js
- extension/lib/openpgp.worker.js
> issue 2836 update openpgp.js to v4.10.6

- test/source/tests/page-recipe/oauth-page-recipe.ts
> issue 2841 fix oauth live tests google

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-size-module.ts
- extension/chrome/elements/compose.ts
> fix caclulating attachments height in setInputTextHeightManuallyIfNeeded()

- test/source/tests/page-recipe/oauth-page-recipe.ts
> issue 2851 fix live tests login

- extension/css/browser-popup.css
Fixes #2853 
@tomholub this is the kind of issues I'm able to catch having Windows as my primary OS. Open Sans isn't the preinstalled font in Windows.
The actual fix is in the 2nd commit, the 1st one is made by Stylelint.
> Issue 2853 default popup looks

- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/core/crypto/pgp/pgp-msg.ts
- test/source/mock/attester/attester-endpoints.ts
- test/source/tests/tests/decrypt.ts
> Issue 2857 sig verification errs

- extension/chrome/settings/modules/contacts.htm
- extension/chrome/settings/modules/contacts.ts
- extension/css/cryptup.css
- extension/js/common/platform/store/contact-store.ts
> issue 2858 search contacts by email

- extension/js/common/api/error/api-error-types.ts
- test/source/mock.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/tests/setup.ts
- test/source/util/index.ts
> issue 2769 redact sensitive info

- .semaphore/semaphore.yml
- test/source/test.ts
> issue 2895 increase mock test parallelism

- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
> issue 2894 refactor wrap unwrap

- extension/css/settings.css
- extension/js/common/api/backend.ts
> issue 2898 use rss feed for blog entries

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
> issue 2905 fix err removing recipients

- build.sh
- package.json
> Use @flowcrypt/fine-uploader

- build.sh
- extension/chrome/elements/pgp_block.htm
- extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts
- extension/js/common/core/common.ts
- package.json
- test/source/tests/tests/decrypt.ts
- tsconfig.json
> Use filesize.js for formatting size of attachments

- extension/css/settings.css
> Make the focused state of the 'Encrypted Contact Page' button visible

- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- test/source/tests/tests/setup.ts
Fixes #2547.
PR submitted for an effort to close my assigned long standing issues :)
I'll get back to you with a proposal to replace the XSS sanitize render with something safe by design but I need a little bit of time to prepare proof-of-concept.
For the private keys that are not really private maybe it would also be good to move them to some separate not-secret file...
> Display all e-mails directly on my_key screen

- extension/chrome/settings/index.htm
- extension/chrome/settings/index.ts
- extension/chrome/settings/setup.htm
- extension/css/settings.css
- extension/js/common/settings.ts
> Make the account menu accessible with kbd

- extension/css/cryptup.css
> Adjust SweetAlert2 for short docs

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/js/common/browser/browser-msg.ts
- test/source/mock/attester/attester-endpoints.ts
- test/source/mock/google/google-data.ts
- test/source/tests/tests/compose.ts
- test/source/tests/tests/setup.ts
> Update recepients in compose.htm after updating key in pgp_block.htm

- extension/js/common/platform/xss.ts
- extension/types/purify.d.ts
- package.json
Manually tested with Chrome, didn't have any problems.
Resolves https://github.com/FlowCrypt/flowcrypt-browser/issues/2955
> Update DOMPurify to v2.1.0 (obsolesce SAFE_FOR_JQUERY)

- extension/chrome/elements/compose-modules/compose-quote-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- test/source/browser/controllable.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
- test/source/tests/tests/compose.ts
> Focus #input_to when forwarding

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/attachment_preview.ts
- extension/css/cryptup.css
> [Attachment preview] Re-use error handling from attachment.ts

- extension/js/common/api/key-manager.ts
- extension/js/common/api/sks.ts
> issue 2740 normalize custom_keyserver_url trailing slash

- extension/chrome/settings/index.ts
- test/source/tests/tests/settings.ts
> Add test for removing a key

- test/source/tests/browser-unit-tests/unit-WellKnownHostMeta.js
- test/source/tests/tooling/api.ts
- test/source/tests/unit-browser.ts
>  issue 3019  add a way to select .only some unit tests

- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/css/cryptup.css
> [Settings/setup] Make the 'go back' button accessible with keyboard

- extension/js/common/ui/key-import-ui.ts
> Update key-import-ui.ts - typo

- extension/css/settings.css
- extension/css/webmail.css
- extension/js/common/inject.ts
- extension/js/common/xss-safe-factory.ts
> Make the 'End Pass Phrase Session' button position: fixed in gmail

- extension/css/webmail.css
- extension/js/common/inject.ts
> issue 3025 secure compose button doubled fix

- extension/chrome/elements/compose.htm
- test/source/tests/tooling/api.ts
> Change the reply box label from 'Encrypted' to 'Secure'

- .gitignore
- .npmrc
- LICENSE
- package-lock.json
> issue 3005 added package-lock

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
> issue 3048 dont report network err

- extension/css/cryptup.css
> Fix .attachment-preview-txt styles

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/attachment_preview.ts
- extension/css/cryptup.css
- extension/css/webmail.css
- extension/js/common/inject.ts
- extension/js/common/xss-safe-factory.ts
- test/source/tests/settings.ts
> Support pass phrase dialog when previewing attachments

- extension/chrome/settings/setup.ts
> send attest/test/welcome only to encryption-enabled keys

- extension/chrome/settings/inbox/inbox.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
- test/source/tests/settings.ts
> Fix closing the passphrase dialog by backdrop click

- extension/chrome/dev/ci_unit_test.ts
- extension/js/common/api/key-server/sks.ts
- test/source/mock/all-apis-mock.ts
- test/source/mock/sks/sks-endpoints.ts
- test/source/mock/wkd/wkd-endpoints.ts
- test/source/tests/browser-unit-tests/unit-Sks.js
> issue 3066 sks trailing slash fix

- extension/chrome/elements/compose-modules/compose-render-module.ts
- test/source/browser/controllable.ts
- test/source/tests/compose.ts
> Signed only attachments can be viewed after send

- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- extension/js/content_scripts/webmail/webmail.ts
> Remove read permission checks.

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/chrome/elements/compose-modules/compose-quote-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose-modules/compose-sender-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-error-module.ts
- extension/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.ts
- extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/add_key.ts
- extension/chrome/settings/modules/backup-automatic-module.ts
- extension/chrome/settings/modules/backup-manual-module.ts
- extension/chrome/settings/modules/backup-status-module.ts
- extension/css/settings.css
- extension/js/common/api/shared/api-error.ts
- extension/js/common/browser/ui.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
> issue 2701 refactor auth errors

- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/tests/compose.ts
> added test for U+10000 code points

- test/source/browser/controllable.ts
- test/source/mock/all-apis-mock.ts
- test/source/mock/lib/api.ts
- test/source/tests/decrypt.ts
- test/source/tests/flaky.ts
- test/source/tests/tooling/browser-recipe.ts
> issue 3097 fix testing progress percentage

- extension/chrome/elements/compose-modules/compose-size-module.ts
- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
- extension/img/svgs/exit-full-screen.svg
- extension/img/svgs/minimize.svg
- test/source/tests/compose.ts
Fixes #3038
Also made small fixes for the "Exit full screen" button to have the according title.
> Increase the clickable area of the buttons in #header_title

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/browser/controllable.ts
- test/source/tests/gmail.ts
> carefully wrap DOM element to fix #3076

- test/source/tests/setup.ts
> [Settings/setup] Ensure banners are not shown when not expected

- test/source/tests/compose.ts
Closes #3051 
This should be it, I re-ran tests 10 times, all 10 went perfectly without retries.
> Another attempt to fix the waitForFileChooser flakiness

- extension/chrome/settings/setup.ts
- test/source/tests/setup.ts
Closes #2661 
Puppeteer indeed works as expected with offline mode and localhost.
> Re-enable offline setup test

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose.htm
- test/source/tests/compose.ts
> Fix the recipients order

- extension/chrome/elements/compose-modules/compose-err-module.ts
Currently the doc doesn't exist, I'll make a PR for it over there in a moment
> Add troubleshooting info to network error message

- extension/js/common/core/mime.ts
- extension/js/common/core/msg-block.ts
- extension/js/common/xss-safe-factory.ts
- test/source/mock/attester/attester-endpoints.ts
- test/source/tests/decrypt.ts
> plain text detached signature fix

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/setup.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/compose.ts
> Fix ordering items in #contacts dropdown

- extension/js/common/api/account-servers/enterprise-server.ts
- extension/js/common/platform/catch.ts
close #3160
we won't yet report errors to fes, here just doing prepwork
> issue 3160 fes refactor prepwork

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/browser/controllable.ts
- test/source/tests/compose.ts
> Add ability to remove focused recipients with Del and Backspace keys

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
> Allow duplicates in #input_to when using contacts search

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
> Do not show contacts search results if input value has changed meanwhile

- extension/chrome/settings/modules/compatibility.ts
- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/tests/unit-node.ts
> Refactored KeyUtil.diagnose for correct usage of passphrase

- test/source/browser/controllable.ts
> Replace deprecated <font> tag.

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
> Remove gmail's autoreplies

- extension/js/common/browser/browser.ts
> Focus tab after opening it with window.open()

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
Hopefully, fixes #3180
This PR is a blind shot since I wasn't able to reproduce the issue. 
There was kind of a TODO task in the method description which I implemented.
Here's what has been done:
1. `attsContainerInner` is now evaluated only once. After detecting a new atts container (which is still happening every 1s), it's being processed and marked with the `.evaluated` class to prevent from next evaluations
2. Children of `attsContainerInner`, are being evaluated as before
3. In addition to 2. there's now the mutation observer which will monitor for new attachments added to `attsContainerInner`'s DOM. Attachments detected with the mutation observer will be processed the same way as in 2.
The `processNewPgpAtts` method was extracted from the `replaceAtts` method without any changes.
> Evaluate atts container only once, detect new atts in it with mutation observer

- extension/js/common/org-rules.ts
> issue 3107 fix curve25519 comment

- extension/js/common/api/email-provider/gmail/google-auth.ts
- extension/js/common/settings.ts
> Fixed retrying consent screen error on cancelling

- extension/js/common/platform/store/contact-store.ts
> Store Contact.pubkey as string

- extension/js/common/settings.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/setup.ts
> issue 3173 change EKM put 400 to 405

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/settings/modules/contacts.ts
- extension/js/common/api/email-provider/email-provider-api.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/api/shared/api.ts
- extension/js/common/platform/store/contact-store.ts
> ContactStore.search() now returns Promise<ContactPreview[]> #3282

- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/css/cryptup.css
- test/source/tests/decrypt.ts
- test/source/tests/gmail.ts
Fixes #3291 
Fixes #3290 
Closes #3279 (proves that it was breaking reply drafts, the test from this PR is failing there)
> Focus #input_text for reply drafts

- extension/chrome/settings/modules/experimental.htm
- test/source/tests/gmail.ts
- test/source/tests/settings.ts
> Added reauth tests on uuid change

- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/setup.ts
- test/source/util/index.ts
> do not attempt to upload to attester when orgrules forbid it

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
This PR saves rich text drafts as inline PGP messages to be able to pick it up later in gmail
I tested it in Gmail to pick it up and send (as RFC3156) -- it works good.
Should I do a (separate) test to 
1. make sure a draft is saved as inline message.
2. an inline draft like this is sent as `multipart/encrypted` (RFC3156)
?
close #3082
> Save rich text drafts as inline PGP messages

- extension/chrome/dev/ci_pgp_host_page.ts
- extension/chrome/dev/ci_unit_test.htm
- extension/chrome/settings/index.ts
- extension/chrome/settings/initial.ts
- extension/js/common/view.ts
- test/source/browser/browser-handle.ts
- test/source/browser/browser-pool.ts
- test/source/browser/controllable.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
- test/source/tests/unit-browser.ts
This PR attempts to wait until page is loaded before testing it - to increase reliability even as we speed up test execution.
issue #3088
> issue 3088 speed up mock test slowMo

- extension/css/cryptup.css
> tiny styles fix for edge

- extension/lib/emailjs/emailjs-mime-codec.js
- test/source/tests/browser-unit-tests/unit-Mime.js
> Fixes corrupted filename error

- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/js/common/api/key-server/key-manager.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/setup.ts
This PR no longer sends fingerprint to PUT /keys/private on EKM since it's no longer required.
close #3363
> Issue 3363 ekm no fp

- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
This PR makes sure that the reply box is positioned properly in the viewport on initialisation
close #3367
> Scroll to the top of reply box if it's higher than the viewport

- test/source/tests/compose.ts
> Typo: errorneously -> erroneously

- extension/css/cryptup.css
- extension/js/common/settings.ts
This PR adds styles for modals in short iframes so they'll be painless to use (no scrolling) for users.
close #3369
> Adjust modal styles for short iframes

- extension/chrome/settings/index.ts
- extension/js/common/settings.ts
This PR adds the oauth login functionality to the "Auth Needed" link in settings' status container.
close #3390
> Make the 'Auth Needed' link work

- extension/chrome/elements/compose.ts
- extension/chrome/settings/setup.ts
- extension/js/common/org-rules.ts
- test/source/mock/backend/backend-data.ts
- test/source/tests/compose.ts
- test/source/tests/setup.ts
This PR adds HIDE_ARMOR_META to OrgRules
close #2035
> Added HIDE_ARMOR_META to OrgRules #2035

- .semaphore/semaphore.yml
- test/source/mock/backend/backend-endpoints.ts
- test/source/mock/fes/fes-endpoints.ts
- test/source/mock/lib/api.ts
- test/source/tests/gmail.ts
- test/source/tests/page-recipe/gmail-page-recipe.ts
This PR attempts to debug tests to reduce flakiness.
close #3428
close #3467
> issue 3428 improve tests

- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/js/common/xss-safe-factory.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/browser/controllable.ts
- test/source/tests/compose.ts
- test/source/tests/gmail.ts
fixes #3519 
fixes #3522
This PR also updates a test of s/mime key that expired, to pass tests again.
> fix s/mime test + iframe heights + doubled iframes

- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.ts
- extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts
- extension/js/common/api/email-provider/gmail/gmail-parser.ts
This PR updates types retuned by Gmail to avoid NPE
close #3510
> issue 3510 cannot read property find of undefined

- extension/manifest.json
I still need to test this more thoroughly and make sure I'm not breaking anything, so not ready to be merged!
Close https://github.com/FlowCrypt/flowcrypt-security/issues/81
> Add frame-src and worker-src CSP directives

- extension/chrome/settings/setup/setup-render.ts
- extension/js/common/api/key-server/attester.ts
- extension/js/common/api/key-server/sks.ts
- extension/js/common/api/key-server/wkd.ts
- extension/js/common/api/pub-lookup.ts
- test/source/tests/browser-unit-tests/unit-Sks.js
- test/source/tests/browser-unit-tests/unit-Wkd.js
This PR drops `pgpClient` property from `PubkeySearchResult`
close #3562
> dropped pgpClient from PubkeySearchResult

- test/source/tests/settings.ts
- test/source/tests/unit-node.ts
This PR replaced expired key with key expiring in year 2121
close #3601
issue #3610 
> Replaced expired key #3601

- extension/chrome/dev/ci_unit_test.ts
- extension/chrome/elements/compose-modules/compose-size-module.ts
- extension/chrome/popups/default.ts
- extension/js/common/platform/catch.ts
- test/source/test.ts
- test/source/tests/browser-unit-tests/unit-Catch.js
- test/source/tests/browser-unit-tests/unit-ContactStore.js
- test/source/tests/settings.ts
- test/source/tests/unit-browser.ts
This PR ensures we only submit errors to flowcrypt.com backend on consumer flavor.
close #3617 
> Issue 3617 dont report errors on enterprise

- extension/chrome/settings/modules/contacts.ts
- extension/css/cryptup.css
This PR fixes small html/css issues described in 
issue #3632
> [Settings / Contacts] Small fixes

- extension/img/svgs/revoked.svg
> Add svg icon for revoked keys

- .github/workflows/check-for-emails.yml
This version allows exemptions for addresses we don't care to be alerted about, like anything ending in test or flowcrypt.com.
> Update and rename main.yml to check-for-emails.yml

- extension/js/common/platform/store/contact-store.ts
- test/source/tests/browser-unit-tests/unit-ContactStore.js
This PR fixes `ContactStore.extractPubkeys()`
close #3659
> Fixed extractPubkeys

- extension/chrome/elements/compose-modules/compose-pwd-or-pubkey-container-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose-modules/compose-types.ts
- extension/chrome/elements/compose.htm
- extension/chrome/elements/compose.ts
- extension/css/cryptup.css
- extension/js/common/core/crypto/key.ts
- extension/js/common/platform/store/contact-store.ts
- test/source/platform/store/contact-store.ts
- test/source/tests/compose.ts
This PR displays revoked status of `Contact`
close #3636
> Display revoked status of contact

- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/chrome/settings/setup/setup-render.ts
This PR refactors EKM integration code used during setup, to be easier to follow and understand.
issue #3596
> issue 3596 refactored ekm integration code

- test/source/tests/page-recipe/oauth-page-recipe.ts
This PR takes into consideration new Gmail selectors of login form while keeping the old ones for the backward compatibility.
close #3678
> Update selectors for gmail login form

- extension/js/common/inject.ts
- test/source/browser/test-urls.ts
- test/source/tests/gmail.ts
- test/source/tests/tooling/browser-recipe.ts
This PR prevents injecting the Secure Compose button in Google Chat (https://mail.google.com/chat/u/0)
close #3746 
> Do not inject compose button in Google Chat

- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/setup.ts
This PR respects NO_PRV_CREATE in EKM autoimport
close #3564
> disable key auto-generation if NO_PRV_CREATE OrgRule is set

- extension/js/background_page/background_page.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/core/common.ts
- extension/js/common/core/expiration-cache.ts
- extension/js/common/platform/store/abstract-store.ts
- extension/js/common/platform/store/passphrase-store.ts
- test/source/tests/unit-node.ts
This PR saves passphrase to expiration cache
(to expire after 4 hours)
close #3565
> Passphrase expiration in session #3565

- extension/js/common/api/key-server/attester.ts
- extension/js/common/org-rules.ts
- test/source/tests/compose.ts
This PR fixes attester's lookupFingerprint() error
close #3800
> Special handling of disallow_attester_search for lookupFingerprint #3800

- extension/chrome/settings/index.ts
This PR will just rename the word "advanced" to "pro"
close #3836 
> renamed advanced to pro subscription label

- extension/chrome/popups/default.htm
- extension/css/cryptup.css
- extension/js/common/assert.ts
- package-lock.json
This PR improves the visual rendering of "Cannot find primary key. Is FlowCrypt not set up yet?" error so it doesn't look broken for users.
close #3669
> Better display of "Cannot find primary key. Is FlowCrypt not set up yet?" error

- extension/js/common/api/key-server/key-manager.ts
- extension/js/common/api/pub-lookup.ts
- extension/js/common/org-rules.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/compose.ts
- test/source/tests/setup.ts
This PR will remove deprecated code from pulling public keys from EKM. 
close #3841 // if this PR closes an issue
- Tests removed
> Remove deprecated code from pulling public keys from EKM

- extension/js/common/api/account-servers/enterprise-server.ts
This PR will simply removed the FES wip note
close #3750 // if this PR closes an issue
> Remove FES wip note comment

- tooling/build-types-and-manifests.ts
This PR adds a build type `chrome-enterprise-local-fes` so that we can test new FES functionality locally, without having to deploy new FES to a real server.
close #3886
> issue 3886 build type that uses local FES

- test/source/tests/gmail.ts
- test/source/tests/page-recipe/gmail-page-recipe.ts
This PR is another attempt to fix the flaky Gmail test.
close #3481
> Flaky gmail test for encrypted drafts: make sure there's no drafts before running this test

- extension/chrome/settings/modules/backup-manual-module.ts
This PR will rename key to asc backup file extension
close #2071 // if this PR closes an issue
> renamed key to asc backup file

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
This PR updates dated code comment about password protected messages.
no issue referenced 
**Tests**:
> updated msg formatter comment about fes

- package-lock.json
- package.json
- test/source/tests/decrypt.ts
This PR resolves these stale failing PRs:
- close #3921
- close #3852
`filesize.js` switched default units from KB (1024 bytes) to kB (1000 bytes) (here's why https://github.com/avoidwork/filesize.js/issues/137)
> Upgrade `filesize` and `pdfjs-dist` dependencies

- .github/workflows/check-for-emails.yml
This PR updates check-for-email action to FlowCrypt's own version
close #3956
- Tested in the repo https://github.com/FlowCrypt/issue947-src/
> issue #3956 Update check-for-emails action

- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
This PR will show cc and bcc email headers from a sent messages.
close #3473 // if this PR closes an issue
> Added cc and bcc rendering on message sent

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose.ts
- extension/js/common/platform/store/abstract-store.ts
- extension/js/common/platform/store/acct-store.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/compose.ts
This PR removes the legacy storage drafts support
close #3329
towards #3971 #3126 #3337
Note for reviewers: for a better review experience use `?w=1`: https://github.com/FlowCrypt/flowcrypt-browser/pull/3972/files?w=1
> Remove legacy storage drafts

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose.ts
- test/source/tests/gmail.ts
This PR checks if a local draft exists when loading the reply box. If so, the local draft will override a cloud draft.
close #3971
**Tests**:
> Check for local draft when loading a reply box, if exists update a cloud draft with a local one

- package.json
This PR fixes `author` field in the `package.json`.
close #4006
> Fix author in package.json

- test/source/tests/browser-unit-tests/unit-Sks.js
- test/source/tests/compose.ts
This PR fixes unit test "Sks lookup pubkey - from live host"
close #4009
> issue #4009 Fix unit test: Sks lookup pubkey - from live host

- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/setup.htm
- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/setup.ts
This PR will add an option for generating rsa3072 key 
close #3447 // if this PR closes an issue
> add option for rsa3072 key

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/chrome/settings/modules/add_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/css/webmail.css
- extension/js/common/view.ts
This PR resolves tiny issues I discovered while reporting https://github.com/FlowCrypt/flowcrypt-browser/issues/4034#issuecomment-933386415
> Small fixes

- .github/workflows/check-for-emails.yml
This PR ignores "Flowcrypt Compatibility" email address in the issue comments.
close #4037
> issue #4037 Ignore Flowcrypt Compatibility in the email check in comments

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-sender-module.ts
- extension/js/common/api/email-provider/email-provider-api.ts
- extension/js/common/api/email-provider/gmail/gmail-parser.ts
This PR simplifies namings
issue #4107
> simpler namings

- extension/js/common/api/account-servers/enterprise-server.ts
This PR adds googlemail to list of public domains so that we don't try to call fes on that domain - it's not there.
no issue
**Tests**:
> updated public mail servers list

- test/source/tests/gmail.ts
- test/source/tests/tooling/browser-recipe.ts
This PR fixes live gmail tests
close #4189
> Live gmail tests: fix selector for compose button container

- extension/chrome/elements/pgp_block.htm
- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-error-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- test/source/tests/decrypt.ts
- test/source/tests/tooling/browser-recipe.ts
- test/source/util/index.ts
This PR displays pgp error in a separate badge for easier removal
close #4253
> Display (some) pgp errors in a separate placeholder

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/setup.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/platform/store/contact-store.ts
- test/source/platform/store/contact-store.ts
- test/source/tests/browser-unit-tests/unit-ContactStore.js
This PR phases out ContactStore.obj(), ContactStore.save() and usage of `Contact` type for easier subsequent refactoring
issue #4268 // doesn't close the issue yet
> use ContactStore.update() instead of obj()/save()

- extension/css/webmail.css
- extension/js/common/inject.ts
This PR fixes compose button in collapsed Gmail look.
close #4287
- Does not need tests (style change only)
> issue 4287 fix small compose btn

- extension/js/common/api/key-server/wkd.ts
- extension/js/common/api/pub-lookup.ts
This PR sets a timeout of 10 seconds on WKD lookups:
- if my own account is using email key manager, AND
- I'm looking up a WKD email on the same domain as my own account
close #4320 
- Difficult to test (deals with internal timeouts, I tested it manually)
> conditionally increase WKD timeout

- extension/css/webmail.css
- extension/js/common/xss-safe-factory.ts
This PR will add an additional condition check for the third case where Gmail UI change occurs (with sticky sidebar)
close https://github.com/FlowCrypt/flowcrypt-browser/issues/4328
> add additional check for third case of gmail UI change

- extension/js/common/core/crypto/key.ts
- test/source/platform/store/contact-store.ts
- test/source/tests/settings.ts
This PR removes all unnecessary methods from test platform implementation of ContactStore
> removed unnecessary methods from test platform ContactStore

- extension/js/common/browser/env.ts
- extension/js/common/inject.ts
- extension/js/common/xss-safe-factory.ts
This PR refactors and fixes rendering of secure compose button.
close #4349
- Difficult to test (involves response to a changed Gmail UI that is not always present)
> issue 4349 wip refactor secure compose button code

- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-error-module.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/core/mime.ts
- extension/js/common/lang.ts
- extension/lib/emailjs/emailjs-mime-parser.js
- test/source/mock/google/exported-messages/message-export-18024d53a24b19ff.json
- test/source/tests/decrypt.ts
- test/source/tests/tooling/browser-recipe.ts
This PR fixes showing ISO-2022-JP encoded content
close #3520
> issue #3520 Properly show ISO-2022-JP encoded content

- extension/chrome/elements/compose-modules/compose-err-module.ts
This PR this PR will fix the anchor tag within the API network message.
close #4420 // if this PR closes an issue
screenshot:
> Fix anchor tag in the api network error message

- extension/js/common/org-rules.ts
- package-lock.json
- test/source/mock/backend/backend-data.ts
- test/source/tests/setup.ts
This PR added allow_attester_search_only_for_domains org rule
close #4476 // if this PR closes an issue
> #4476 added allow_attester_search_only_for_domains org rule

- extension/chrome/settings/modules/contacts.ts
- extension/js/common/api/key-server/attester.ts
- extension/js/common/api/pub-lookup.ts
- extension/js/common/org-rules.ts
This PR removed lookup of public key by fingerprint
close #4481 // if this PR closes an issue
> #4481 Remove lookup of public key by fingerprint

- extension/js/common/api/key-server/key-manager.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/setup.ts
This PR changed api endpoint to v1
close #4488 // if this PR closes an issue
> #4488 change api endpoint to v1

- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-popover-module.ts
- extension/chrome/elements/compose-modules/compose-types.ts
- test/source/tests/compose.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
This PR enforces message signing when encrypting
close #3475 // if this PR closes an issue
> #3475 Enforce message signing when encrypting

- extension/chrome/settings/setup/setup-key-manager-autogen.ts
This PR improved EKM import key screen response
close #4335 // if this PR closes an issue
> #4335 Improve EKM import key screen response

- .husky/pre-commit
- package-lock.json
- package.json
This PR implemented lint-staged and commit hook.
close #4523 // if this PR closes an issue
> #4523 Implement lint-staged and commit hook

- .semaphore/semaphore.yml
- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/js/common/xss-safe-factory.ts
- test/source/tests/gmail.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
- test/source/tests/tooling/browser-recipe.ts
This PR fixed live gmail tests
close #4432 // if this PR closes an issue
> #4432 Fix live gmail tests

- .husky/pre-commit
This PR disables husky temporary.
> Disable husky

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose-modules/formatters/general-mail-formatter.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
This PR checks for bad keys in a consistent manner between sending and saving draft
close #4377 // if this PR closes an issue
- Tests updated
> #4377 Check for bad keys in a consistent manner between sending and saving draft

- test/source/tests/compose.ts
This PR fixed load contacts through API ui test
close #4011 // if this PR closes an issue
> #4011 Fix load contacts through API ui test

- extension/chrome/dev/ci_unit_test.ts
This PR fixed any in ci_unit_test
close #4541 // if this PR closes an issue
> #4541 Fix: any in ci_unit_test

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/tests/compose.ts
This PR fixed cache found contacts locally as soon as they are fetched issue
close #4532 // if this PR closes an issue
- Test added
> #4532 fix: cache found contacts locally as soon as they are fetched issue

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
This PR get rid of canReadEmails
close #4600 // if this PR closes an issue
> #4600 fix: get rid of canReadEmails

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/gmail.ts
This PR fixes responding with plain message is not possible issue when using triple dot
close #4621 // if this PR closes an issue
> #4621 fix responding with plain message is not possible issue when using triple dot

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/tests/compose.ts
This PR fixed re-enter recipient issue
close #4628 // if this PR closes an issue
> #4628 fix: re-enter recipient issue

- extension/chrome/settings/setup.htm
- test/source/mock/google/google-endpoints.ts
- test/source/tests/flaky.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
This PR fixes an error most non-enterprise users saw during setup after last update.
close #4650
**Tests**:
- Test added
> Issue 4650 setup backup hotfix

- extension/chrome/dev/ci_unit_test.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/core/buf.ts
- extension/js/common/core/crypto/pgp/pgp-hash.ts
- test/source/tests/browser-unit-tests/unit-Crypto.js
- test/source/tests/compose.ts
- test/source/tests/unit-node.ts
This PR uses window.crypto to get SHA-256
close #4626 // if this PR closes an issue
- Test updated
> #4626 use window.crypto to get SHA-256

- extension/js/common/client-configuration.ts
- extension/js/common/platform/store/in-memory-store.ts
- extension/js/common/platform/store/passphrase-store.ts
- test/source/mock/backend/backend-data.ts
- test/source/tests/setup.ts
- test/source/tests/tooling/browser-recipe.ts
This PR configures passphrase session length with in_memory_pass_phrase_session_length 
close #4613 // if this PR closes an issue
> #4613 Configure passphrase session length with in_memory_pass_phrase_session_length 

- extension/js/common/api/email-provider/gmail/google-auth.ts
- extension/js/common/notifications.ts
- test/source/mock/google/google-data.ts
- test/source/tests/gmail.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
- test/source/tests/setup.ts
- test/source/util/index.ts
This PR fixed reconnecting authentication on existing installation issue
close #4693 // if this PR closes an issue
> #4693 fix: issue reconnecting authentication on existing installation

- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/setup.ts
- extension/js/common/api/key-server/attester.ts
- extension/js/common/client-configuration.ts
- extension/js/common/lang.ts
- extension/js/common/platform/catch.ts
- extension/js/common/settings.ts
- test/source/mock/attester/attester-endpoints.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/lib/oauth.ts
- test/source/tests/setup.ts
This PR stops using initialLegacySubmit and implemented new org rule `SETUP_ENSURE_IMPORTED_PRV_MATCH_LDAP_PUB`
close #4609 // if this PR closes an issue
> #4609 stop using initialLegacySubmit

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/gmail.ts
This PR fixed attachment count live test(Gmail changed little behavior for attachment preview and therefore live test was broken)
> Fix: attachment count live test

- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/setup.ts
- extension/js/common/api/key-server/attester.ts
- test/source/mock/attester/attester-endpoints.ts
This PR changed `test/welcome` endpoint to `welcome-message`.
close #4710 // if this PR closes an issue
> #4710 fix: updated test/welcome endpoint

- extension/js/common/client-configuration.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/fes/fes-endpoints.ts
- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR requires flags parameter in client configuration
close #4694 // if this PR closes an issue
> #4694 Require flags parameter in client configuration

- extension/js/common/client-configuration.ts
- test/source/mock/backend/backend-data.ts
- test/source/tests/setup.ts
This PR fixed null client configuration
close #4724 // if this PR closes an issue
> #4724 fix null client configuration

- test/source/mock/google/google-endpoints.ts
- test/source/mock/lib/oauth.ts
- test/source/tests/gmail.ts
- test/source/tests/setup.ts
This PR moved several live test to mock test
close #4698 // if this PR closes an issue
> #4698 move live test to mock test

- extension/chrome/dev/ci_unit_test.ts
- extension/js/common/core/common.ts
- extension/js/common/platform/catch.ts
- test/source/tests/browser-unit-tests/unit-Catch.js
This PR filters sensitive fields from logs
close #3824 // if this PR closes an issue
> #3824 filter sensitive fields from logs

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/mock/google/live-gmail-test-emails/[ci.test] Test switch to encrypted reply for middle message - 0(FMfcgzGqRGfPBbNLWvfPvDbxnHBwkdGf).eml
- test/source/mock/google/live-gmail-test-emails/[ci.test] Test switch to encrypted reply for middle message - 1(FMfcgzGqRGfPBbNLWvfPvDbxnHBwkdGf).eml
- test/source/tests/gmail.ts
This PR fixes switch to encrypted reply issue for messages (Thread messages which is not the last message)
close #4496 // if this PR closes an issue
> #4496 fix: switch to encrypted reply

- test/source/browser/controllable.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
This PR starts OAuthPageRecipe.waitForNavigationIfAny before clicking
This probably fixes the intermittent bug
close https://github.com/FlowCrypt/flowcrypt-browser/issues/4763
- Does not need tests (internal changes)
> Start waiting for navigation before clicking

- extension/chrome/elements/passphrase.htm
- extension/chrome/elements/passphrase.ts
- extension/js/common/core/common.ts
- extension/js/common/lang.ts
This PR fixed visual glitch opening passphrase dialog
close #4681 // if this PR closes an issue
> #4681 fix: visual glitch opening passphrase dialog

- .semaphore/semaphore.yml
- test/source/mock/backend/backend-data.ts
- test/source/mock/fes/fes-endpoints.ts
- test/source/mock/google/exported-messages/message-export-1803be3182d1937b.json
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/mock/wkd/wkd-endpoints.ts
- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
- test/source/tests/setup.ts
- tooling/build-types-and-manifests.ts
This PR removed hosts requirement
close #4631 // if this PR closes an issue
> #4631 fix: remove hosts

- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/js/common/settings.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/tests/compose.ts
This PR fixed compose issue when account not connected
close #4792 // if this PR closes an issue
> #4792 fix: compose issue when account not connected

- extension/js/common/api/account-servers/flowcrypt-com-api.ts
- test/source/mock/backend/backend-endpoints.ts
- test/source/tests/gmail.ts
This PR password protected message send issue when FES is not used
close #4792 // if this PR closes an issue
> #4792 fix: Password protected message issue when FES is not used

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose.ts
- extension/chrome/settings/modules/debug_api.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/js/common/api/email-provider/gmail/google-auth.ts
- extension/js/common/platform/store/acct-store.ts
- test/source/mock/google/google-endpoints.ts
- test/source/mock/lib/oauth.ts
- test/source/tests/compose.ts
This PR uses google api to get allowed google scopes
close #4675 // if this PR closes an issue
> #4675 Use google api to get allowed google scopes

- extension/chrome/settings/index.ts
- extension/js/common/api/account-servers/enterprise-server.ts
- extension/js/common/api/account-servers/flowcrypt-com-api.ts
- extension/js/common/client-configuration.ts
- extension/js/common/settings.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR ensures gracious behavior & ui should remain functional when updating client configuration
close #4815 // if this PR closes an issue
> #4815 Ensure gracious behavior & ui should remain functional when updating client configuration

- extension/chrome/settings/modules/contacts.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/mock/sks/sks-endpoints.ts
- test/source/tests/setup.ts
This PR implemented custom SKS server client configuration test 
close #3346 // if this PR closes an issue
> #3346 custom SKS server client configuration test 

- test/source/tests/browser-unit-tests/unit-ContactStore.js
- test/source/tests/unit-browser.ts
This PR close #4850
- Tests updated
> Thoroughly check unit-browser titles

- .husky/pre-commit
- package.json
This PR enabled commit lint
close #4523 // if this PR closes an issue
> #4523 Enable commit lint

- extension/chrome/elements/compose-modules/compose-pwd-or-pubkey-container-module.ts
- test/source/browser/controllable.ts
- test/source/tests/compose.ts
This PR shows correct indicator for message password
close #4872 // if this PR closes an issue
> #4872 feat: show correct indicator for message password

- package.json
This PR runs prettier as pre-commit hook
close #4878 // if this PR closes an issue
> #4878 feat: run prettier as pre-commit hook

- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
- test/source/tests/setup.ts
This PR fixed negative expiration note
close #4853 // if this PR closes an issue
> #4853 fix: negative expiration note

- tooling/release-firefox-latest-update.json
- tooling/release-step-2-upload
This PR adds a missing firefox update json file that will be put at https://flowcrypt.com/api/update/firefox
close #4893
> issue 4893 path + ff update file

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
This PR fixed old drafts lost issue when user doesn't enter passphrase
close #4895 // if this PR closes an issue
- Difficult to test (This issue is hard/impossible to reproduce in CI environment.)
> #4895 fix: Old drafts lost issue when user doesn't enter passphrase

- extension/js/common/api/email-provider/gmail/google-auth.ts
This PR simplified google auth login logic
close #4913 // if this PR closes an issue
> #4913 fix: simplify google auth login logic

- extension/js/common/api/account-servers/external-service.ts
This PR added `authHdr` in all FES calls
close #4912 // if this PR closes an issue
> #4912 feat: added authHdr in all FES calls

- extension/chrome/elements/compose.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/security.ts
- extension/js/common/api/account-server.ts
- extension/js/common/api/email-provider/gmail/google-auth.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
This PR initialized external service at init in AccountServer
close #4917 // if this PR closes an issue
> #4917 fix: initialize external service at init

- .semaphore/semaphore.yml
This PR reduces instance size for linters and ui tests.
no issue
> use smaller instances for small tests

- .semaphore/semaphore.yml
- test/source/mock/fes/customer-url-fes-endpoints.ts
- test/source/mock/fes/shared-tenant-fes-endpoints.ts
- test/source/mock/lib/mock-util.ts
This PR moves `messageIdRegex` to helper (as per PR review comment)
close #4734
> #4734 Move messageIdRegex to helper

- extension/js/common/platform/store/contact-store.ts
- test/source/browser/controllable.ts
- test/source/tests/compose.ts
This PR fixed duplicated contact search result
close #4282 // if this PR closes an issue
- Test updated
> #4282 fix: duplicated contact search result

- extension/chrome/elements/compose-modules/compose-quote-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- test/source/tests/compose.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
This PR shows signature right away in secure compose window
close #4959 // if this PR closes an issue
> #4959 Show signature right away in secure compose window

- extension/chrome/settings/modules/contacts.ts
- extension/js/common/xss-safe-factory.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
As part of research of issue #3448 
This PR only contains some refactoring/simplifications so we can merge it right away
- Does not need tests (refactor only)
> refactor armored blocks replacement

- extension/js/common/api/email-provider/gmail/google-auth.ts
This PR removes unused line.
no issue
> no issue - removed unused value

- package.json
This PR runs `pretest` in postinstall
close #4981 // if this PR closes an issue
> #4981 Run `pretest` in postinstall

- extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
- extension/js/common/api/key-server/keys-openpgp-org.ts
- extension/js/common/api/pub-lookup.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/keys-openpgp-org/keys-openpgp-org-endpoints.ts
- test/source/tests/setup.ts
This PR fixed PR reviews of #4974
close #4989 // if this PR closes an issue
> #4989 fix: PR review of #4974

- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/tests/unit-node.ts
This PR creates a cleartext signed message in `MsgUtil.sign` if `detached=false`
close #4988
- Tests added and updated
> prefer cleartext signed message #4988

- extension/lib/README.md
> Fixed typo

- tooling/build-types-and-manifests.ts
This PR updates port for local FES build
close #5008
> #5008 Update local FES port

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/tests/compose.ts
This PR fixed Compose recipient box UI bug
close #4241 // if this PR closes an issue
> #4241 fix: Compose recipient box UI bug

- .semaphore/semaphore.yml
- test/source/tests/tooling/browser-recipe.ts
This PR closes #5018
- Does not need tests (refactor only)
> Fix expectComposeButton for gmail2022

- extension/js/common/core/attachment.ts
- extension/js/common/core/mime.ts
- extension/js/common/core/types/emailjs.d.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/mock/google/exported-messages/message-export-187085b874fb727c.json
- test/source/tests/decrypt.ts
This PR fixed failing parsing of signed message
close #5029 // if this PR closes an issue
> #5029 fix: failed parsing of signed message

- README.md
This PR added instructions on how to install development build to Chrome and Firefox
close #5016 // if this PR closes an issue
> #5016 Add instructions on how to install development build to Chrome and Firefox

- extension/chrome/settings/index.ts
This PR highlights development build in browser
close #5017 // if this PR closes an issue
> #5017 Highlight development build in browser

- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/setup.htm
This PR fixed pass phrase related ui texts
close #5012 // if this PR closes an issue
> #5012 Fix ui texts

- extension/js/common/core/crypto/pgp/msg-util.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
This PR removes patches for OpenPGP.js version < 5.7.0
- Does not need tests (internal changes)
> Removed type patches for OpenPGP.js

- test/source/mock/all-apis-mock.ts
- test/source/mock/attester/attester-endpoints.ts
- test/source/mock/keys-openpgp-org/keys-openpgp-org-endpoints.ts
- test/source/mock/lib/api.ts
- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/decrypt.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR refactored Api class to accept configProvider
close #5077 // if this PR closes an issue
> #5077 feat: Refactor Api class to accept configProvider

- test/source/browser/controllable.ts
- test/source/tests/compose.ts
This PR makes tests more thorough by checking that only a single frame matching the url exists.
> ControllableBase.getFrame makes sure only one matching frame is present

- test/source/tests/tooling/browser-recipe.ts
This PR returns accessToken from setUpCommonAcct to be re-used by tests
Also returns `acctEmail`, that would help simplify some tests.
issue #4966
- Internal test refactoring
> return accessToken from setUpCommonAcct

- extension/js/common/platform/xss.ts
This PR fixed `colgroup` not rendered issue.
close #5111 // if this PR closes an issue
> #5111 fix: colgroup not rendered issue

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/css/cryptup.css
- extension/js/common/platform/store/contact-store.ts
- test/source/tests/compose.ts
This PR fixed contact search result loading for PGP key loading status
close #5131 // if this PR closes an issue
> #5131 fix: contact search result loading

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
This PR fixed encrypted draft open issue when passphrase expired
close #5144 // if this PR closes an issue
- Difficult to test (Testing the process of opening an encrypted draft within a thread cannot be simulated in a mock test and should only be done in live tests. However, it can be challenging to reproduce the behavior of an expired passphrase during live testing. Additionally, testing with drafts within a thread can be unstable since they may be discarded at any time.)
> #5144 fix: can't open encryptd draft issue after passphrase expire

- test/source/mock/google/google-endpoints.ts
- test/source/mock/lib/api.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR migrated google mock endpoint to `ConfigurationProvider`
close #5142 // if this PR closes an issue
> #5142 Migrate google mock endpoint to `ConfigurationProvider`

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-quote-module.ts
- test/source/browser/controllable.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/compose.ts
This PR fixed incorrect modification detection when saving drafts issue
close #5037 // if this PR closes an issue
- Difficult to test (Couldn't always reproduce this issue because in automated test, it's hard to type text to email body in less than 3 seconds after frame load)
> #5037 fix: incorrect modification detection when saving drafts

- extension/chrome/elements/compose.htm
This PR updates recipient text field input limit from 256 to 8000.
close #5168 
> issue #5168 increase recipient text field limit to 8000

- extension/js/common/api/account-servers/external-service.ts
- extension/js/common/platform/store/acct-store.ts
- extension/js/common/platform/store/in-memory-store.ts
This PR fixed getting id token issue in settings page
close #5173 // if this PR closes an issue
- Difficult to test (hard to reproduce)
> #5173 fix: get id token issue in settings page

- extension/js/common/platform/store/in-memory-store.ts
This PR fixed `value is not available issue` toast issue in gmail page
close #5176 // if this PR closes an issue
> #5176 fix: value is not available issue

- .github/dependabot.yml
- .github/workflows/ossar-analysis.yml
This PR implements auto-updating of github actions using `dependabot`
close #5186
> #5186 Use dependabot for github actions

- extension/chrome/settings/modules/compatibility.htm
This PR updates the usage description of the compatibility test page.
close #5221 
Screenshot:
> Issue #5221 provide broader usage description of the compatibility test page

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose.ts
- extension/chrome/elements/passphrase.htm
- extension/chrome/elements/passphrase.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/change_passphrase.htm
- extension/chrome/settings/modules/change_passphrase.ts
- extension/chrome/settings/modules/compatibility.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/help.ts
- extension/chrome/settings/modules/security.ts
- extension/chrome/settings/modules/test_passphrase.htm
- extension/chrome/settings/modules/test_passphrase.ts
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-render.ts
- extension/js/common/brute-force-protection.ts
- extension/js/common/lang.ts
- extension/js/common/platform/store/acct-store.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
- test/source/tests/decrypt.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
This PR added anti brute force protection
close #5215 // if this PR closes an issue
> #5215 Add anti brute force protection

- test/source/browser/browser-handle.ts
- test/source/browser/browser-pool.ts
- test/source/browser/controllable.ts
- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/decrypt.ts
- test/source/tests/flaky.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
- test/source/tests/tooling/browser-recipe.ts
- test/source/tests/tooling/index.ts
- test/source/tests/unit-browser.ts
This PR isolates debugHtmls and mockApiLogs to current test's context
close #5257 
close #5259
- Changes to internal test infrastructure
> Use TestContext and fix test infrastructure

- test/source/tests/decrypt.ts
This PR fixes after refactoring
issue #5248
- Does not need tests (test refactoring only)
> fix master following refactoring

- extension/js/common/api/email-provider/gmail/gmail-parser.ts
- extension/js/common/api/email-provider/gmail/google.ts
- extension/js/common/settings.ts
- test/source/mock/google/google-endpoints.ts
This PR fixed different sender name issue
close #5254 // if this PR closes an issue
- Difficult to test (Hard to reproduce in test environment)
> #5254 Fix: Different sender name issue

- extension/chrome/dev/ci_unit_test.ts
- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/js/common/platform/xss.ts
- test/source/tests/browser-unit-tests/unit-Xss.js
This PR fixes pattern warning and preserves leading and trailing \t
Close #5268
- Test added
> leading and trailing \t fixed

- extension/js/common/view.ts
This PR ensures that view rendering happens after 'load' event
> rendering after load event

- test/source/tests/gmail.ts
- test/source/tests/page-recipe/gmail-page-recipe.ts
This PR expands Main Menu when needed in Gmail live tests
close #5314
- Test refactoring
> Expand Gmail Main Menu when needed #5314

- extension/chrome/elements/compose-modules/compose-attachments-module.ts
This PR updates the attachment size limit in Rich Text Editor mode.
close #2538 
> #2538 Update attachment size limit in rich text mode

- extension/js/common/platform/store/acct-store.ts
- extension/js/common/platform/store/global-store.ts
This PR is preparation to address localStorage directly, without using the background page
close #5331
> #5331 Address localStorage from content script directly

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- package-lock.json
- package.json
- test/source/mock/fes/fes-constants.ts
This PR adds signature for password-protected messages.
close #5351
> #5351 Sign password-protected messages

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/js/background_page/background_page.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/platform/store/abstract-store.ts
- extension/js/common/platform/store/global-store.ts
- test/source/browser/controllable.ts
This PR removes unused code and improves some of the existing code
issue #0000
- Does not need tests (refactor only)
> removed unused code, tidy up

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/settings/inbox/inbox-modules/inbox-notification-module.ts
- extension/chrome/settings/modules/experimental.ts
- extension/js/background_page/background_page.ts
- extension/js/common/api/account-servers/external-service.ts
- extension/js/common/api/authentication/google/google-oauth.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/api/email-provider/gmail/google.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/platform/store/acct-store.ts
- extension/js/common/settings.ts
- extension/js/common/ui/backup-ui/backup-ui-automatic-module.ts
This PR renames the file `google-auth.ts`to `google-oauth.ts` and rename the exported class `GoogleAuth`to `GoogleOAuth`.
close #5319
> #5319 rename GoogleAuth to GoogleOAuth

- extension/js/common/lang.ts
This PR updates link to account recovery guide to be the same as in https://github.com/FlowCrypt/flowcrypt-web/pull/1296
> Update account recovery link

- extension/css/cryptup.css
This PR fixed key detail view wrap issue
close #5451 // if this PR closes an issue
> #5451 Fix: key detail view wrap issue

- extension/chrome/settings/modules/my_key.ts
This PR fixes the grammatical error present on `my_keys.ts` file.
close #5490 
> #5490 Fix grammatical error on my_keys.ts

- extension/changelog.txt
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR fixes broken `getConvoRootEl` after Gmail HTML code change. As base code I use 8.5.1 build, so we can make it a small release.
close #5494
> [hotfix release 8.5.2] #5494 reply buttons hotfix on 8.5.1 build

- extension/chrome/settings/modules/contacts.ts
This PR replaces the old URL with new one and capitalizes buttons.
close #5524
> #5524 Update the "use custom keyserver" button link on the "Contacts and their Public Keys" page and capitalize buttons

- extension/chrome/settings/index.ts
This PR fixes broken RSS links rendered in the FlowCrypt settings page.
close #5526 
> #5526 Fix RSS broken links rendered in FlowCrypt settings page

- extension/chrome/settings/modules/help.ts
- extension/js/common/api/account-servers/external-service.ts
- test/source/mock/fes/shared-tenant-fes-endpoints.ts
This PR removes the `boolean` JSON parameter `sent` in the send user feedback endpoint.
close #5493 
> #5493 Remove parameter check in feedback endpoint

- test/source/tests/gmail.ts
- test/source/tests/page-recipe/gmail-page-recipe.ts
This PR removes previous temporary fix from live test
> Fix live test

- extension/js/common/core/mime.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- package-lock.json
- package.json
This PR fixes broken rendering for thread which includes unencrypted replies to encrypted messages
close #5560
- Difficult to test (explain why) - wasn't able to recreate similar thread
> #5560 Fix rendering for thread with unencrypted reply

- test/source/tests/tooling/browser-recipe.ts
This PR fixes live test for `mail.google.com/chat` as Google has updated UI and some selectors were changed.
> Fix chat live test

- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.3 and adds changelog
> Release 8.5.3

- extension/js/common/api/authentication/google/google-oauth.ts
- extension/js/common/api/shared/api.ts
This PR temporary disables usage of fetch upload streaming because of http/2 issues for some users
close #5612
- Difficult to test (explain why) - difficult to reproduce circumstances for failing requests
> #5612 Temporary disable fetch upload streaming

- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.4 and adds changelog
> Release 8.5.4

- extension/chrome/elements/compose-modules/compose-input-module.ts
This PR fixed Squire WillPaste Handler
close #5684 // if this PR closes an issue
> #5684 Fixed Squire WillPaste Handler

- extension/chrome/elements/add_pubkey.htm
- extension/css/cryptup.css
This PR makes text and UI improvements of the "Add a public key to email address" page.
close #5695
Before
After
> #5695 Improve the "Add a public key to email address" page texts and UI

- test/source/tests/setup.ts
This PR split automatic key update tests
close #5395 // if this PR closes an issue
> #5395 Split automatic key update tests

- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.5 and adds changelog
> Release 8.5.5

- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
This PR fixed show original message logic
close #5733 // if this PR closes an issue
> #5733 Fix: original message

- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.6 and adds changelog
> Release 8.5.6

- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.7 and adds changelog
> Release 8.5.7

- eslint.config.mjs
- extension/js/common/api/key-server/attester.ts
- extension/js/common/browser/browser.ts
- extension/js/common/browser/env.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- flowcrypt-browser.code-workspace
- package-lock.json
- package.json
- test/source/browser/browser-handle.ts
- test/source/browser/controllable.ts
- test/source/mock/attester/attester-key-constants.ts
- test/source/mock/google/google-data.ts
- test/source/mock/google/google-endpoints.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/mock/keys-openpgp-org/keys-openpgp-org-endpoints.ts
- test/source/mock/lib/api.ts
- test/source/patterns.ts
- test/source/tests/flaky.ts
- test/source/tests/page-recipe/abstract-page-recipe.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/tooling/browser-recipe.ts
- test/source/tests/tooling/index.ts
- test/source/tests/unit-node.ts
- tooling/build-types-and-manifests.ts
This PR fixes issues found by ESLint (mostly in test files), removes unused properties from ESLint config and updates TypeScript to 5.5
> Fix found ESLint issues

- SECURITY.md
This PR updated expired links in SECURITY.md
> Update expired links in SECURITY.md

- extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts
This PR fixed unexpected draft creation issue
close #5616 // if this PR closes an issue
> #5616 Fix: unexpected draft creation

- extension/chrome/elements/pgp_block.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts
This PR fixed message loading stuck issue
close #5770 // if this PR closes an issue
- Difficult to test (Couldn't reproduce in ci environment)
> #5770 Fix: message loading stuck issue

- extension/chrome/elements/shared/key_errors.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/js/common/browser/ui.ts
- extension/js/common/ui/key-import-ui.ts
This PR fixed acctEmail not included when redirecting user to compatibility page issue
close #5768 // if this PR closes an issue
> #5768 Fix: acctEmail not included when redirecting user to compatibility page

- test/source/browser/browser-handle.ts
- test/source/tests/gmail.ts
This PR fixed live tests
close #5806 // if this PR closes an issue
> #5806 Fix live tests

- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- extension/js/common/core/crypto/key.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR added key status and creation date in key list & detail page
close #4407 // if this PR closes an issue
> #4407 Add key status and creation date in key list & detail page

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/browser/chrome.ts
- extension/js/common/browser/env.ts
This PR fixed enable google contact search issue in firefox
close #5704 // if this PR closes an issue
> #5704 Enable google contact search in firefox

- extension/chrome/settings/index.ts
- extension/js/common/lang.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR added feature to show confirm modal when deleting key
close #5832 // if this PR closes an issue
> #5832 Show confirm modal when deleting key

- extension/js/service_worker/bg-handlers.ts
- tooling/build-types-and-manifests.ts
This PR lets firefox use manifest V3
close #5829// if this PR closes an issue
> #5829 Use manifest V3 for firefox

- extension/css/cryptup.css
This PR highlighted contact for mouse hover in contact popup.
close #5926 // if this PR closes an issue
> #5926: Contact popup recipient selection mouse highlight

- extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts
- test/source/tests/gmail.ts
This PR adds secure reply to all button for password protected message
close #5933 // if this PR closes an issue
> #5933 Add secure reply to all button for password protected message

- .github/dependabot.yml
- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.10 and adds changelog
> Release 8.5.10

- extension/js/common/browser/browser-msg.ts
- extension/js/service_worker/background.ts
This PR implemented feature to clean up unused alarms
close #5940 // if this PR closes an issue
> #5940 Clean up unused alarms

- eslint.config.mjs
- package-lock.json
- package.json
This PR changed to default eslint header plugin
close #5977 // if this PR closes an issue
> #5977 Use original eslint header plugin

- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
- tooling/release-step-2-upload
This PR adds changelog and updates version to 8.5.11
> Release 8.5.11

- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- package-lock.json
- package.json
- scripts/build.js
- tsconfig.json
This PR uses Clipboard API instead of ClipboardJS
close #6013 // if this PR closes an issue
> #6013 Use Clipboard API instead of ClipboardJS

- test/source/tests/tooling/browser-recipe.ts
This PR fixed gmail live chat test
close #6041 // if this PR closes an issue
> #6041 Fix: gmail live chat test
