- chrome/js/common/common.js
Bugfix: single-byte ASCII characters below 192 (eg. 160 = non-breaking space) or above 192 (eg. 233 = 'é') were not correctly decoded.
Fixes #808
> Bugfix: Missing accentuated characters in decrypted HTML content

- chrome/manifest.json
- Replacing the `icon` property for `default_icon` , Fixes bug with higher resolution icons shown. 
https://developer.chrome.com/extensions/tut_migration_to_manifest_v2#api-checklist
> Updates Flowcrypt icon used in browser 

- extension/js/common/composer.ts
Solves https://github.com/FlowCrypt/flowcrypt-browser/issues/1001
Considered using `this.removeReceiver(htmlElement)` but it expects the recipient close "x" element to be passed which is a bit clunky, and`this.showHidePwdOrPubkeyContainerAndColorSendBtn();` is already used a few times in the same manner.
> check if password box etc. should be removed recipient deletion via backspace

- extension/css/webmail.css
Fixes https://github.com/FlowCrypt/flowcrypt-browser/issues/1529 by matching Gmail's Compose button style.
> Update secure compose style

- extension/js/common/api/api.ts
- extension/js/common/api/google.ts
- extension/js/common/settings.ts
Anything that needs to be done to setup tests so I can write some? I get:
`Error: ENOENT: no such file or directory, open 'test/test-secrets.json'`
Also, we could filter out emails on "verificationStatus" (user might not have validated his alias) or leave that to users to decide. What do you think?
> fixes #929 : Use Gmail api to fetch user email aliases

- extension/js/common/composer.ts
Applies feature for #813 In the `draftSave` function, which is executed every 3 seconds, I added a test for ensuring the subject line has changed. If the subject line OR the message body have changed, then the daftSave function is executed.
I am tracking the subject line in a variable called `lastSubject`, which is changed to the new subject line when the function `hasSubjectChanged` has been executed.
The function for testing whether the messageBody has changed was also modified slightly because the `else` seemed redundant. This function was renamed to `hasBodyChanged`, and was copied to `hasSubjectChanged` for testing changes to the subject line.
> Allow a draft to be saved if body or subject has changed

- extension/chrome/settings/inbox/inbox.htm
- extension/chrome/settings/inbox/inbox.ts
- Adds a 'Show Original' button to the FlowCrypt inbox
- Only shows the button if there are PGP messages in the thread
- When button is click:
- page is reloaded with a 'showOriginal' url param set to 'true'
- PGP blocks are not rendered but instead shown as text wrapped in a pre tag
- The button is changed to show 'See Decrypted' now
- When 'See Decrypted' is clicked page is reloaded again but with the 'showOriginal' url param omitted
> Fixes 1414 - add a 'show original' button to fc inbox

- extension/js/common/composer.ts
Fixes https://github.com/FlowCrypt/flowcrypt-browser/issues/1564
Note that this UX differs from that of deleting a normal gmail reply:
Normal reply --> delete draft --> editor closes and user needs to click reply again
Secure reply --> delete draft --> text disappears, any extra recipients disappear, but editor stays open.
This was the ask in https://github.com/FlowCrypt/flowcrypt-browser/issues/1564, and I think it's a fine UX, just wanted to make the difference explicit.
> Reload reply iframe instead of removing it

- extension/js/common/browser.ts
- extension/js/common/composer.ts
Remove automatic adding of "Re: <subject>" in browser.ts and detect undefined and use empty string instead upon send in composer.ts
> Leave empty reply empty on message send

- extension/js/common/browser.ts
fixes #1595 
* Variables named 'id' in AttUI methods are renamed 'uploadFileId' to avoid confusion about Att.id field which is unrelated.
> rename variables name 'id'

- extension/chrome/settings/modules/contacts.htm
- extension/chrome/settings/modules/contacts.ts
- extension/js/common/browser.ts
- extension/js/common/core/pgp.ts
- extension/js/common/platform/require.ts
- extension/types/openpgp.d.ts
- review-branch.sh
Fixes #1134 . Adds a button to the contacts page that allows choosing a file, if the file selected is a valid PGP key file in binary format, the armored key is written to the public key input field.
> Add a button to import binary keyfile

- extension/chrome/elements/pgp_block.ts
- extension/chrome/settings/modules/contacts.ts
- extension/chrome/settings/modules/keyserver.htm
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/setup.ts
- extension/js/common/api/attester.ts
- extension/js/common/api/keyserver.ts
- extension/js/common/api/sks.ts
- extension/js/common/composer.ts
- extension/js/common/platform/store.ts
- extension/js/common/rules.ts
- extension/js/content_scripts/webmail/gmail_element_replacer.ts
#1819 4 hrs
The `Rules` class needs a sha1 implementation, which is available in OpenPGP.js, which is not available everywhere in the plugin (not available in `pgp_block.ts` for performance reasons). Since we use Rules class more in this PR, I needed to give it a native sha1 implementation that is not dependent on OpenPGP.js.
Also I took a shortcut to hardcode a keyserver into the `Rules` class instead of serving it from the backend, that should be fixed in the future.
> Issue #1819 custom ks

- extension/chrome/elements/pgp_pubkey.ts
Issue #1883 
Time Spent: 20m
Yes, sorry, that was my bad,
I don't know why but I thought that `background-color: inherit;` inherits the previous color but it doesn't, it inherits something else (maybe I will investigate it later)
> Issue #1883 Leave else case empty instead of 'inherit'

- extension/css/sweetalert2.css
- extension/js/common/browser.ts
- extension/lib/sweetalert2.js
- extension/types/sweetalert2.d.ts
- package.json
A lot of good things (improvements, features and bug fixes) happened to SweetAlert2 since v8.0.7 so it makes sense to upgrade to the latest stable version.
The string value of `customClass` is still supported but it was deprecated, so I replaced it with an object, everithing else seems fine to me.
> Upgrade sweetalert2 to the latest version

- extension/js/common/composer.ts
Closes #1902 
I wasn't able to find the original PR adding this workaround, probably because it was added long ago and not needed anymore.
```js
// the padding cause issues in firefox where user cannot click on the message password
```
I guess "the message password" is this one:
I manually tested it with changes from this PR, works nicely (Firefox 68)
> Remove setting padding-top and padding-bottom to 0 in Firefox

- extension/js/common/composer.ts
Closes #1929
@tomholub WDYT about adding
```css
transition: height 0.1s ease-in-out
```
to `#new_message`? To me personally, the height animation makes an impression better.
> Height of the minimized iframe should be equal header's height

- extension/chrome/settings/initial.htm
Closes #1898
Made the icons a bit more greenish. Also, removed the `-webkit` prefix as `filter` property is supported now: https://caniuse.com/#feat=css-filters
> Make logo a bit more consistent with the one in toolbar

- extension/css/cryptup.css
- extension/js/common/composer.ts
Closes #1925 
> When there is just one email in input_from, the from-select-option was hidden but I think it would still trap focus when tabbing. So you would need to double-tab to get from recipients to body. It wasn't smooth. Please test if it's still the case, and if it is, see what could be done about it.
Tested, no longer the case, because there's no `<select>` when there is just one email:
> Include #input_from to taborder

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
- extension/js/common/ui/att_ui.ts
Fixes #1958
I made the `<input>` inside of `.icon.attach` focusable, that seems to be the only way to make it clickable with the keyboard.
Also, moved the `title` attr to `<input>`. Previously, browsers were showing the default input title instead of "Attach a file":
> Implement clicking the 'Attach a file' button with a keyboard

- extension/chrome/settings/modules/contact_page.htm
Issue #1928,
Result:
I fixed alignment of `Full Name:` ​​placeholder but actually I'd like to get rid of it because we don't have any similar inputs in the extension (I haven't seen that large placeholder) and I think our users can intuitively understand that there should be their name so I think without a placeholder it would look better.
> issue #1928, Corrected margins of placeholder

- extension/css/cryptup.css
Closes #1967
The font size of related DOM elements is switched from `px` to `em`, the `body`'s font size is switched to `rem`. This way it is easy to override the base value with one css setting (try to change body's font-size in dev tools, all children will be resized accordingly:
This argument is laid out in this article: https://css-tricks.com/rem-global-em-local/
---
When testing, keep in mind that browsers need page reload in order to apply the font-size setting to an iframe.
> Issue #1967 convert font-size px -> rem/em

- extension/css/cryptup.css
This is probably one of the most popular mistakes of front-end developers, there's even the website for it :) http://outlinenone.com/
@michael-volynets @tomholub please do not use `outline: none` without adding some other way of indicating the focused state, e.g. adding `border` to `:focus` state.
Without outline, it's not possible to see the focused state of the element and UI becomes unusable for keyboard users (hackers, people with inabilities to use mouse/trackpoint, etc.).
> Remove outline: none on #input_from

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
Fixes #2045 
I converted `<div>`s to `<button>`s. It's always a good idea to use `<button>` tags for buttons, by doing that we're getting all a11y features for free (it's built-in in browsers), e.g. this line was removed:
```js
this.S.cached('send_btn').keypress(Ui.enter(() => this.extractProcessSendMsg()));
```
`<button>`s are getting clicked automatically with `Enter` or `Spacebar`, no need in adding additional keyboard handlers.
---
Also, I removed the `border-radius: 2px` from `#send_btn` and `#toggle_send_options` in order to avoid messing around with `border-top/bottom-left/right-radius` properties. @tomholub please let me know if sharp buttons are agains design styleguide.
> Issue #2045 make 'Send' and 'Show send options' buttons focusable

- extension/js/common/composer.ts
- test/source/patterns.ts
Closes #2056 
To be honest, I do not understand what exaclty is the reason syncronous `.focus()` is not working in Chrome. It doesn't seem that something else is stealing focus from `input_text`.
The fix is a little ugly becase of so-called "magic" number `100`, I personally don't like magic numbers and try to avoid them when possible. @tomholub please let me know if it's too ugly to be in the codebase.
> Issue #2056 Focus input_text asyncronously when replying

- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
- extension/js/common/composer.ts
- extension/js/common/composer/composer-contacts.ts
- test/source/browser/controllable.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
Closes #2044
Also, in scope of this PR I made `cc` and `bcc` buttons accessible with keyboard (they are at the end of taborder)
As discussed per email conversation I changed some lines in JS side to use IDs instead of tag names or classnames:
- `recipients_placeholder: '#recipients_placeholder'`
- `cc: '#cc'`
- `bcc: '#bcc'`
@michael-volynets @tomholub this practice is bad and should be avoided in future:
```js
this.composer.S.cached('email_copy_actions').find('span')
```
The reason why it's bad is that JS should not rely on tag names at all. In this PR I was changing `<span>`s to `<button>`s and was not expecting to break something on the JS side by doing that.
Copy-pasting the good practice suggested by @tomholub here:
> - tags only have html structure significance, and not used …
> Make the 'Recepients' field accessible with keyboard

- extension/js/common/composer.ts
> Issue #2062, Remove .blur().focus() trick and run parseRenderRecipients() directly

- extension/js/common/composer/composer-contacts.ts
Issue #2077 
Time Spent 2h 30m,
The reason why that wasn't working is because Chromium triggers the`dragend` event before `drop` event when we use it in Gmail webmail, maybe it's their bug or what but it should have been vice versa. 
At the first, I just removed `dragend` event but it caused me more problems so I decided to cover the body of `dragend` event in `Catch.setHandeledTimeout` and it started working correctly.
About firefox, when we start drag&drop - then triggers blur event on `recipientElement` and it hides our inputs. 
I added `if` statement to check whether it was triggered by drag&drop or not, if no then do collapse
> Issue 2077 fix cc bcc drag and drop

- extension/css/browser-popup.css
- extension/css/cryptup.css
- extension/css/webmail.css
Closes #2055
`outline: none` should not be set on `a:focus` without replacing outline with some other kind of indication of the focused state.
All other occurrences of `outline: none` are fine - they are applied either for inputs where the focus can be visible by the cursor or for buttons with the alternative method of focus indication (borders + opacity).
> Issue #2055, Remove outline: none from links

- extension/chrome/elements/pgp_block.ts
- extension/js/common/core/mime.ts
Issue #1606,
Time Spent: 2h 30m (Almost all time I was investigating why it isn't working),
I'm not sure it's the right solution but I tried to make it work as Thunderbird does.
I tried to open this message in Thunderbird and they render the attachment and the text. So I did the same. Now, FlowCrypt decrypts the message correctly.
If you approve this solution I'll start writing the tests.
> [3h] Issue #1606, corrected Mime.decode method

- test/source/mock/strategies/send-message-strategy.ts
- test/source/tests/page_recipe.ts
- test/source/tests/tests/compose.ts
Issue #1452 
Time Spent: 1h 40m
When I finished writing the test and I ran it, unfortunately, it didn't pass, I didn't know why because the test was written correctly. The problem was because of `email-mime-codec` `foldLines` method, it added a new line symbol and the message changed.
Could you please explain to me why do we need this method?
> [2h] Issue #1452 test signed messages

- extension/chrome/elements/shared/attach.template.htm
- extension/css/cryptup.css
Closes #2142
This was my oversight from #2043
Also, fixed the `tabindex` of attachment buttons, so they are just before the Send button.
@tomholub this behavior is opinionated, in Gmail those buttons are actually inaccessible with keyboard so it might be unusual for users. Let me know if you think attachments should be after the Send button in the taborder.
> Improve the responsiveness of attachments

- extension/js/common/composer.ts
Closes #2165 
This small node was forgotten in `setInputTextHeightManuallyIfNeeded()`:
> Issue 2165 take icon_show_prev_msg's height into account in setInputTextHeightManuallyIfNeeded()

- extension/js/common/core/mime.ts
- extension/js/common/core/pgp.ts
- extension/js/common/xss_safe_factory.ts
> issue 2216 stop replacing verification blocks

- .vscode/launch.json
With this configuration it's possible to debug `chrome_consumer_live_gmail` tests by using breakpoins (either `debugger` or VSCode breakpoins):
Using the VSCode debugger over `console.log` will save us a ton of time when writing tests.
Docs on setting up debug configuration in AVA: https://github.com/avajs/ava/blob/master/docs/recipes/debugging-with-vscode.md
Common docs on debugging in VSCode: https://code.visualstudio.com/docs/editor/debugging
> Add launch.json with the config to debug chrome_consumer_live_gmail

- extension/js/common/composer/composer-draft.ts
Fixes #2274 
The initial value of `lastDraftBody` isn't always `''`. In case the account has a signature (footer), the initial value of `lastDraftBody` should be the user's signature so `hasBodyChanged()` will return the correct result.
> Fix initializing lastDraftBody

- extension/chrome/elements/pgp_pubkey.ts
> Refactored pgp_pubkey.ts file

- extension/chrome/elements/subscribe.ts
> Issue #2239, Refactored subscribe file

- .eslintignore
- conf/tslint.yaml
- extension/chrome/elements/composer/composer-storage.ts
- extension/chrome/elements/composer/formatters/encrypted-mail-msg-formatter.ts
- extension/chrome/elements/pgp_block_modules/pgp_block_render_module.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/js/background_page/bgutils.ts
- extension/js/common/api/api.ts
- extension/js/common/api/attester.ts
- extension/js/common/api/backend.ts
- extension/js/common/api/email_provider/gmail/gmail.ts
- extension/js/common/api/google-auth.ts
- extension/js/common/api/google.ts
- extension/js/common/api/keyserver.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/browser/ui.ts
- extension/js/common/core/mime.ts
- extension/js/common/platform/catch.ts
- extension/js/common/platform/store.ts
- extension/js/common/settings.ts
- extension/js/common/ui/att_ui.ts
- tooling/tslint-rules/awaitReturnedPromiseRule.ts
- tooling/tslint-rules/onelinerObjectLiteralRule.ts
close #1599 
This is extremely interesting. For our particular codebase, and our (edited compiler), if we want the longest possible stack trace, we need to await promises explicitly instead of returning them.
bad:
```js
threadGet = (threadId: string, format?: GmailResponseFormat, progressCb?: ProgressCb): Promise<GmailRes.GmailThread> => {
return Google.gmailCall(this.acctEmail, 'GET', `threads/${threadId}`, { format }, { download: progressCb }) as GmailRes.GmailThread;
}
```
good:
```js
threadGet = async (threadId: string, format?: GmailResponseFormat, progressCb?: ProgressCb): Promise<GmailRes.GmailThread> => {
return await Google.gmailCall(this.acctEmail, 'GET', `threads/${threadId}`, { format }, { download: progressCb }) as GmailRes.GmailThread;
}
```
This is because we hacked the …
> issue 1599 stack passing fix

- flowcrypt-browser.code-workspace
Follow-up for #2351
`autoFix` functionality for `.ts` files works only with this syntax as per https://github.com/microsoft/vscode-eslint/issues/609#issuecomment-460554105
> Enable ESLint autoFix for TS

- .vscode/extensions.json
I made a small Wiki page on how to get started with VSCode: https://github.com/FlowCrypt/flowcrypt-browser/wiki/Getting-started-in-VSCode
This PR will ensure that when a new developer starts working on the project, he/she will be prompted to install recommended extensions:
> Add recommended extensions .vscode/extensions.json

- flowcrypt-browser.code-workspace
They shipped changes two days ago: https://github.com/microsoft/vscode-eslint/blob/master/README.md
@michael-volynets already commited a new config in https://github.com/FlowCrypt/flowcrypt-browser/commit/55293b4dec056b2a3adb9523e6d4917e9e0e73b3 so in this PR I'm removing the deprecated ones.
> Update eslint config for VSCode workspace

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/composer/composer-send-btn.ts
- extension/chrome/settings/modules/backup.ts
- extension/js/common/core/common.ts
- extension/js/common/platform/store.ts
Issue #2416 
Time Spent: 1h 50m
I fixed those bugs and also added a new thing called `PromiseCencellationToken`, I should have added it because I found some kind of memory leak. In `attachment.ts` and `backup.ts` when we called `Store.waitUntilPassphraseChanged` and clicked `Later` button the cycle that checks if PP changed was working which is bad because how many times I opened modal dialog and clicked `Later` - how many times the function was running continuously.
This `PromiseCencellationToken` fixes that problem.
> Issue 2416 sendbtn is blocked when canceling pp modal

- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
- extension/js/common/core/pgp-key.ts
- extension/js/common/core/types/openpgp.d.ts
Issue #1842 
Time Spent: 4h
I thought it would be easier :)
I faced some issues that slowed me a little.
1. I had to update typings. First I decided to copy/pasted definitions from here `https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/openpgp/ts3.2/index.d.ts`  but that didn't work so I added that definitions that we only need.
2. I don't know why but `openpgp.key.Key.revoke` returns not `string` but `Stream`. I checked the original method to understand what's going on there. I checked it and didn't find out why so I had to somehow deal with that, and I corrected typings a little, so `openpgp.key.Key.revoke` may return either `string`, `Stream<string>` or `undefined`.
3. And the last thing I had to do is to handle a situation when a user doesn't have stored …
> Issue #1842, Added ability to download revocation certificate

- extension/chrome/elements/composer/composer-input.ts
- extension/chrome/elements/composer/composer-send-btn-popover.ts
- extension/lib/squire-raw.js
- extension/types/squire.d.ts
Fixes #2409
Unfortunately, it doesn't seem possible to fix the issue without changing `squire-raw.js`. In order not to override changes during the upgrade, I added the comment. @tomholub please let me know if you have some other suggestions on how to prevent accidental overriding changes in `lib` files.
Should we maybe create the internal fork of `squire` (as private repo) to mirror the changes we're doing on it?
> Do not autoformat links for plain text messages

- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/setup.htm
- extension/css/cryptup.css
- test/source/tests/browser_recipe.ts
- test/source/tests/page_recipe/setup-page-recipe.ts
Closes #2114 
Closes #1807
As promised, keyboard a11y is there for free:
As well as in `add_key.html`:
> Remove advanced options toggle

- flowcrypt-browser.code-workspace
Closes #2478 
I didn't find a better way to get rid of distracting underlines.
The `test_tslint` task will still report tslint issues in `test` folder, but VSCode won't highlight them.
> Disable vscode tslint for test folder

- extension/chrome/settings/setup.htm
Closes #2490 
It was changed from `<div>` to `<button>` by me in https://github.com/FlowCrypt/flowcrypt-browser/commit/f73d125a3dae7495bccd27518b40802460f628d9#diff-2dcb80916f2c15c0faa1e89f30197eefR322 not sure if it was somehow working with `<div>`, probably noe). It should definitely be `<a>` because we're setting `href` in https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/settings/setup.ts#L118
> COMPOSE ENCRYPTED EMAIL should be a link

- extension/css/settings.css
Closes #2566 
The Secure Compose button is wider than other buttons now, @tomholub let me know if that bothers your eye (mine is fine with that).
I intentionally didn't use the `issue-xxxx` in the branch name to avoid unnecessarily testing since there are no significant changes.
> Add white-space: nowrap to the Secure Compose button

- extension/js/common/api/attester.ts
- extension/js/common/rules.ts
- test/source/mock.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/google/google-data.ts
- test/source/tests/tests/setup.ts
> issue 2517 disallow domains search

- extension/chrome/settings/inbox/inbox-modules/inbox-menu-module.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.ts
> Issue 2546 auth settings

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose.ts
- test/source/browser/controllable.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
- test/source/tests/tests/compose.ts
Closes #1114 
I'm personally very excited about this feature because even though the change is small in terms of LoC, the impact could be quite big because Arabic is the 5th most popular language in the world. And people who speak Hebrew will be excited as well, Israel has the largest number of startups per capita in the world, around one startup per 1,400 people, so people out there would appreciate our effort.
You might want to announce the RTL support in release notes, blog and in the news section of `settings/index.htm`.
TODO:
> Add RTL support

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/css/cryptup.css
- test/source/tests/tests/compose.ts
Fixes #2577 
Long names and emails are handled with `text-overflow: ellispsis`:
> Align contacts list with gmail, put email under name

- extension/css/webmail.css
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
Fixes #2615 
Also fixed the vertical alignment of the Secure Reply button in Chrome:
Before | After
-|-
> Issue 2615 secure reply button handlers

- test/source/tests/tests/gmail.ts
Closes #2622 
@tomholub first of all, please give your feedback on the test. I decided to add the Gmail test to simulate the real use-case, but if you think that's not the best way, let me know.
Secondly, if the first part is alright and Gmail test is fine here, I'm struggling to get the `pgp_block.htm` frame, for some reason the `getFrame()` method can't find it and throwing the `Error: Frame not found: pgp_block.htm` exception.
> Add test for offline mode

- extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts
- extension/css/cryptup.css
Fixes #2644 
Visible filenames are limited to 100 chars. Here's the simulated example:
> Remove fixed heigth from #attachments .attachment

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/tests/gmail.ts
Connected to #2683 
Fixes the scenario described in https://github.com/FlowCrypt/flowcrypt-browser/issues/2683#issuecomment-602902847 but it will work only once:
The proper (infinite) switching between plain and secure should be done separately.
This could theoretically fix the "reply box does not always get replaced" issue, but I'm not 100% sure. @tomholub I'll need your feedback in #2683 on the initial issue is it's still happening after we merge this PR.
> Switch from plain to encrypted reply (from toolbar)

- flowcrypt-browser.code-workspace
As per https://github.com/FlowCrypt/flowcrypt-browser/pull/2712#discussion_r400281551
> Remove amatiasq.sort-imports from recommended extensions

- extension/manifest.json
This change enables very strict CSP that doesn't allow inline styles or scripts.
Not everything works with it though! (e.g. popup) but it seems like there are not many changes. I'll check out later if it's feasible to remove all inline styles, if so - I'll fix them, if not, I'll allow them but disallow everything else.
DO NOT MERGE this yet!
------------
close #2693
> Add strict Content Security Policy

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/tests/gmail.ts
The issue was in raising `keepNextStandardReplyBox` when clicking the "Reply" button to plain messages. Silly oversight by me :man_facepalming: 
Fixes #2683
> Do not raise keepNextStandardReplyBox for plain replies to plain messages

- extension/js/common/xss-safe-factory.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/tests/gmail.ts
Fixes #2720 
I recommend using `?w=1` for CR: https://github.com/FlowCrypt/flowcrypt-browser/pull/2745/files?w=1
> Do not show 'switch to encrypted reply' warning when replying to signed message

- extension/chrome/settings/modules/backup-manual-module.ts
- extension/chrome/settings/modules/backup.ts
- extension/chrome/settings/modules/change_passphrase.htm
- extension/css/cryptup.css
- test/source/tests/page-recipe/settings-page-recipe.ts
Fixes #2684 
Added this confirmation popup:
---
Also, fixed these UI details:
before: 
after:
---
before:
after:
> Add confirmation after private key has been backed up

- extension/manifest.json
Added `upgrade-insecure-requests` to CSP per discussion in https://github.com/FlowCrypt/flowcrypt-browser/issues/2691. I was glad to see we've already got `frame-ancestors` to block clickjacking, good call!
> added insecure requests upgrade directive to CSP

- .semaphore/semaphore.yml
- extension/chrome/elements/pgp_block_modules/pgp-block-error-module.ts
- test/source/mock/google/google-data.ts
- tooling/build-types.ts
I don't think there is any need to allow tags here, but if I'm wrong please let me know and we'll find a different way. This should prevent HTML injection via error messages per FLO-02-004 of the Cure53 report.
// tom
close #2770
> Sanitize error messages by removing all tags

- extension/js/common/browser/browser.ts
Use [ChildNode.remove()](https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove) for removing node, `document.body.removeChild` produces `The node to be removed is not a child of this node` exception.
Fixes #2764
> Use ChildNode.remove()

- extension/chrome/elements/backup.ts
- extension/chrome/settings/setup/setup-recover-key.ts
- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- extension/js/common/core/crypto/smime/smime-key.ts
This aligns `checkPassPhrase` with other key functions and also allows the Key object to be serialized using structured clone algorithm in Firefox.
Fixes #2804.
I've tested this in Firefox while first reproducing it. It failed on each time when setting up an already used account but if you can test it too I'd be really glad ;)
> Fix Firefox account recovery / Move `checkPassPhrase` outside of Key object

- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
To reproduce:
- Use Firefox,
- Open Secure Compose on gmail.com (*not* internal inbox),
- Send an e-mail to a key that has expiration set.
The bug is caused by Date objects arriving from another realm (extension vs gmail.com page). They are full-fledged Date objects but they are not `instanceof Date` because `Date` points to the Date constructor from current frame (gmail.com).
The fix checks the existance of the function we need (`getTime`).
This was kind of hard to debug until I found a toggle in Firefox devtools to allow debugging extensions :)
> Fix unexpected value when sending e-mail

- extension/chrome/popups/default.ts
Fixes #2854 
This is the regression from my PR https://github.com/FlowCrypt/flowcrypt-browser/pull/2714 Either I somehow skipped testing that functionality in Firefox or Firefox added something in one of the latest versions which doesn't allow `window.open` to work. Luckily, there's the fallback through the bg page.
> Fix redirectToInitSetup() for Firefox

- .vscode/launch.json
- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose.ts
- extension/css/cryptup.css
- test/source/tests/page-recipe/compose-page-recipe.ts
- test/source/tests/tests/compose.ts
Closes #2636
Hopefully the code is good now, I tried to make local drafts as close as possible to Gmail drafts so the saving/restoring/deleting processes would be the same.
Added the ability to save drafts when offline for both compose and reply use-cases.
---
Also fixed the centering of reply loader:
before | after
-|-
And also this typo:
> Add offline drafts

- extension/chrome/elements/pgp_pubkey.htm
- extension/chrome/settings/modules/contacts.htm
- extension/chrome/settings/modules/contacts.ts
- extension/js/common/xss-safe-factory.ts
- test/source/browser/controllable.ts
- test/source/tests/tests/compose.ts
S/MIME certs couldn't be imported on contacts screen due to missing libraries and internal support to display the certs.
This change adds a test to catch this scenario, fixes the underlying code and adds missing libraries.
I've also improved the naming of `needle` as it took me some time to figure out why string was not found on the page when I see it's there :)
As for #2732 this is now using `serialNumber` that is defined as:
```
hex encoded value of an ASN.1 INTEGER.
Conforming CAs should ensure serialNumber is:
- no more than 20 octets
- non-negative (prefix a '00' if your value starts with a '1' bit)
```
it looks like OpenPGP fingerprint and is displayed automatically in groups so I think this fixes #2732.
> Issue 2732: fix S/MIME import on contacts screen

- extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts
- extension/js/common/platform/xss.ts
Escapes HTML from the labelId parameter:
I'll leave the issue open for similar problems (of which I suspect there might be a few).
> escape labelId parameter for HTML

- extension/chrome/settings/setup/setup-render.ts
- extension/css/cryptup.css
- extension/css/settings.css
Fixes #2535 
Only autofocus was missing, `Enter` hit was working as expected.
Also fixed SweetAlert2's font-size for Bootstrap 3 because after upgrading deps #2105 was undone. #2105 was my mistake, the lesson to myself: never edit deps commited to the repo.
> Autofocus recover input

- extension/chrome/settings/index.htm
- extension/css/settings.css
Closes #2468 
Also, I removed the `0.7` opacity on that button, because with the opacity it was looking like `<button disabled />`
> Make the 'Renew' button accessible with kbd

- extension/css/settings.css
Fixes #2922 
The horizontal jumpiness caused by body with top margin was bothering my eye, so I pushed this one-liner bypassing the queue.
> Change #header-row's margin to padding so body won't have margins

- extension/js/common/core/att.ts
Fix #2928 
I guess this is the smallest PR in this repo :)
My knowledge of regexes wasn't enough and I asked for the help from the community: https://stackoverflow.com/q/63928569
Fortunately, the help was prompt and TIL that the `RegExp` object keeps track of the `lastIndex` where a match occurred, so on subsequent matches it will start from the last used index, instead of `0`: https://stackoverflow.com/a/1520853
> Fix webmailNamePattern regex

- extension/chrome/elements/attachment_preview.htm
- extension/js/common/browser/ui.ts
- test/source/tests/tests/settings.ts
- test/source/util/index.ts
Fixes #2950 
Google Chrome 83 began to disallow iframes from downloading unless the `allow-downloads` key is added to an iframe’s `sandbox` attributes: https://www.chromestatus.com/feature/5706745674465280
> Add allow-downloads to attachment preview iframes

- extension/chrome/elements/attachment.ts
- extension/css/cryptup.css
Fixes #2989 
Also, improved styles a bit:
@tomholub do we need a test for this fix? I was trying to add one, but for adding a test there should be some kind of going offline possibility in `GoogleData`. What do you think?
> Fix retry attachment download

- extension/js/common/core/crypto/pgp/openpgp-key.ts
Typo!
'skiped' should be 'skipped'
This is done because otherwise, the form vowel + consonant + e causes the vowel to take the long form (eg the words Skype, hope, or dine). Consider the word hop. To prevent it's past simple from being 'hoped' (which would be pronounced with the long o and means something else), it becomes hopped.
Interesting to me how these things kind of have rules, but also kind of don't!
> Update openpgp-key.ts due to typo

- extension/chrome/dev/ci_unit_test.ts
- extension/js/common/api/key-server/wkd.ts
- test/source/browser/browser-pool.ts
- test/source/mock/all-apis-mock.ts
- test/source/mock/wkd/wkd-endpoints.ts
- test/source/test.ts
- test/source/tests/browser-unit-tests/unit-Wkd.js
- test/source/tests/compose.ts
- test/source/tests/setup.ts
Closes #3003
First checks for policy file, then extracts the key and checks for email match.
Advanced method is now supported.
> Wkd now uses advanced request where possible and checks policy file

- extension/js/common/org-rules.ts
Just removes the reflected input entirely (simple solution). I tested this on Chrome, here's what it looks like:
Fixes https://github.com/FlowCrypt/flowcrypt-security/issues/63
> Remove email reflection that causes html injection vulnerability

- .vscode/launch.json
- test/source/tests/compose.ts
Fixes #3051 
This PR workarounds the puppeteer issue https://github.com/puppeteer/puppeteer/issues/6040
I subscribed to the issue, to be notified and remove this workaround when the issue is resolved and released.
> issue #3051 race condition for waitForFileChooser() fix + fixed wkd test

- extension/css/cryptup.css
Fixes #3037
Also, added custom outlines as native outline were missing in Firefox for some reason:
Also, increased the height of `#cc` and `#bcc` buttons to `24px` so it won't be too small (prev height was `17px`)
> Improve #input_from styles, add custom outline to it and #cc/#bcc buttons

- extension/chrome/elements/compose-modules/compose-pwd-or-pubkey-container-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-types.ts
- extension/css/cryptup.css
Closes #2785
Also, fixed the spinner size inside of `.recipients-inputs`, it was too big and produced jumpiness:
> Use non-numeric enum for RecipientStatus

- extension/manifest.json
Adds the following directives:
font-src (none)
manifest-src (none/self)
media-src (none)
worker-src (self)
form-action (none)
I left out `style-src` because we have a bunch of inline styles. Ideally, we should move that code to .css files and then add `style-src 'self'`. But for now I just wanted to include directives that don't break anything.
> Add additional directives to CSP

- extension/js/common/browser/ui.ts
Fixes #3151 
https://bugs.chromium.org/p/chromium/issues/detail?id=79407
> the keyCode is 10 instead of 13. a normal enter reports 13, like other browsers, only ctrl+enter is broken, and **only on windows**.
> Fix ctrl+enter for chrome on windows

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/attachment_preview.ts
- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-my-pubkey-module.ts
- extension/chrome/elements/compose-modules/compose-quote-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/passphrase.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/backup-manual-module.ts
- extension/chrome/settings/modules/change_passphrase.ts
- extension/chrome/settings/modules/decrypt.ts
- extension/chrome/settings/modules/keyserver.ts
- extension/chrome/settings/modules/my_key.ts
- extension/chrome/settings/modules/my_key_update.ts
- extension/chrome/settings/modules/my_key_user_ids.ts
- extension/chrome/settings/modules/security.ts
- extension/js/background_page/migrations.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/msg-util.ts
- extension/js/common/platform/store/global-store.ts
- extension/js/common/platform/store/key-store.ts
- extension/js/common/settings.ts
- extension/js/common/ui/key-import-ui.ts
- test/source/test.ts
- test/source/tests/unit-node.ts
- test/source/util/index.ts
Closes #1640 
// edit tom: closes #3220
> Added emails and fingerprints to PrvKeyInfo #1640

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
Fixes #3242
The issue was that `parseRenderRecipients()` called twice from `inputsBlurHandler()` and from `selectContact()`.
> Do not perform inputsBlurHandler() if #contacts li was clicked

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-my-pubkey-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/css/cryptup.css
- extension/js/common/browser/ui.ts
Closes #2763
Also, improved UX for toasts a bit to let users know when a toast will be closed and let them pause the timer (e.g. if they need more time to read and understand it) by hovering with a mouse.
> Add toast message for dropped pubkeys

- extension/css/cryptup.css
- extension/css/webmail.css
Fixes #3267
---
Also, improved styles for `div.recipients_use_encryption`, it looked a bit broken for narrow (<1200px) screens:
Before:
After:
> Set max-width: 100% for inline images in rich-text messages

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/gmail.ts
- test/source/tests/page-recipe/gmail-page-recipe.ts
Fixes #3180 
For some reason Gmail removes `msgBody` from [here](https://github.com/FlowCrypt/flowcrypt-browser/blob/88300b146314c791f610d7d84b4d4798eca3c2d2/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L486) right after we render secured message. By using `updateMsgBodyEl_DANGEROUSLY(el, 'set')`, `msgBody` is being replaced and therefore Gmail won't remove it.
> Fix rendering rich-text encrypted message right after sending it

- extension/js/common/platform/catch.ts
- extension/js/common/platform/store/contact-store.ts
Closes #2759 
Raising an exception inside 
```
search.onsuccess = Catch.try(() => {
...
})
```
block resulted in unresolved Promise, so `const raw: unknown[] = await new Promise(...` hang.
> Call reject on exception in search.onsuccess

- test/source/browser/controllable.ts
This PR fixes waitForContent in tests so that it would interpret `"[hello]"` as a string and not a regex if provided as a string.
close #3316
> issue 3316 fix waitforcontent

- package-lock.json
- package.json
- test/source/browser/controllable.ts
- test/source/test.ts
- test/source/tests/tooling/browser-recipe.ts
This PR extracts google token and deletes all drafts on the account
close #3315
> Clean drafts before each GMail test

- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- test/source/tests/compose.ts
This PR allows macOS users to send message with the expected `⌘ + Enter` shortcut
close #3355
> fix ⌘ + Enter shortcut for sending

- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
This PR reports issues with parsing inline images to track issues with unexpected `src` values of inline images (https://github.com/FlowCrypt/flowcrypt-browser/issues/3301#issuecomment-757591686)
close #3301
> Report issues with parsing inline images

- extension/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.ts
Currently XSS is mitigated like so:
https://github.com/FlowCrypt/flowcrypt-browser/blob/4e45cf6dfd80972e34ada1a7572c12e3a7276725/extension/chrome/settings/inbox/inbox.ts#L114-L118
But we don't account for HTML tags, which we don't want to render inside of subject lines.
Resolves https://github.com/FlowCrypt/flowcrypt-security/issues/100
> Escape subjects in extension inbox

- extension/js/common/browser/ui.ts
Per the [SweetAlert2 documentation](https://sweetalert2.github.io/#handling-dismissals):
> Replace deprecated sweetalert2 method onClose-> willClose

- extension/js/common/browser/browser.ts
- extension/js/common/settings.ts
This PR workarounds the Firefox limitation when `chrome.windows` isn't available in iframes. The workaround opens the settings page where user can log in with the standard workflow. 
close #3368
https://user-images.githubusercontent.com/6059356/106969963-9767ad00-6754-11eb-8f19-1198e9b16cc5.mp4
> Workaround the unavailability of chrome.windows in iframes on Firefox

- extension/js/common/api/email-provider/gmail/google-auth.ts
This PR increases the OAuth popup height so users won't have to scroll to the action button.
close #3373
Also, I decreased the popup width because that seems to be the cause of that padding from your screenshot (was not happening in my environment):
> Adjust OAuth popup size

- extension/chrome/elements/compose-modules/compose-input-module.ts
This PR allows users to remove the formatting with the keyboard to give the ability to remove styles from the pasted text.
issue #3347 (not close because I'd like to figure out the button for removing the formatting as well)
> Add the ctrl+\ shortcut for removing the formatting

- extension/js/common/api/email-provider/gmail/google-auth.ts
This PR increases the OAuth popup height so users won't have to scroll to the action button.
close #3373
@tomholub I assumed that the previous version would work in Windows as well, but after actual checking it wasn't good. Now the popup is good in both OS. Sorry about the hassle.
> Adjust OAuth popup size for Windows

- extension/js/common/core/crypto/key.ts
- extension/js/common/core/types/openpgp.d.ts
- test/source/mock/wkd/wkd-endpoints.ts
This PR makes Wkd mock return unarmored keys
close #3402
> return unarmored keys from WKD mock

- build.sh
Currently, when purify.js throws an error we get this:
>DevTools failed to load SourceMap: Could not load content for chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/purify.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
This PR adds the map so we get better errors from this.
> Include DOMPurify JS map for better error output

- extension/chrome/elements/compose-modules/compose-pwd-or-pubkey-container-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-popover-module.ts
This PR resizes reply box when showing/hiding password UI so the send btn is visible when the email address in recipients is marked grey
Addresses https://github.com/FlowCrypt/flowcrypt-browser/issues/3432#issuecomment-780109901
> Trigger resizeComposeBox() after showing/hiding password UI

- extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts
This resolves https://github.com/FlowCrypt/flowcrypt-security/issues/106 by escaping the LabelID. Here's how this looks now when I try to inject HTML:
Let me know if I'm not accounting for anything!
> Prevent HTML injection via Label ID

- extension/chrome/settings/fatal.ts
Currently, in the page /chrome/settings/fatal.htm, you can pass a stacktrace parameter. The contents of that parameter are placed into a pre tag, but if the stacktrace itself contains a closing pre tag, then anything after that will be rendered as HTML.
For example, here is the result of going to /chrome/settings/fatal.htm?stacktrace=\</pre>\<marquee>I LOVE HYPERTEXT\</marquee>:
https://user-images.githubusercontent.com/44826516/108677326-c006db00-74a6-11eb-8666-7ba9a033e2d2.mov
To resolve this, I escape the contents of the stacktrace using Xss.escape. I tested this manually and it worked in blocking the attacks presented in the report.
Another possible complaint could be that we are reflecting output at all, as someone could just put a phishing message into the stack parameter. However, …
> escape stacktraces in FlowCrypt error page

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-size-module.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
- extension/types/squire.d.ts
This PR keeps the cursor of the reply box in the viewport so users always know where they are.
close #3403
@tomholub this small issue kept me busy, and I'm still unable to come up with the perfect solution, but this one looks good enough for me. There's one visual imperfection which I'm unable to fix - the visible vertical jumpiness of the Send button when adjusting `scrollTop` of `convoRootScrollable`:
https://user-images.githubusercontent.com/6059356/109157005-3131e100-777a-11eb-8212-4c26d1e3020b.mp4
I'm not even sure if there is a solution to keep the button stable, but if there is one it would probably be complex.
> Keep the cursor of the reply box always in viewport

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose.htm
- extension/css/cryptup.css
This PR adds scrolling to the contacts popup if it's higher than the iframe (e.g. reply box), so users will always be able to see and click contacts which were previously just inaccessible.
Also, fixed this small UI inconvenience when the contacts popup was staying visible after the focus was moved to `#input_text`:
https://user-images.githubusercontent.com/6059356/109433961-a1ab5d00-7a1b-11eb-9d8f-204760420465.mp4
close #3436
> Issue 3436 contacts popup in reply box

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
Currently, here is what happens if I include an `<i>` tag in a password protected message's unencrypted intro section:
As you can see, the tag is applied and the rest of the email is italicized. Here is what happens after this PR:
> Escape HTML in password protected message intros

- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key.ts
Remove the option to copy private key to clipboard due to formatting inconveniences for users when eg pasting into word
Resolves https://github.com/FlowCrypt/flowcrypt-security/issues/115
> Disallow clipboard copy of private key

- extension/chrome/elements/compose-modules/compose-my-pubkey-module.ts
- extension/js/common/core/crypto/key.ts
This PR makes KeyInfo.email optional to avoid unexpected NPE.
close #3508
> issue 3508 keyinfo email missing

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/settings/modules/decrypt.ts
- extension/js/common/core/crypto/pgp/msg-util.ts
This PR stops returning `DecryptError.message` to avoid sending complex objects over the BrowserMsg.
close #3507
> issue 3507 fix circular structure json on decrypt error

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose-modules/formatters/signed-msg-mail-formatter.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/chrome/settings/modules/contacts.ts
- extension/js/background_page/migrations.ts
- extension/js/common/core/crypto/key.ts
- extension/js/common/platform/store/contact-store.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/platform/store/contact-store.ts
- test/source/tests/browser-unit-tests/unit-ContactStore.js
- test/source/tests/compose.ts
This PR replaces has_pgp, last_use and pubkey_last_check with hasPgp, lastUse and pubkeyLastCheck accordingly,
EXCEPT in: 1) CSS -- `has_pgp` is retained.
2) ContactV3 in migration from older version of the database.
close #3539
> refactored has_pgp, last_use and pubkey_last_check to camelCase

- README.md
- extension/chrome/dev/ci_unit_test.ts
- extension/js/common/platform/debug.ts
- test/source/platform/debug.ts
- test/source/test.ts
This PR dumps contents of `debug` IndexedDB entries.
These entries are supposed to be populated by `Debug.addMessage` calls in various test branches.
close #3482
@tomholub I tried adding this line
```
Debug.addMessage({ origText }).then(undefined, undefined);
```
inside `MsgBlockParser.detectBlocks` (as it is synchronous) and the input was successfully retrieved from the database upon test completion.
But is there a slight risk that we're trying to dump before completion of previous database transaction in this case?
> Dumping contents of 'debug' IndexedDB in browser tests #3482

- extension/js/common/platform/store/contact-store.ts
This PR adds description to `save` and `update` methods of `ContactStore`.
close #3536
> Added comments for ContactStore save and update methods

- extension/js/common/platform/store/contact-store.ts
- test/source/tests/browser-unit-tests/unit-ContactStore.js
This PR retains `name` and `lastUse` values of existing records
when `save` or `update` calls didn't have corresponding non-null values as parameters
close #3552
> Never reset Contact's name and lastUse

- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/smime/smime-key.ts
- test/source/tests/unit-node.ts
This PR allows to import a certificate in DER format
in addition to already implemented PEM and PKCS#12 PFX formats
issue #3559
> Allow to import unarmored S/MIME certificate

- extension/css/webmail.css
- extension/js/common/inject.ts
- extension/js/common/xss-safe-factory.ts
This PR places the 'Secure Compose' button under the Gmail logo and makes the styles of the 'Secure Compose' button independent from the layout. Because the layout can be different with different settings, e.g. Meet ebabled/disabled.
close #3558
**Tests**:
> Make the 'Secure Compose' button (almost) independent from Gmail styles

- flowcrypt-browser.code-workspace
We are currently using the unofficial https://github.com/hex-ci/vscode-stylelint-plus plugin because the "autofix on save" feature.
Now, the "autofix on save" feature is available in the official extension, switching to it because it's maintained by the stylelint team.
> Use official stylelint vscode plugin

- extension/chrome/elements/pgp_block.ts
- test/source/tests/decrypt.ts
Prevents directory traversal by using a more robust defense. This change uses a regex to prevent the characters `.`, `/`, and 
`\` from appearing in msgId. There was already a test for directory traversal, so I've added an additional one that tests for the workaround.
close https://github.com/FlowCrypt/flowcrypt-security/issues/134
> Prevent msgId path traversal workaround

- extension/css/cryptup.css
- extension/css/settings.css
- extension/css/webmail.css
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
This PR fixes rendering attachments with double whitespaces in their filenames.
close #3642
`innerText` is the representation and should never be used as data:
---
Also fixed some small styling issues:
1. Expired subscription badge:
Before | After
-|- 
2. Attachment filenames with special chars like `Č`:
Before | After
-|- 
3. Fixed vertical alignments of attachments (missed this one in #3639)
> Fix rendering attachments with double whitespaces in their filenames

- extension/chrome/elements/passphrase.htm
- extension/chrome/elements/passphrase.ts
- extension/chrome/settings/modules/experimental.ts
- extension/css/cryptup.css
- extension/js/common/browser/ui.ts
- extension/js/common/settings.ts
This PR provides guidance when forgot pass phrase in already set up extension.
close #3323
> Add guidance when forgot pass phrase in already set up extension

- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
- test/source/tests/decrypt.ts
- test/source/tests/gmail.ts
This PR verifies signature as soon as a pubkey is auto-loaded from lookup etc.
close #3105
> don't require user to click to verify signature on first pubkey load

- extension/css/cryptup.css
This PR allow to turn most of SVG icons into white ones.
In our codebase we mostly use SVG icons with `<img>` tags. This creates a limitation with styling, because it's not possible to affect SVG **images** like that, more details: https://stackoverflow.com/q/24933430
Thie `.icon_white` class will allow us a simple way to turn an icon into a white one: 
```html
```
Importnat note: this technique will not work with icons with a fill color of `#000`. There should be at least `1` in all of the rgb channels, in other words at least `#010101`. More details: https://css-tricks.com/solved-with-css-colorizing-svg-backgrounds/
issue https://github.com/FlowCrypt/flowcrypt-browser/pull/3663#issuecomment-846378623
- Not …
> Add .icon_white class

- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/compose.htm
- test/source/tests/compose.ts
This PR disables the 'Send Options' button when disabling the 'Send' button in order to prevent unexpected behaviors
close #3650
---
Also changed `autocomplete="false"` to `autocomplete="off"`, because `autocomplete` [is not a boolean attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautocomplete) and was not working in Chrome:
> Disable the 'Send Options' button when disabling the 'Send' button

- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/js/common/api/account-server.ts
- extension/js/common/api/account-servers/flowcrypt-com-api.ts
- extension/js/common/api/flowcrypt-website.ts
- extension/js/common/platform/store/global-store.ts
- test/source/mock/backend/backend-endpoints.ts
- test/source/tests/flaky.ts
This PR cleans up deprecated functionality.
The actual backend already returns the `url` parameter that we newly use here.
issue #3672
- Tests added or updated (mock updated to reflect changes, although from user perspective there are no changes in behavior)
> issue 3672 cleanup for web portal

- extension/chrome/elements/passphrase.ts
- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-recover-key.ts
- extension/css/cryptup.css
This PR provides guidance when user forgot pass phrase during setup.
close #681
https://user-images.githubusercontent.com/6059356/119109385-cb2bc180-ba29-11eb-8d7f-c0e1cd33fbfb.mp4
> Add guidance when forgot pass phrase during setup

- extension/chrome/elements/attachment.ts
- extension/chrome/elements/attachment_preview.ts
- extension/chrome/elements/passphrase.ts
- extension/chrome/settings/inbox/inbox.ts
- extension/chrome/settings/index.ts
- extension/chrome/settings/modules/decrypt.ts
- extension/css/cryptup.css
- extension/css/settings.css
- extension/css/webmail.css
- extension/js/common/browser/browser-msg.ts
- extension/js/common/browser/ui.ts
- extension/js/common/settings.ts
- extension/js/common/xss-safe-factory.ts
- extension/js/content_scripts/webmail/setup-webmail-content-script.ts
- test/source/tests/settings.ts
This PR removes a few instances of `#cryptup_dialog` usage and replaces them with already existed functionality of showing `<iframe>` inside SweetAlert2 modal.
close #3677
---
Also fixed the `.action_finish_session` button. It was unusable when a user has a long list of emails (the button was covered by email rows, their `z-index` is `2`):
---
Also fixed the vertical alignment in `.button`, e.g. in `decrypt.htm`:
Before | After
-|-
> Get rid of #cryptup_dialog

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
When the "Add a pubkey to email address" modal is opened, there's the `addedPubkeyDbLookupInterval` interval which calls `evaluateRecipients()`. Previously `evaluateRecipients()` was unnecessary called every second with an empty set of recipients which caused saving a draft every second.
This PR makes sure that `evaluateRecipients()` is executed once, when the contact is actually updated.
close #3688
> Do not unnecessary trigger `evaluateRecipients()` for empty set of recipients

- extension/chrome/elements/attachment_preview.htm
- extension/manifest.json
This PR This fixes image previews in Firefox, and is an alternative to the approach used in https://github.com/FlowCrypt/flowcrypt-browser/pull/3704
close #3703
- Difficult to test because we don't have Firefox tests (yet!)
> Add blob: as valid image source in extension CSP

- extension/chrome/elements/attachment_preview.htm
- extension/chrome/elements/attachment_preview.ts
- extension/css/cryptup.css
- extension/css/webmail.css
- test/source/tests/compose.ts
This PR adds filename to the top left corner of attachment preview, so users will be aware what file they are previewing.
close #3689
> Add filename to attachment preview

- .vscode/launch.json
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/tests/compose.ts
This PR makes sure that the contacts popup is not showing when it's not expected, particularly in these 2 cases:
1. Submit the recipient which isn't in contacts, e.g. hide the "no results" popup after submitting a new email address
2. Do not render contacts suggestions if focus was moved away from input meanwhile
close #3698
> Hide contacts when submit recipient

- extension/chrome/settings/modules/contacts.ts
- extension/js/common/platform/store/contact-store.ts
- test/source/platform/store/contact-store.ts
- test/source/tests/settings.ts
This PR allows to remove a pubkey from a contact (email).
When a pubkey is no longer referenced by any email, it is deleted from the store.
close #3632
> Remove pubkeys from contacts #3632

- extension/chrome/elements/compose-modules/compose-pwd-or-pubkey-container-module.ts
- extension/css/cryptup.css
This PR fixes the position of `#expiration_note` block, as well as adds comma between `.warning_nopgp` and `. warning_revoked`.
close #3716
> Issue 3716 expiration note position

- .github/dependabot.yml
- package-lock.json
- package.json
This PR reverts bootstrap dependency to 4.6.0 because v5 breaks the settings page
close #3736
Also, configured dependabot to ignore bootstrap major updates by using their recent config: https://github.blog/changelog/2021-05-21-dependabot-version-updates-can-now-ignore-major-minor-patch-releases/
> Revert bootstrap to 4.6.0

- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/modules/add_key.ts
- test/source/tests/flaky.ts
- test/source/tests/page-recipe/settings-page-recipe.ts
- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/settings.ts
This PR ensures that adding a private key obeys the  FORBID_STORING_PASS_PHRASE OrgRule
close #3756
> Apply FORBID_STORING_PASS_PHRASE OrgRule to add_key.htm frame

- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup.ts
- extension/chrome/settings/setup/setup-render.ts
This PR fixes a setup title that suggested that user should wait, when in fact user was supposed to fill out a form.
close #3779
> issue 3779 fix confusing h1 during setup

- extension/chrome/settings/modules/change_passphrase.ts
This PR doesn't prompt the user to backup after changing pass phrase when forbidden with NO_PRV_BACKUP. (before, after the prompt, it showed "backups forbidden" anyway, so the prompt was just confusing)
close #3782
> issue 3782 dont offer backup when forbidden

- extension/manifest.json
Because of how Firefox interprets the frame-src CSP directive, users on Firefox are unable to download their private keys (and probably do other things). This weakens the directive to make this functionality work for FF users.
close https://github.com/FlowCrypt/flowcrypt-browser/issues/3774
- Difficult to test because we don't have Firefox specific tests (yet! https://github.com/FlowCrypt/flowcrypt-browser/issues/3411)
> Add blob as valid frame-src to prevent Firefox key download bug

- extension/js/common/org-rules.ts
- test/source/mock/backend/backend-data.ts
- test/source/tests/setup.ts
This PR disallows attester search alltogether if one of the entries is '*'
close #3563
> Disallow attester search for all domains when * as specified #3563

- test/source/tests/gmail.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
This PR is not meant to be merged, it's the part of debugging #3785 
I don't remember where exactly, but some time ago I asked about taking screenshots from CI. I found the simple way to do that:
1. `console.log(await page.screenshot({ encoding: "base64" }))`
2. copy the output from CI log and paste it to https://codebeautify.org/base64-to-image-converter
---
As to debugging #3785 I think that `acctPassword` is not set for some reason, here's the screenshot of the state where email and password are supposed to be entered:
> debug live Gmail tests failing

- test/source/tests/gmail.ts
- test/source/tests/page-recipe/gmail-page-recipe.ts
This PR fixes the flaky gmail test by increasing the sleep timeout before checking `pageHasSecureDraft()`, sometimes in CI it takes more than 3s to load the Gmail's UI and render the secure draft.
close #3481
> Fix flaky gmail test

- extension/chrome/elements/compose.htm
Suggesting a PR to disable autocomplete on password field when creating/sending a protected message. Adding a `autocomplete='off'` attribute to input_password
> Disable password automcomplete leaks previous passwords on protected 

- extension/chrome/elements/compose.htm
- flowcrypt-browser.code-workspace
This PR fixes the HTML markup of `compose.htm` and also
close #3726
I was able to catch this issue with the help of `mkaufman.htmlhint` extension. @tomholub If you think that I should add it to `flowcrypt-browser.code-workspace`'s recommendations, let me know.
> Fix .warning_revoked

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/css/cryptup.css
This PR is a proposed solution for #3115
To clarify, I was not able to reproduce the reported issue in both browsers. Also, my assumption about what might be the cause of the user's issue was wrong (I was assuming that buttons clicks are not handled because buttons are getting hidden right before the click handler).
But, I had to come up with the solution, because the user clearly demonstrated with a video that the issue exists. 
Proposed solution: **always show cc and bcc buttons**. I personally think it is better to always show these buttons even though Gmail is not doing that (but Outlook for example always shows cc/bbc buttons), so users will always see them and be able to click them with one click. 
Another good part about UX is that keyboard users previously had cc/bcc buttons …
> [Proposal] Always show cc bcc buttons

- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/tests/unit-node.ts
This PR changes passphrase mismatch message to more evident 'INCORRECT PASSPHRASE'
close #3192
> Modified passphrase mismatch message #3192

- extension/chrome/elements/pgp_pubkey.ts
- extension/js/common/platform/store/contact-store.ts
- test/source/tests/settings.ts
This PR doesn't allow to import a revoked public key to 'emails' and 'pubkeys' still,
but automatically imports revocation info to 'revocations' store,
with an intention to protect against further possible import of an older version of the revoked key.
close #3637
> Import revocation information automatically #3637

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/gmail.ts
This PR displays the number of encrypted attachments:
close #3654 
> Display the number of encrypted attachments

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/css/cryptup.css
- extension/css/webmail.css
- test/source/tests/compose.ts
This PR prevents showing the contacts suggestion popup which was containing only "loading..." message. It was blinking and unnecessary distracting users when they are typing email addresses into the `#input_to` field:
close #3711
Also, some minor style adjustments for sweetalert2 after the latest update from #3847
> Do not bother users with the "loading..." state of contacts suggestions

- test/source/tests/gmail.ts
This PR (hopefully) fixes the flaky gmail test. Locally I'm not able to make the test fail. Last time I increased the sleep from 3 to 5 seconds, but apparently, that's not enough. Increasing to 10. In other similar places the sleep is also 10 seconds:
- https://github.com/FlowCrypt/flowcrypt-browser/blob/master/test/source/tests/gmail.ts#L181
- https://github.com/FlowCrypt/flowcrypt-browser/blob/master/test/source/tests/gmail.ts#L190
(hopefully) close #3481
> Replace flaky sleep timeouts with robust code

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/tests/compose.ts
- test/source/util/index.ts
This PR empties the contacts popup when hiding it, so it will not be shown when refocusing `#input_to`
close #3857
> Prevent showing contacts popup for empty input

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/js/common/api/account-server.ts
- extension/js/common/api/account-servers/enterprise-server.ts
- test/source/mock/fes/fes-endpoints.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/mock/lib/api.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
This PR will use fes.example.com instance instead of flowcrypt.com/api for sending password-protected messages through the web portal - when FES is available.
close #3672
- Tests added
> issue 3672 use FES for web portal when available

- extension/css/cryptup.css
This PR fixes the styles of popups in short frames so the content and the buttons fit:
close #3908
> Fix styles for popups in short frames

- extension/chrome/elements/compose.htm
This PR rephrases the popup message when sending password-protected email into a clearer one.
close #3449 // if this PR closes an issue
> improved popup message when sending password protected email

- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/tests/unit-node.ts
This PR will:
* throws an error if the (x509 and OpenPGP) keys found are more than one.
close #2799 // if this PR closes an issue
> Throw an error if keys more than one found.

- .eslintrc.js
- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-storage-module.ts
- extension/js/common/api/email-provider/sendable-msg.ts
- extension/js/common/api/shared/api-error.ts
- extension/js/common/browser/ui.ts
- extension/js/common/inject.ts
This PR will remove the toast and the reported error in the console when an invalid email was detected.
close #3932 // if this PR closes an issue
close #3557 
> Remove toast modal when invalid email is detected

- extension/chrome/elements/compose-modules/compose-attachments-module.ts
- extension/css/cryptup.css
- test/source/tests/compose.ts
This PR adds the ability to download submitted attachments back when composing encrypted emails
close #3896
> Support click back on submitted attachments

- extension/js/common/core/const.ts
This PR excludes searching backups from the Gmail trash when recovering an account.
close #3968 // if this PR closes an issue
> exclude searching for backups from Gmail trash

- .github/dependabot.yml
This PR configures dependabot not to bother about these deps:
- `iso-8859-2`, because it's ESM and ava doesn't have ESM support for now, https://github.com/FlowCrypt/flowcrypt-browser/pull/3961#issuecomment-921335748
- `openpgp`, because the upgrade isn't easy and will be done in #3324
Also, 1 PR by dependabot per time to avoid parallel CI builds, rebasing and git conflicts.
> Ask dependabot not to bother about iso-8859-2 and openpgp deps

- .semaphore/semaphore.yml
- test/source/test.ts
This PR updates Semaphore CI workflow to store debug files generated by tests as job artifact.
close #3801
> issue #3801 Store debug files as Sempahore job artifacts

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/js/background_page/migrations.ts
- extension/js/common/platform/store/global-store.ts
This PR puts all local drafts into 1 place in storage, under the `local_drafts` key. Also, it adds the migration, so users will not lose their local drafts which were saved in the old format.
close #3337
> Change the storage path for local/offline drafts

- extension/js/common/api/account-server.ts
- extension/js/common/api/account-servers/enterprise-server.ts
- extension/js/common/api/account-servers/flowcrypt-com-api.ts
- test/source/mock/fes/fes-endpoints.ts
This PR uses this endpoint https://fes.flowcrypt.com/api/v1/client-configuration?domain=flowcrypt.com (or similar depending on customer domain) to fetch client configuration (org rules) from FES, instead of the `/api/v1/account/` endpoint which was authenticated.
This is to avoid relying on a non-OIDC access token, which our customer doesn't prefer.
close #3751
- Tests updated
> issue 3751 use client-configuration endpoint on FES

- extension/js/background_page/background_page.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/platform/store/in-memory-store.ts
- extension/js/common/platform/store/passphrase-store.ts
This PR turns pass phrase session store into a more generic InMemoryStore that could be also used for storing other temporary secrets.
close #4018
> issue 4018 generic InMemoryStore

- extension/chrome/elements/compose-modules/compose-attachments-module.ts
- extension/css/webmail.css
This PR increases the limit of attachments to 50. Tested on Mac and Win, no issues with sending / encrypting / decrypting / rendering performance.
close #3940
> issue #3940 increase number of attachments to 50

- .eslintrc.js
- conf/tslint.yaml
- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/css/webmail.css
- extension/js/background_page/migrations.ts
- extension/js/common/core/msg-block-parser.ts
- extension/js/common/platform/store/global-store.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- extension/js/content_scripts/webmail/webmail.ts
- test/source/browser/controllable.ts
- test/source/tests/compose.ts
- test/source/tests/elements.ts
- test/source/tests/gmail.ts
- test/source/tests/settings.ts
- test/source/tests/unit-browser.ts
- test/source/tests/unit-node.ts
This PR allows users to create several offline compose drafts. It also takes care of migrating the existed compose offline drafts, so nothing will be lost for users.
close #3126
> issue #3126 Add support for multiple offline compose drafts

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/css/cryptup.css
This PR sets the compose window active when user is required to enter their PP
close #4039 
https://user-images.githubusercontent.com/6059356/135986885-535a95ee-b3c4-4c1e-b302-e0bc781a4b2a.mp4
> issue #4039 Set compose window active when PP is required

- .semaphore/semaphore.yml
- test/source/browser/test-urls.ts
- test/source/tests/gmail.ts
Because it's not possible to make Gmail tests robust when running them in parallel, this PR changes the SemaphoreCI config so that Gmail tests will run only for:
- `master` branch
- branches that contain `live-test` or `gmail-test` in them
Also, stabilized Gmail tests so all of them now pass without retries:
```
✔ mail.google.com/chat (34.6s)
ℹ run time: 28s
✔ mail.google.com - setup prompt notif + hides when close clicked + reappears + setup link opens settings (49.4s)
ℹ run time: 43s
✔ mail.google.com - plain reply to encrypted and signed messages (1m 52.6s)
ℹ run time: 57s
✔ mail.google.com - send rich-text encrypted message (1m 52.7s)
ℹ run time: 72s
✔ mail.google.com - success notif after setup, click hides it, does not re-appear + offers to reauth (2m 9.8s)
ℹ run time: 123s
✔ …
```
> Run Gmail tests only for master and branches that contain `live-test` or `gmail-test` + re-enable and fix flaky test

- extension/chrome/elements/compose-modules/compose-input-module.ts
- extension/chrome/elements/compose-modules/compose-quote-module.ts
- extension/chrome/elements/compose.htm
- extension/chrome/elements/pgp_block_modules/pgp-block-quote-module.ts
- extension/css/cryptup.css
- extension/js/common/core/common.ts
- extension/js/common/platform/xss.ts
- package-lock.json
- package.json
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
- test/source/tests/gmail.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
- test/source/tests/setup.ts
This PR:
- allows leading and trailing whitespaces in general (users should be able to start and end their messages with spaces or tabs, e.g. for formatting purposes)
- preserves leading tabs when pasting tab-intended text (related PR in Squire repo https://github.com/neilj/Squire/pull/417)
close #3925
- Tests are added
> issue #3925 Allow leading whitespaces generally (do not trim messages) + allow tabs when pasting tab-intended text

- test/source/tests/compose.ts
This PR replaces the email `test-wkd@metacode.biz` which has the expired key with `demo@flowcrypt.com`
close #4085
> Use demo@flowcrypt.com instead of test-wkd@metacode.biz in tests

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-render-module.ts
- extension/chrome/elements/compose-modules/compose-size-module.ts
- extension/chrome/settings/modules/change_passphrase.ts
- extension/js/common/ui/key-import-ui.ts
This PR makes sure that the app is reacting to all input changes - with the keyboard or with the mouse (e.g. right click -> paste)
close #4076
> Change the 'keyup' events handlers to 'input' because text content can be changed with the mouse

- extension/chrome/elements/add_pubkey.htm
- extension/chrome/elements/pgp_pubkey.htm
- extension/chrome/settings/modules/contacts.htm
- extension/chrome/settings/modules/contacts.ts
- extension/css/cryptup.css
This PR adds an orange warning when manually importing public keys. It also fixes the broken layout of `chrome/elements/pgp_pubkey.htm`
close #4097
close #4104
> issue #4097 add warning when manually importing public keys

- extension/chrome/elements/compose-modules/compose-render-module.ts
- test/source/tests/gmail.ts
This PR fixes the vertical resizing of the compose window in Firefox after entering passphrase for a draft.
close #4139
Also, outside of the scope of the issue, I fixed live gmail tests as they are failing on the `master` branch now.
> Fix resizing draft compose window after entering passphrase in Firefox

- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/js/common/inject.ts
- package-lock.json
- package.json
- test/source/tests/gmail.ts
This PR puts the end pp session in front of google chat popups on hover to improve UX:
https://user-images.githubusercontent.com/6059356/143932383-edb00816-67c1-4d18-833e-d8e773266185.mp4
close #4078
---
Also fixed a small issue with the encrypted subject's look:
before | after
-|-
---
Also bumped puppeteer to [v12.0.1](https://github.com/puppeteer/puppeteer/releases/tag/v12.0.1) as live gmail tests were failing with v12.0.0 because of [this issue](https://github.com/puppeteer/puppeteer/issues/7805): https://flowcrypt.semaphoreci.com/jobs/8c3c44f4-1ffc-412c-b73c-62b435a48d2a + fixed a flaky test with weird puppeteer issue typing 'ompose draftc' instead of 'compose draft' …
> issue #4078 End passphrase button z index run gmail tests

- extension/chrome/elements/compose-modules/compose-draft-module.ts
This PR makes secure compose popup active when draft is waiting for pass phrase, previously is wasn't become active on open and looked faded (as default inactive popup).
Also, the buttons are now more obvious to click:
close #4081
> issue #4081 Make secure compose popup active when draft is waiting for pass phrase

- extension/css/webmail.css
- extension/js/common/inject.ts
- extension/manifest.json
This PR converts the FlowCrypt logo image inside the Secure Compose button inline for the sake of compatibility with [Virtru Email Protection](https://chrome.google.com/webstore/detail/virtru-email-protection/nemmanchfojaehgkbgcfmdiidbopakpp/related?hl=en)
close #4098
Also, because Gmail changed the layout a bit, fixed the detection when the Secure Compose button should have smaller height (issue #4063)
> issue #4098 Make the FlowCrypt logo in "Secure Compose" button inline

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
This PR fixes the vertical offset for contacts list for CC and BCC fields as well as for TO field when `#input-from` is visible
close #4105
> issue #4105 Fix vertical offset for contacts list

- extension/chrome/elements/compose-modules/compose-send-btn-popover-module.ts
- test/source/tests/compose.ts
This PR turns off only the handler for send btn popover, not all click handlers on body.
close #4087
> issue #4087 Do dot turn off all click handlers on body when closing send btn popover

- extension/chrome/elements/compose-modules/compose-my-pubkey-module.ts
- extension/css/cryptup.css
- extension/js/common/lang.ts
This PR makes the title for the 'Attach Pubkey' button a bit more detailed. Also, it adds the `cursor: pointer` to buttons to let users know that they are clickable.
close #4073
> issue #4073 Better title for the 'Attach Pubkey' button

- extension/js/common/inject.ts
This PR checks if the new Gmail look is enabled and if so the Secure Compose button will be injected into another `<div>`.
Here's the markup of the new Gmail look:
close #4099
- Difficult to test, I'm still unable to turn on that new look for myself and I can't turn on this new look in the tests. The markup above is from the screensharing session with a customer.
> Fix injecting the Secure Compose button on the new Gmail look

- extension/chrome/elements/pgp_pubkey.htm
- extension/chrome/elements/pgp_pubkey.ts
- extension/css/cryptup.css
- test/source/tests/settings.ts
This PR hides the import warning for unusable keys.
close #4168
> issue #4168 Do not show import warning for unusable keys

- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-signature-module.ts
- test/source/mock/attester/attester-endpoints.ts
- test/source/tests/decrypt.ts
This PR renders text prior to signature
close #4197  // if this PR closes an issue
> render text prior to signature verification

- extension/js/background_page/background_page.ts
- extension/js/background_page/migrations.ts
- extension/js/common/core/common.ts
- extension/js/common/platform/store/contact-store.ts
- extension/js/common/platform/store/global-store.ts
- test/source/tests/browser-unit-tests/unit-ContactStore.js
- test/source/tests/unit-node.ts
This PR extends each entry in searchable till the end of the original full string,
making it possible to search whole emails etc.
close #3735 
> extend searchable entries till the end of email/name

- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
This PR will fix HTML injection in the subject name when rendering a rich-text document and will escape only the subject name where we shouldn't expect HTML tags.
close #4239 // if this PR closes an issue
> Issue 4239 fix HTML Injection

- extension/js/common/core/buf.ts
- extension/js/common/core/crypto/pgp/msg-util.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/tests/unit-node.ts
This PR extracts signer fingerprints from signature subpackets to `VerifyRes`
close #3873
> added signerFingerprints to VerifyRes

- extension/chrome/elements/pgp_block.ts
- extension/chrome/settings/modules/experimental.ts
- extension/js/background_page/background_page.ts
- extension/js/common/api/account-servers/enterprise-server.ts
- extension/js/common/api/email-provider/gmail/google-auth.ts
- extension/js/common/browser/browser-msg.ts
- extension/js/common/core/const.ts
- extension/js/common/core/expiration-cache.ts
- extension/js/common/platform/store/acct-store.ts
- extension/js/common/platform/store/in-memory-store.ts
- extension/js/content_scripts/webmail/webmail.ts
- test/source/tests/tooling/browser-recipe.ts
This PR store `google_token_access` in memory, correctly managing expiration
close #4196
- Tests added or updated (google access toke extraction is updated)
> store google_token_access in memory

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/mock/google/live-gmail-test-emails/[ci.test] simple attachments trigger processAttachments (KtbxLvHkSWwbVHxgCbWNvXVKGjFgqMbGQq).eml
- test/source/tests/gmail.ts
This PR only hides "download all" or "save to Google Drive" buttons when at least one attachment is recognized as encrypted (or in any other way special to OpenPGP)
close #4247
> simple attachments preserve 'download all' button

- extension/js/common/browser/browser-msg.ts
This PR makes the background page bounce incoming broadcast messages back to the sender tab, thus allowing propagation to all its frames in Firefox
close #4072
- Difficult to test (need Firefox)
> Bounce broadcast messages back to tab in Firefox

- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- extension/js/common/core/types/openpgp.d.ts
- test/source/tests/unit-node.ts
This PR validates all private key packets on `decrypt` or on `parse` (if they are unencrypted)
close #0000 // if this PR closes an issue
> validate private keys

- extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-error-module.ts
- test/source/tests/page-recipe/inbox-page-recipe.ts
This PR displays "pass phrase needed" badge in the pgp_block when the message wasn't decrypted because of missing pass phrase
close #4266
> rephrase error badge when pass phrase is needed

- extension/css/webmail.css
- extension/js/common/xss-safe-factory.ts
This PR will adjust the secure compose button UI for the new Gmail UI.
proposed changes looks like:
close https://github.com/FlowCrypt/flowcrypt-browser/issues/4308
> add adjustment on secure compose button for new Gmail UI

- extension/js/common/xss-safe-factory.ts
This PR will add a tooltip `Secure Compose` on FlowCrypt secure compose button.
<video src=https://user-images.githubusercontent.com/46025304/157205427-e216c9da-db6a-4520-a949-01236c9751b2.mov>
close https://github.com/FlowCrypt/flowcrypt-browser/issues/4323 
> add "Secure Compose" tooltip on FlowCrypt secure compose button

- extension/chrome/elements/add_pubkey.ts
- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- extension/chrome/elements/compose-modules/compose-send-btn-module.ts
- extension/chrome/elements/pgp_pubkey.ts
- extension/js/common/platform/store/contact-store.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/tests/browser-unit-tests/unit-ContactStore.js
This PR refactors code to use `ContactStore.getOneWithAllPubkeys()` instead of `ContactStore.get()`
close #3905 
> issue #3905 Refactor to use ContactStore.getOneWithAllPubkeys() instead of .get() 

- extension/chrome/settings/index.ts
- extension/chrome/settings/setup.htm
- extension/js/common/core/crypto/key.ts
- extension/js/common/core/crypto/pgp/msg-util.ts
- extension/js/common/core/crypto/smime/smime-key.ts
- extension/js/common/ui/key-import-ui.ts
- test/source/tests/unit-node.ts
This PR changes "key type" into "key family".
close #4376
> Change key type into key family

- test/source/tests/compose.ts
- test/source/tests/flaky.ts
- test/source/tests/settings.ts
This PR adds exact file names when using `awaitDownloadTriggeredByClicking()` in tests
close #4387
> issue #4387 expect exact file names when using awaitDownloadTriggeredByClicking() in tests

- test/source/browser/controllable.ts
- test/source/tests/page-recipe/settings-page-recipe.ts
- tooling/build-types-and-manifests.ts
This PR is a followup from #4419 - I missed content scripts in that PR.
close #4452
- Difficult to test - would have to do our live Gmail tests on an enterprise build instead of regular. I suppose that's doable, but we may need to consider doing it both on enterprise and on regular. This functionality is expected to eventually be the same on both so it doesn't seem worth testing this in interim period. (Live gmail tests are very flakey)
> issue 4452 also use gmail.googleapis.com in enterprise content script

- extension/chrome/settings/setup/setup-key-manager-autogen.ts
- extension/js/common/api/key-server/key-manager.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/compose.ts
- test/source/tests/setup.ts
This PR renamed PUT /v1/end-user/key-pairs field
close #4513 // if this PR closes an issue
> #4513 fix: PUT rename /v1/end-user/key-pairs field

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
- test/source/tests/compose.ts
This PR re-evaluates pwd prompt when updating of public key in another frame
close #4504 // if this PR closes an issue
> #4504 Fix: updating of public key in another frame should also re-evaluate pwd prompt

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/mock/google/live-gmail-test-emails/Plain message triggering a smart reply (FMfcgzGpHHKCrKRLptBSNwkpMxzkdcQc).eml
- test/source/tests/gmail.ts
This PR will make smart replies available for non-encrypted messages
screenshots:
(before)
(after)
close #4549 // if this PR closes an issue
- Tests will be added later
> make smart replies available for non-encrypted messages

- test/source/tests/page-recipe/setup-page-recipe.ts
- test/source/tests/setup.ts
This PR allows an expired key in `manualEnter` test recipe,
fixing the broken test `setup - import key - two e-mails on the screen`
- Tests updated
> Allow expired key in manualEnter recipe

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- test/source/tests/compose.ts
This PR fixes `replyInfoDiv` format. It was sending `{email: string, name: string}` instead of `string`.
close #4348
- I decided not to test this since I'd like to send out update soon and it's not easy to test. I've refactored the code to make it easier to notice this regression in PR code reviews by adding `type ReplyInfoRaw` which must remain stable to work with FES UI. With this in place, the original problem would have been noticed and corrected during development or review.
> issue 4348 only send sender email in replyInfoDiv

- extension/chrome/elements/compose-modules/compose-footer-module.ts
This PR escapes a hyphen character. It is to correct the regex to match a character `-` instead of a range between `*` to `_`
close #4674 
> Escape hyphen character

- test/source/mock/backend/backend-data.ts
- test/source/tests/setup.ts
This PR fixed `passphrase should expire in in_memory_pass_phrase_session_length` mock test issue
close #4700 // if this PR closes an issue
> #4700 Fix mock test

- test/source/tests/compose.ts
This PR fixed `compose - pass phrase dialog - dialog cancel` mock test
> Fix: compose - pass phrase dialog - dialog cancel mock test

- extension/chrome/settings/modules/security.htm
- extension/chrome/settings/modules/security.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/settings.ts
- test/source/tests/tooling/browser-recipe.ts
This PR fixes issues on #4739 by hiding the password messages' expiry settings for FES users.
close #4739  // if this PR closes an issue
> Hide password messages' expiry settings for FES users

- test/source/tests/decrypt.ts
- test/source/tests/flaky.ts
This PR moved ` decrypt - entering pass phrase should unlock all keys that match the pass phrase` to flaky
close #4776 // if this PR closes an issue
> #4776 fix: Move` decrypt - entering pass phrase should unlock all keys that match the pass phrase` to flaky

- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
This PR move `compose - test compose after reconnect` test to flaky group
close #4813 // if this PR closes an issue
> #4813 fix: move `compose - test compose after reconnect` test to flaky group

- extension/chrome/elements/compose-modules/compose-err-module.ts
- extension/chrome/elements/compose-modules/compose-pwd-or-pubkey-container-module.ts
- extension/chrome/elements/compose-modules/formatters/general-mail-formatter.ts
- extension/chrome/elements/compose.htm
- extension/chrome/elements/compose.ts
- extension/css/cryptup.css
- extension/js/common/client-configuration.ts
- extension/js/common/lang.ts
- test/source/mock/backend/backend-data.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/compose.ts
This PR introduces DISABLE_FLOWCRYPT_HOSTED_PASSWORD_MESSAGES client configuration flag.
When this flag is present & recipient pub keys are missing & don't use FES, treat like password protected message feature is not there.
close #4771 // if this PR closes an issue
> #4771 Better ux for disabled password messages

- extension/chrome/elements/backup.htm
- extension/chrome/elements/passphrase.htm
- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/modules/change_passphrase.htm
- extension/chrome/settings/modules/compatibility.htm
- extension/chrome/settings/modules/my_key.htm
- extension/chrome/settings/modules/my_key_update.htm
- extension/chrome/settings/modules/security.htm
- extension/chrome/settings/modules/test_passphrase.htm
- extension/chrome/settings/setup.htm
This PR changes the passphrase length limit to `256` which also fixes the app crash when a user pastes a long string on the passphrase field where the extension evaluates the passphrase complexity.
close #4835 
> change passphrase length limit

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- extension/js/common/api/account-server.ts
- extension/js/common/api/account-servers/enterprise-server.ts
- test/source/mock/fes/fes-endpoints.ts
- test/source/mock/google/google-data.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
This PR reverts change of behavior introduced in issue https://github.com/FlowCrypt/flowcrypt-browser/issues/4348 without reverting all of the general code / refactoring changes. Various parts of the code can still handle sending more than one actual message per "send button" click, which may still come handy, with a note to refactor it away in year 2024 if it remains unused.
close #4870
close #4702 - I also fixed this as a byproduct. Since it's a single message sent to pubkey recipients and to password link recipients, as before, it does make sense again to attach the files to it (since we only have to upload them once, not once per recipient), which is what I've done.
- Tests added or updated (WIP) …
> Issue 4870 revert individual fes msgs

- extension/chrome/elements/compose-modules/compose-draft-module.ts
- extension/js/common/core/crypto/pgp/pgp-armor.ts
- extension/js/content_scripts/webmail/gmail-element-replacer.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/gmail.ts
This PR correctly parses draft saved from iOS app and get rid of tags
close #4868 // if this PR closes an issue
- Couldn't add test (Need to add live test for parsing existing drafts. However, implementing a live test would present a stability issue as drafts cannot be exported and may be discarded prior to the start of the live test or whatsoever reason)
> #4868 fix: correctly parse draft saved from iOS app and get rid of tags

- extension/chrome/elements/attachment.ts
- test/source/mock/google/exported-messages/message-export-18610f7f4ae8da0a.json
- test/source/tests/decrypt.ts
- test/source/tests/settings.ts
This PR do not strip .gpg or .pgp extension when downloading original file
close #4859 // if this PR closes an issue
> #4859 feat: do not strip .gpg or .pgp extension when downloading original file

- scripts/build.sh
This PR fixes unnecessary `.bak` files after extension build
close #4940
> #4940 Update build script to not produce .bak files

- extension/js/common/api/account-servers/external-service.ts
This PR <what does it do and why?>
close #4844 // if this PR closes an issue
- Difficult to test (Hard/impossible to reproduce in semaphoreci)
> #4844 feat: renew id token when expires

- extension/js/common/core/common.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- extension/js/common/ui/key-import-ui.ts
- test/source/tests/unit-node.ts
This PR employs user verification mechanisms from OpenPGP v5
On diagnostics page an unverified user id looks like this
As for Key parsing, all unverified user ids are omitted from the `Key.identities` property.
close #4588
> Employ user verification mechanisms from OpenPGP v5

- extension/js/common/core/crypto/pgp/openpgp-key.ts
- extension/js/common/core/crypto/pgp/pgp-armor.ts
- package-lock.json
- package.json
This PR upgrades OpenPGP.js to 5.6.0, some patches are no longer needed and are removed
> upgrade OpenPGP to 5.6.0, remove patches

- extension/js/background_page/background_page.htm
This PR removes sweetalert reference from background page.
Was it ever used? Is it possible to use it?
(as part of research for issue #4866)
> removed reference to Swal from background page

- extension/js/common/core/crypto/key.ts
This PR updates the compatibility test by adding the `usableForEncryption` and `usableForSigning` properties to the output results.
close #4996 
> Add checks for key encryption and signing usability

- extension/css/webmail.css
- extension/js/common/xss-safe-factory.ts
This PR makes secure compose button clickable for text too
close #4980 // if this PR closes an issue
> #4980 feat: make secure compose button clickable for text too

- extension/chrome/settings/modules/add_key.htm
- extension/chrome/settings/modules/compatibility.htm
- extension/chrome/settings/modules/my_key_update.htm
- extension/chrome/settings/setup.htm
This PR updates the ASCII armored private key length limit to 80kb from 20kb.
close #5014 
> issue #5014 update ascii armored private key length limit to 80kb

- test/source/test.ts
- test/source/tests/compose.ts
- test/source/tests/gmail.ts
This PR adjusts timeouts
close #5035
close #5038
- Internal test changes
> Better timeout management in live tests

- test/source/browser/controllable.ts
- test/source/tests/page-recipe/oauth-page-recipe.ts
This PR tries to fix Javascript world error
> Try to fix google chat live test

- test/source/browser/controllable.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/compose.ts
- test/source/tests/page-recipe/compose-page-recipe.ts
This PR first sets up sending options, then types the message, invoking draft save.
close #5052
---------------------------------
- internal test refactoring
> Configure sending options prior typing in ComposePageRecipe

- extension/chrome/settings/modules/security.htm
- extension/chrome/settings/modules/security.ts
- test/source/tests/settings.ts
This PR removes the password message custom expiry options.
close #5003
> issue #5003 remove password messages custom expiry options

- extension/js/common/api/email-provider/gmail/gmail.ts
- test/source/mock/key-manager/key-manager-endpoints.ts
- test/source/tests/settings.ts
This PR fixes processing logic in searching sent messages for contacts by query
close #5075 
close #5085 (also removed test interference)
- Not worth testing?
> fixed guess contacts from sent messages query to omit top-level domain

- extension/js/common/core/crypto/pgp/openpgp-key.ts
This PR adds the primary key's bit size information on the compatibility test page result.
close #5093 
> issue #5093 Add primary key bit size info on compatibility test page

- extension/chrome/elements/attachment.ts
- test/source/mock/google/exported-messages/message-export-187cfc92db548a0c.json
- test/source/tests/decrypt.ts
This PR adds a warning modal when downloading unencrypted file attachments on the FlowCrypt web extension page.
close #4862
> issue #4862 add warning modal when downloading unencrypted attachment

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
This PR disables contacts search when pasting long string
close #5169 // if this PR closes an issue
> #5169 fix: disable contacts search when pasting long string

- .github/dependabot.yml
- package-lock.json
- package.json
This PR updates puppeteer to 20.4.0 and removes dependabot version lock
> Update puppeteer to 20.4.0

- extension/css/webmail.css
- extension/js/common/platform/xss.ts
This PR allows the spinner image to be visible on gmail page
(actually allows hrefs to extension's resources)
close #5196
- Not worth testing?
> allow spinner image on gmail page

- extension/chrome/settings/modules/compatibility.htm
- extension/chrome/settings/modules/compatibility.ts
This PR Adds a public key lookup in the compatibility test extension page.
close #5211
Screenshots:
> issue #5211 Add public key lookup in compatibility test page

- extension/chrome/settings/setup.htm
- extension/chrome/settings/setup/setup-render.ts
This PR hides `also submit the same pubkey for` label when list is empty
close #5229 // if this PR closes an issue
> #5229 fix: hide "also submit the same pubkey for" label when list is empty

- .semaphore/semaphore.yml
This PR requests `ubuntu2004` for Semaphore CI
close #5225
- Does not need tests (internal CI changes)
> use Ubuntu 20.04 in Semaphore CI

- .prettierrc
This PR explicitly sets the previous `trailingComma` prettier's settings
Default value changed from `es5` to `all` in `prettier v3.0.0`
I think we should explicitly set the older value to avoid unnecessary updates
- Does not need tests (refactor only)
> restore trailingComma setting

- extension/chrome/dev/ci_unit_test.ts
- extension/js/common/platform/catch.ts
- test/source/tests/browser-unit-tests/unit-Catch.js
- test/source/tests/unit-browser.ts
This PR strips query strings on reported errors.
close #5282 
> #5282 Strip query strings on error reports

- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-attachments-module.ts
- test/source/tests/settings.ts
This PR adds check if attachment is decrypted before trying to download it, to fix error message which appeared when extension tried to decrypt already decrypted attachment.
close #5340
> #5340 Check if attachment is decrypted before downloading

- extension/js/common/browser/browser-msg.ts
- test/source/browser/controllable.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/tests/gmail.ts
- test/source/tests/settings.ts
- test/source/tests/setup.ts
This PR checks iframe origin before sending message with `postMessage`
close #5367
> #5367 Add origin check for postMessage

- extension/chrome/elements/attachment_preview.ts
- test/source/tests/settings.ts
This PR fixes corrupted PDF files when they're downloaded from preview page.
close #5408
> #5408 Fix broken PDF files when downloading from preview page

- extension/chrome/elements/compose-modules/compose-footer-module.ts
- test/source/mock/google/google-endpoints.ts
- test/source/tests/compose.ts
This PR fixes extra lines added to user signatures
before:
after:
close #5354
> #5354 Fix extra lines added to user signatures

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
This PR fixed `Secure reply` button not inserted for non-English Gmail UI issue
close #5428 // if this PR closes an issue
- Difficult to test (Hard to simulate gmail language change)
> #5428 Fix: "Secure reply" button not inserted for non-English Gmail UI

- extension/chrome/settings/modules/contacts.ts
- extension/css/cryptup.css
This PR addresses a minor UI issue where the expanded public key details in 'contacts' do not collapse when clicking the contact email header.
<video src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/5034c8bc-afa2-469f-b49a-fe712bea5d65" width="50%">
close #5513 
> #5513 Fixed uncollapsible contact's public key details UI

- extension/js/content_scripts/webmail/gmail-element-replacer.ts
This PR adds additional check before fetching encrypted message attachment to fix `Attachment bytes already set` error
close #5570
- Difficult to test (explain why) - difficult to reproduce in test environment
> #5570 Additional check before encrypted message attachment fetch

- extension/js/common/api/shared/api.ts
This PR improves handling of empty API response (usually happens on `DELETE` requests)
close #5601
- Difficult to test (explain why) - initial error doesn't affect functionality, it's just printed to console
> #5601 Fix empty API response handling

- extension/js/common/core/attachment.ts
This PR fixes decryption errors that occur on plain emails with ambiguous noname files with `multipart/mixed` email attachments.
close #5629 
- Difficult to test - The user just received the email, so I think it's something we can't ask to be part of the test. Additionally, I'm not sure how to generate an email with such an attachment. I checked if I can trim down the sensitive part from the noname file, but I think it's not possible and can't be done easily. This can be manually tested through user confirmation, though it works fine for me with the changes in this PR.
> #5629 Fix decryption error for ambiguous noname file with multipart/mixed email attachment.

- extension/chrome/elements/compose.htm
This PR replaces "email password" with "message password" in the Secure Compose window
close #5707
Before
After
> #5707 Replace "email password" with "message password" in the Secure Compose window

- extension/chrome/settings/setup.ts
- extension/js/common/platform/catch.ts
- test/source/tests/compose.ts
- test/source/tests/flaky.ts
- test/source/tests/setup.ts
This PR fixes id token fetch for sending error reports from content script.
\+ replaces `{ line: 0, col: 0 }` with `{ line: 1, col: 1}` for reports with unknown error location (as backend expects positive number, and throws error when line or col is 0)
close #5715
- Tests will be added later (https://github.com/FlowCrypt/flowcrypt-browser/issues/5718)
> #5715 Fix id token fetch for exception reports

- extension/chrome/elements/compose-modules/compose-input-module.ts
This PR fixed rich text image paste issue (Ctrl+C, Ctrl+V)
close #5600 // if this PR closes an issue
- Difficult to test (Hard to simulate in CI mode)
> #5600 Fix: rich text image paste issue

- .github/workflows/ossar-analysis.yml
This PR updates the ossar-analysis.yml file in `.github/workflows/` by updating the github action to its most recent version.
Reference: https://github.com/FlowCrypt/flowcrypt-browser/new/master?filename=.github%2Fworkflows%2Fossar.yml&workflow_template=code-scanning%2Fossar
close #5681 
> #5681 Update ossar-analysis.yml

- extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/core/common.ts
This PR added promise with limit logic to prevent 429 errors
close #5697 // if this PR closes an issue
> #5697 Feat: added promise with limit logic

- extension/chrome/elements/compose-modules/compose-input-module.ts
This PR adds check ensuring that rich-text is enable before ever removing rich text formatting. This solves the issue of having a prepended newlines when typing, for example, "Hello<kbd>Enter</kbd>World" where it produces 
```
World
Hello
```
in the `contenteditable.div` in the master branch.
To test this manually:
1.) Open Gmail with FlowCrypt browser extension installed and configured.
2.) Send you're self a signed message email.
3.) Reply to your own signed message email.  (*The bug appears at this point on "master" branch but not here.*) 
4.) Type "Hello<kbd>Enter</kbd>World" and it will produce output on `contenteditable.div` correctly with:
```
Hello
World
```
instead of the bugged version:
```
World
Hello
```
close #5599 
**Tests** _(delete all …
> #5599 Add checks if rich-text option is enabled before removing support

- extension/js/common/core/crypto/pgp/openpgp-key.ts
This PR improves the case where sending an empty signed message using FlowCrypt returns unhandled error. This is due to `createCleartextMessage()` not accepting empty message. So passing a newline that would serve as empty message would satify the condition when user choose to send blank signed email when asked by the FlowCrypt browser extension. 
close #5730
> #5730 Fix error when sending blank signed message

- extension/js/common/platform/catch.ts
This PR implemented feature to group similar error reports
close #5736 // if this PR closes an issue
> #5736 Group similar error reports

- extension/js/common/platform/catch.ts
This PR makes `environment` string shorter to be valid for `log-collector/exception` endpoint
close #5764
> #5764 Fix long ‘environment’ string

- extension/js/content_scripts/webmail/generic/setup-webmail-content-script.ts
This PR fixed vscode errors in content script
close #5746 // if this PR closes an issue
> #5746 Fix: vscode errors in content script

- tooling/build-types-and-manifests.ts
This PR removes `background.service_worker` for Firefox's manifest.json build process to remove such warning for unknown property `service_worker` for Manifest V2.
close #5780
> #5780 Remove service_worker for firefox's manifest.json build process

- extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts
- extension/js/common/api/email-provider/gmail/gmail.ts
- extension/js/common/api/shared/api-error.ts
This PR added timeout before next retry for 429 error
close #5697 // if this PR closes an issue
> #5697 Added timeout before next retry for 429 error

- extension/js/common/browser/browser-msg.ts
This PR fixed `unchecked runtime.lastError A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received` issue
close #5433 // if this PR closes an issue
> #5433 Fix: Unchecked runtime.lastError

- extension/js/service_worker/inject.ts
This PR removed chrome.tabs.onUpdated listener in firefox
close #5831 // if this PR closes an issue
> #5831 Remove chrome.tabs.onUpdated listener in firefox

- extension/js/common/message-renderer.ts
- extension/js/content_scripts/webmail/gmail/gmail-element-replacer.ts
This PR moved deleteExpired logic to messageRenderer and perform once per minute instead of every seconds
close #5830// if this PR closes an issue
> #5830 Move deleteExpired logic to messageRenderer and perform once per minute instead of every seconds

- extension/chrome/elements/compose-modules/compose-input-module.ts
- test/source/tests/compose.ts
This PR fixes squire initialization for secure compose message box where newlines gets injected above the current line when `Enter` is pressed.
close #5838 
> #5838 Added checks for RichText() before initializing squire in Secure Reply message box

- extension/js/common/platform/store/global-store.ts
- extension/js/common/settings.ts
This PR updates the data from `GlobalStore` storage making it syncronized when accounts from sessionStorage is removed. This update helps determining unconnected accounts in an event of account reset. 
close #5797 
> Reduce GlobalStore accounts in addition to sessionStorage removal

- extension/chrome/elements/pgp_block.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-quote-module.ts
- extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts
- extension/css/cryptup.css
- extension/js/common/core/crypto/key.ts
- extension/js/common/lang.ts
- extension/js/common/message-renderer.ts
- extension/js/common/render-interface.ts
- extension/js/common/render-message.ts
- extension/js/common/render-relay.ts
- test/source/tests/decrypt.ts
This PR implemented feature to display warning for incorrect pgp checksum
close #5868 // if this PR closes an issue
> #5868 Display warning for incorrect pgp checksum

- extension/js/common/api/shared/api.ts
This PR fixed failed to execute json on response error in console on message send 
close #5886 // if this PR closes an issue
- Difficult to test (Can't simulate this in CI environment)
- 
> #5886 Fix: failed to execute json on response error in console on message send

- extension/chrome/settings/modules/my_key.htm
- test/source/tests/flaky.ts
This PR adds a tests for checking shareable public key on `my_keys.htm` on FlowCrypt Settings -> Public Key.
close #4618 
> #4618 Add tests for checking shareable public key

- extension/chrome/elements/pgp_pubkey.htm
- extension/chrome/elements/pgp_pubkey.ts
- extension/css/cryptup.css
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- test/source/tests/settings.ts
This PR implemented fix to show clearer error message why key is not usable
close #5032 // if this PR closes an issue
> #5032 Show clearer error message why key is not usable

- extension/chrome/elements/compose-modules/formatters/encrypted-mail-msg-formatter.ts
- test/source/mock/google/strategies/send-message-strategy.ts
- test/source/tests/compose.ts
This PR adds encrypted attachment to password protected messages so that attachment can be seen in password protected messages.
close #5913 // if this PR closes an issue
close #4702 // if this PR closes an issue
- Difficult to test(The current mock Gmail environment doesn't support decrypting sent messages. In a live Gmail test, we would need to use a real non-public key email recipient, which could be inconvenient as it requires sending actual messages to that recipient.)
> #5913 Add encrypted attachment to password protected message

- .github/dependabot.yml
- extension/changelog.txt
- package-lock.json
- package.json
- tooling/release-firefox-latest-update.json
This PR updates version to 8.5.9 and adds changelog + sticks with `web-ext` v7, as v8 doesn't support node16 used on our deploy infrastructure.
> Release 8.5.9

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
This PR fixed cc and bcc ui issue
close #5020 // if this PR closes an issue
> #5020 Fix: cc and bcc ui issue

- extension/chrome/elements/compose-modules/compose-recipients-module.ts
This PR fixed reply box padding issue caused by https://github.com/FlowCrypt/flowcrypt-browser/pull/5932
close #5935 // if this PR closes an issue
> #5935 Fix: Reply box padding issue

- extension/js/common/platform/store/global-store.ts
- extension/js/service_worker/migrations.ts
This PR migrates StoredKeyInfo to KeyInfoWithIdentity format
close #4378 // if this PR closes an issue
> #4378 Migrate StoredKeyInfo to KeyInfoWithIdentity format

- extension/chrome/elements/backup.ts
- test/source/tests/decrypt.ts
This PR adds the key's fingerprint when rendering the private key backups in Gmail for easier recognition of keys, useful when removing unnecessary keys permanently.
Closes #5999
Screenshots:
For already imported keys:
For unimported keys:
> #5999 Add fingerprint when rendering private backups

- conf/tsconfig.content_scripts.json
- conf/tsconfig.tooling.json
- extension/js/common/core/crypto/pgp/msg-util.ts
- extension/js/common/core/crypto/pgp/openpgp-key.ts
- extension/js/common/core/crypto/pgp/openpgpjs-custom.ts
- extension/js/common/core/crypto/pgp/pgp-armor.ts
- package-lock.json
- package.json
- tsconfig.json
This PR upgraded openpgp to v6.2
close #6049 // if this PR closes an issue
> #6049 Upgrade openpgp to v6.2

- extension/js/common/browser/browser-msg.ts
- extension/js/common/core/common.ts
- extension/js/service_worker/background.ts
This PR fixed alarm limit issue and service worker window issue
close #6024 // if this PR closes an issue
> #6024 Fix: alarm limit issue and service worker window issue

- test/source/tests/tooling/browser-recipe.ts
This PR fixed live gmail tests
close #6056 // if this PR closes an issue
> #6056 Fix live gmail tests

- extension/js/common/core/crypto/pgp/openpgp-key.ts
- extension/js/common/core/crypto/pgp/openpgpjs-custom.ts
- test/source/tests/decrypt.ts
This PR reverts changes in OpenPGP configuration.
close #6055 
> #6055 Revert changes in openpgp.js config
